; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=zluda-combine-mma -mtriple=amdgcn-amd-amdhsa %s | FileCheck %s

define void @single_call(ptr %d.result, <4 x i32> %a, <2 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: define void @single_call(
; CHECK-SAME: ptr [[D_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <4 x i32> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP6:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[TMP6]] to <8 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP4]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[D_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b, <4 x i32> %c)
  store <4 x i32> %d, ptr %d.result
  ret void
}

define void @no_shared_a(ptr %d0.result, ptr %d1.result, <4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0, <4 x i32> %a1, <2 x i32> %b1, <4 x i32> %c1) {
; CHECK-LABEL: define void @no_shared_a(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A0:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <4 x i32> [[A1:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP11:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[TMP11]] to <8 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A1]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B1]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP12:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C1]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i32> [[TMP12]] to <8 x float>
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP6]], <16 x i16> [[TMP7]], <8 x float> [[TMP8]])
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP9]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP10]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a1, <2 x i32> %b1, <4 x i32> %c1)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @dependency(ptr %d0.result, ptr %d1.result, <4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1) {
; CHECK-LABEL: define void @dependency(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A0:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP10:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[TMP10]] to <8 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B1]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP8:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP6]], <16 x i16> [[TMP7]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP8]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b1, <4 x i32> %d0)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @zext_trunc_elimination(ptr %d0.result, ptr %d1.result, <4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1) {
; CHECK-LABEL: define void @zext_trunc_elimination(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A0:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP10:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[TMP10]] to <8 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B1]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP8:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP6]], <16 x i16> [[TMP7]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP9:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP8]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b1, <4 x i32> %d0)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @combine(ptr %d0.result, ptr %d1.result, <4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1, <4 x i32> %c1) {
; CHECK-LABEL: define void @combine(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TMP3]] to <8 x float>
; CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <8 x float> [[TMP5]] to <8 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 1
; CHECK-NEXT:    store <4 x i32> [[TMP8]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b1, <4 x i32> %c1)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @use_in_middle(ptr %d0.result, ptr %d1.result, <4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1, <4 x i32> %c1) {
; CHECK-LABEL: define void @use_in_middle(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TMP3]] to <8 x float>
; CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <8 x float> [[TMP5]] to <8 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i32> [[TMP8]], i64 0
; CHECK-NEXT:    store <4 x i32> [[TMP8]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0)
  %2 = extractelement <4 x i32> %d0, i64 0
  %d1 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b1, <4 x i32> %c1)
  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @dependency_in_middle(ptr %d0.result, ptr %d1.result, <4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0, <4 x i32> %c1) {
; CHECK-LABEL: define void @dependency_in_middle(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[DEPENDENCY:%.*]] = insertelement <2 x i32> zeroinitializer, i32 0, i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> [[DEPENDENCY]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TMP3]] to <8 x float>
; CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <8 x float> [[TMP5]] to <8 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP6]])
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP7]], 1
; CHECK-NEXT:    store <4 x i32> [[TMP8]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP9]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0)
  %dependency = insertelement <2 x i32> zeroinitializer, i32 0, i64 0
  %d1 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %dependency, <4 x i32> %c1)
  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

define void @split_combine_elimination(ptr %d2.result, ptr %d3.result, <4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1, <4 x i32> %c1, <4 x i32> %a1, <2 x i32> %b2, <2 x i32> %b3) {
; CHECK-LABEL: define void @split_combine_elimination(
; CHECK-SAME: ptr [[D2_RESULT:%.*]], ptr [[D3_RESULT:%.*]], <4 x i32> [[A0:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]], <4 x i32> [[A1:%.*]], <2 x i32> [[B2:%.*]], <2 x i32> [[B3:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <8 x i32> [[TMP3]] to <8 x float>
; CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <8 x float> [[TMP5]] to <8 x i32>
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A1]])
; CHECK-NEXT:    [[TMP8:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B2]], <2 x i32> [[B3]])
; CHECK-NEXT:    [[TMP9:%.*]] = bitcast <8 x i32> [[TMP6]] to <8 x float>
; CHECK-NEXT:    [[TMP10:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP7]], <16 x i16> [[TMP8]], <8 x float> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = bitcast <8 x float> [[TMP10]] to <8 x i32>
; CHECK-NEXT:    [[TMP12:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP11]])
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP12]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP12]], 1
; CHECK-NEXT:    store <4 x i32> [[TMP13]], ptr [[D2_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP14]], ptr [[D3_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a0, <2 x i32> %b1, <4 x i32> %c1)

  %d2 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a1, <2 x i32> %b2, <4 x i32> %d0)
  %d3 = call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a1, <2 x i32> %b3, <4 x i32> %d1)
  store <4 x i32> %d2, ptr %d2.result
  store <4 x i32> %d3, ptr %d3.result

  ret void
}

define void @combine_s32(ptr %d0.result, ptr %d1.result, <4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1, <4 x i32> %c1) {
; CHECK-LABEL: define void @combine_s32(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.amatrix.split.amd16x16.nv16x32(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.bmatrix.reshape.amd16x16.nv32x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP4]], i1 true, <4 x i32> [[TMP6]], <8 x i32> [[TMP3]], i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP5]], i1 true, <4 x i32> [[TMP7]], <8 x i32> [[TMP8]], i1 false)
; CHECK-NEXT:    [[TMP10:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP10]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP10]], 1
; CHECK-NEXT:    store <4 x i32> [[TMP11]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP12]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a, <2 x i32> %b1, <4 x i32> %c1)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}

declare <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32>, <2 x i32>, <4 x i32>)

define void @dont_merge_across_load_store(ptr %d0.result, ptr %d1.result, <4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0, <4 x i32> %c1, ptr %dependency) {
; CHECK-LABEL: define void @dont_merge_across_load_store(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <4 x i32> [[C1:%.*]], ptr [[DEPENDENCY:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B0]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP11:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <8 x i32> [[TMP11]] to <8 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP1]], <16 x i16> [[TMP2]], <8 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP4]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[DEPENDENCY]], align 16
; CHECK-NEXT:    [[B1:%.*]] = load <2 x i32>, ptr [[DEPENDENCY]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8(<2 x i32> [[B1]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP12:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C1]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i32> [[TMP12]] to <8 x float>
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x16.bf16.v8f32.v16i16(<16 x i16> [[TMP6]], <16 x i16> [[TMP7]], <8 x float> [[TMP8]])
; CHECK-NEXT:    [[TMP10:%.*]] = call <4 x i32> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> [[TMP9]])
; CHECK-NEXT:    store <4 x i32> [[TMP5]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP10]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d0 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b0, <4 x i32> %c0)
  store <4 x i32> %d0, ptr %dependency
  %b1 = load <2 x i32>, ptr %dependency
  %d1 = tail call <4 x i32> @llvm.zluda.mma.m16n8k16.f32.bf16.bf16.f32(<4 x i32> %a, <2 x i32> %b1, <4 x i32> %c1)
  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result

  ret void
}


define void @combine_interleaved(ptr %d0.result, ptr %d1.result, ptr %d2.result, ptr %d3.result, <4 x i32> %a0, <4 x i32> %a1, <2 x i32> %b0, <4 x i32> %c0, <2 x i32> %b1, <4 x i32> %c1) {
; CHECK-LABEL: define void @combine_interleaved(
; CHECK-SAME: ptr [[D0_RESULT:%.*]], ptr [[D1_RESULT:%.*]], ptr [[D2_RESULT:%.*]], ptr [[D3_RESULT:%.*]], <4 x i32> [[A0:%.*]], <4 x i32> [[A1:%.*]], <2 x i32> [[B0:%.*]], <4 x i32> [[C0:%.*]], <2 x i32> [[B1:%.*]], <4 x i32> [[C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.amatrix.split.amd16x16.nv16x32(<4 x i32> [[A0]])
; CHECK-NEXT:    [[TMP2:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.bmatrix.reshape.amd16x16.nv32x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP4]], i1 true, <4 x i32> [[TMP6]], <8 x i32> [[TMP3]], i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP5]], i1 true, <4 x i32> [[TMP7]], <8 x i32> [[TMP8]], i1 false)
; CHECK-NEXT:    [[TMP10:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP10]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP10]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.amatrix.split.amd16x16.nv16x32(<4 x i32> [[A1]])
; CHECK-NEXT:    [[TMP14:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.bmatrix.reshape.amd16x16.nv32x8(<2 x i32> [[B0]], <2 x i32> [[B1]])
; CHECK-NEXT:    [[TMP15:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C0]], <4 x i32> [[C1]])
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP13]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP13]], 1
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP14]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP14]], 1
; CHECK-NEXT:    [[TMP20:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP16]], i1 true, <4 x i32> [[TMP18]], <8 x i32> [[TMP15]], i1 false)
; CHECK-NEXT:    [[TMP21:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP17]], i1 true, <4 x i32> [[TMP19]], <8 x i32> [[TMP20]], i1 false)
; CHECK-NEXT:    [[TMP22:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP21]])
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP22]], 0
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP22]], 1
; CHECK-NEXT:    store <4 x i32> [[TMP11]], ptr [[D0_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP23]], ptr [[D1_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP24]], ptr [[D2_RESULT]], align 16
; CHECK-NEXT:    store <4 x i32> [[TMP12]], ptr [[D3_RESULT]], align 16
; CHECK-NEXT:    ret void
;

  %d0 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a0, <2 x i32> %b0, <4 x i32> %c0)
  %d1 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a1, <2 x i32> %b0, <4 x i32> %c0)
  %d2 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a1, <2 x i32> %b1, <4 x i32> %c1)
  %d3 = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a0, <2 x i32> %b1, <4 x i32> %c1)

  store <4 x i32> %d0, ptr %d0.result
  store <4 x i32> %d1, ptr %d1.result
  store <4 x i32> %d2, ptr %d2.result
  store <4 x i32> %d3, ptr %d3.result

  ret void
}


define void @lower_uncombined_mma_i8(ptr %d.result, <4 x i32> %a, <2 x i32> %b, <4 x i32> %c) {
; CHECK-LABEL: define void @lower_uncombined_mma_i8(
; CHECK-SAME: ptr [[D_RESULT:%.*]], <4 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <4 x i32> [[C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.amatrix.split.amd16x16.nv16x32(<4 x i32> [[A]])
; CHECK-NEXT:    [[TMP2:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.bmatrix.reshape.amd16x16.nv32x8(<2 x i32> [[B]], <2 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i32> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8(<4 x i32> [[C]], <4 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP2]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP4]], i1 true, <4 x i32> [[TMP6]], <8 x i32> [[TMP3]], i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x i32> @llvm.amdgcn.wmma.i32.16x16x16.iu8.v8i32.v4i32(i1 true, <4 x i32> [[TMP5]], i1 true, <4 x i32> [[TMP7]], <8 x i32> [[TMP8]], i1 false)
; CHECK-NEXT:    [[TMP10:%.*]] = call { <4 x i32>, <4 x i32> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x i32> [[TMP9]])
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <4 x i32>, <4 x i32> } [[TMP10]], 0
; CHECK-NEXT:    store <4 x i32> [[TMP11]], ptr [[D_RESULT]], align 16
; CHECK-NEXT:    ret void
;
  %d = call <4 x i32> @llvm.zluda.mma.m16n8k32.s32.s8.s8.s32(<4 x i32> %a, <2 x i32> %b, <4 x i32> %c)
  store <4 x i32> %d, ptr %d.result
  ret void
}
