; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=zluda-lower-matrix-conversions -mtriple=amdgcn-amd-amdhsa %s | FileCheck %s

define void @amatrix_convert(ptr %amd_a, <4 x i32> %nv_a) {
; CHECK-LABEL: define void @amatrix_convert(
; CHECK-SAME: ptr [[AMD_A:%.*]], <4 x i32> [[NV_A:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[ROW:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[ROW]], 7
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[TMP2]], 2
; CHECK-NEXT:    [[NV_LANE:%.*]] = add i32 [[TMP3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i32 [[ROW]], 3
; CHECK-NEXT:    [[PACKED_NUMBER:%.*]] = add i32 [[TMP7]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = and i32 [[PACKED_NUMBER]], -2
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP14]]
; CHECK-NEXT:    [[NV_IDX3:%.*]] = add i32 [[TMP14]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX3]]
; CHECK-NEXT:    [[TMP8:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[A_TMP0:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP8]], i32 [[TMP5]])
; CHECK-NEXT:    [[TMP9:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[A_TMP1:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP9]], i32 [[TMP11]])
; CHECK-NEXT:    [[LANE_MOD16:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_8:%.*]] = icmp ult i32 [[LANE_MOD16]], 8
; CHECK-NEXT:    [[A_FRAG_REG:%.*]] = select i1 [[LANE_LT_8]], i32 [[A_TMP0]], i32 [[A_TMP1]]
; CHECK-NEXT:    [[BOTTOM16:%.*]] = trunc i32 [[A_FRAG_REG]] to i16
; CHECK-NEXT:    [[TMP10:%.*]] = insertelement <16 x i16> poison, i16 [[BOTTOM16]], i64 0
; CHECK-NEXT:    [[TMP13:%.*]] = lshr i32 [[A_FRAG_REG]], 16
; CHECK-NEXT:    [[ELEMENT8:%.*]] = trunc i32 [[TMP13]] to i16
; CHECK-NEXT:    [[TMP19:%.*]] = insertelement <16 x i16> [[TMP10]], i16 [[ELEMENT8]], i64 1
; CHECK-NEXT:    [[ROW9:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP20:%.*]] = and i32 [[ROW9]], 7
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[TMP20]], 2
; CHECK-NEXT:    [[TMP23:%.*]] = add i32 [[TMP22]], 1
; CHECK-NEXT:    [[TMP24:%.*]] = lshr i32 [[ROW9]], 3
; CHECK-NEXT:    [[PACKED_NUMBER12:%.*]] = add i32 [[TMP24]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = and i32 [[PACKED_NUMBER12]], -2
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP51]]
; CHECK-NEXT:    [[NV_IDX19:%.*]] = add i32 [[TMP51]], 1
; CHECK-NEXT:    [[TMP18:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX19]]
; CHECK-NEXT:    [[TMP21:%.*]] = shl i32 [[TMP23]], 2
; CHECK-NEXT:    [[A_TMP06:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP21]], i32 [[TMP16]])
; CHECK-NEXT:    [[TMP25:%.*]] = shl i32 [[TMP23]], 2
; CHECK-NEXT:    [[A_TMP17:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP25]], i32 [[TMP18]])
; CHECK-NEXT:    [[LANE_MOD168:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_89:%.*]] = icmp ult i32 [[LANE_MOD168]], 8
; CHECK-NEXT:    [[A_FRAG_REG10:%.*]] = select i1 [[LANE_LT_89]], i32 [[A_TMP06]], i32 [[A_TMP17]]
; CHECK-NEXT:    [[BOTTOM1611:%.*]] = trunc i32 [[A_FRAG_REG10]] to i16
; CHECK-NEXT:    [[TMP28:%.*]] = insertelement <16 x i16> [[TMP19]], i16 [[BOTTOM1611]], i64 2
; CHECK-NEXT:    [[TMP31:%.*]] = lshr i32 [[A_FRAG_REG10]], 16
; CHECK-NEXT:    [[ELEMENT24:%.*]] = trunc i32 [[TMP31]] to i16
; CHECK-NEXT:    [[TMP37:%.*]] = insertelement <16 x i16> [[TMP28]], i16 [[ELEMENT24]], i64 3
; CHECK-NEXT:    [[ROW25:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP38:%.*]] = and i32 [[ROW25]], 7
; CHECK-NEXT:    [[TMP40:%.*]] = shl i32 [[TMP38]], 2
; CHECK-NEXT:    [[TMP41:%.*]] = add i32 [[TMP40]], 2
; CHECK-NEXT:    [[TMP48:%.*]] = lshr i32 [[ROW25]], 3
; CHECK-NEXT:    [[PACKED_NUMBER28:%.*]] = add i32 [[TMP48]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = and i32 [[PACKED_NUMBER28]], -2
; CHECK-NEXT:    [[TMP27:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP57]]
; CHECK-NEXT:    [[NV_IDX35:%.*]] = add i32 [[TMP57]], 1
; CHECK-NEXT:    [[TMP29:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX35]]
; CHECK-NEXT:    [[TMP30:%.*]] = shl i32 [[TMP41]], 2
; CHECK-NEXT:    [[A_TMP018:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP30]], i32 [[TMP27]])
; CHECK-NEXT:    [[TMP32:%.*]] = shl i32 [[TMP41]], 2
; CHECK-NEXT:    [[A_TMP119:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP32]], i32 [[TMP29]])
; CHECK-NEXT:    [[LANE_MOD1620:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_821:%.*]] = icmp ult i32 [[LANE_MOD1620]], 8
; CHECK-NEXT:    [[A_FRAG_REG22:%.*]] = select i1 [[LANE_LT_821]], i32 [[A_TMP018]], i32 [[A_TMP119]]
; CHECK-NEXT:    [[BOTTOM1623:%.*]] = trunc i32 [[A_FRAG_REG22]] to i16
; CHECK-NEXT:    [[TMP46:%.*]] = insertelement <16 x i16> [[TMP37]], i16 [[BOTTOM1623]], i64 4
; CHECK-NEXT:    [[TMP39:%.*]] = lshr i32 [[A_FRAG_REG22]], 16
; CHECK-NEXT:    [[ELEMENT40:%.*]] = trunc i32 [[TMP39]] to i16
; CHECK-NEXT:    [[TMP55:%.*]] = insertelement <16 x i16> [[TMP46]], i16 [[ELEMENT40]], i64 5
; CHECK-NEXT:    [[ROW41:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP56:%.*]] = and i32 [[ROW41]], 7
; CHECK-NEXT:    [[TMP58:%.*]] = shl i32 [[TMP56]], 2
; CHECK-NEXT:    [[TMP59:%.*]] = add i32 [[TMP58]], 3
; CHECK-NEXT:    [[TMP69:%.*]] = lshr i32 [[ROW41]], 3
; CHECK-NEXT:    [[PACKED_NUMBER44:%.*]] = add i32 [[TMP69]], 0
; CHECK-NEXT:    [[TMP134:%.*]] = and i32 [[PACKED_NUMBER44]], -2
; CHECK-NEXT:    [[TMP43:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP134]]
; CHECK-NEXT:    [[NV_IDX51:%.*]] = add i32 [[TMP134]], 1
; CHECK-NEXT:    [[TMP44:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX51]]
; CHECK-NEXT:    [[TMP45:%.*]] = shl i32 [[TMP59]], 2
; CHECK-NEXT:    [[A_TMP030:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP45]], i32 [[TMP43]])
; CHECK-NEXT:    [[TMP42:%.*]] = shl i32 [[TMP59]], 2
; CHECK-NEXT:    [[A_TMP131:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP42]], i32 [[TMP44]])
; CHECK-NEXT:    [[LANE_MOD1632:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_833:%.*]] = icmp ult i32 [[LANE_MOD1632]], 8
; CHECK-NEXT:    [[A_FRAG_REG34:%.*]] = select i1 [[LANE_LT_833]], i32 [[A_TMP030]], i32 [[A_TMP131]]
; CHECK-NEXT:    [[BOTTOM1635:%.*]] = trunc i32 [[A_FRAG_REG34]] to i16
; CHECK-NEXT:    [[TMP64:%.*]] = insertelement <16 x i16> [[TMP55]], i16 [[BOTTOM1635]], i64 6
; CHECK-NEXT:    [[TMP52:%.*]] = lshr i32 [[A_FRAG_REG34]], 16
; CHECK-NEXT:    [[ELEMENT56:%.*]] = trunc i32 [[TMP52]] to i16
; CHECK-NEXT:    [[TMP73:%.*]] = insertelement <16 x i16> [[TMP64]], i16 [[ELEMENT56]], i64 7
; CHECK-NEXT:    [[ROW57:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP74:%.*]] = and i32 [[ROW57]], 7
; CHECK-NEXT:    [[TMP60:%.*]] = shl i32 [[TMP74]], 2
; CHECK-NEXT:    [[NV_LANE38:%.*]] = add i32 [[TMP60]], 0
; CHECK-NEXT:    [[TMP104:%.*]] = lshr i32 [[ROW57]], 3
; CHECK-NEXT:    [[PACKED_NUMBER60:%.*]] = add i32 [[TMP104]], 2
; CHECK-NEXT:    [[TMP86:%.*]] = and i32 [[PACKED_NUMBER60]], -2
; CHECK-NEXT:    [[TMP49:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP86]]
; CHECK-NEXT:    [[NV_IDX67:%.*]] = add i32 [[TMP86]], 1
; CHECK-NEXT:    [[TMP54:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX67]]
; CHECK-NEXT:    [[TMP61:%.*]] = shl i32 [[NV_LANE38]], 2
; CHECK-NEXT:    [[A_TMP042:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP61]], i32 [[TMP49]])
; CHECK-NEXT:    [[TMP53:%.*]] = shl i32 [[NV_LANE38]], 2
; CHECK-NEXT:    [[A_TMP143:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP53]], i32 [[TMP54]])
; CHECK-NEXT:    [[LANE_MOD1644:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_845:%.*]] = icmp ult i32 [[LANE_MOD1644]], 8
; CHECK-NEXT:    [[A_FRAG_REG46:%.*]] = select i1 [[LANE_LT_845]], i32 [[A_TMP042]], i32 [[A_TMP143]]
; CHECK-NEXT:    [[BOTTOM1647:%.*]] = trunc i32 [[A_FRAG_REG46]] to i16
; CHECK-NEXT:    [[TMP82:%.*]] = insertelement <16 x i16> [[TMP73]], i16 [[BOTTOM1647]], i64 8
; CHECK-NEXT:    [[TMP65:%.*]] = lshr i32 [[A_FRAG_REG46]], 16
; CHECK-NEXT:    [[ELEMENT72:%.*]] = trunc i32 [[TMP65]] to i16
; CHECK-NEXT:    [[TMP91:%.*]] = insertelement <16 x i16> [[TMP82]], i16 [[ELEMENT72]], i64 9
; CHECK-NEXT:    [[ROW73:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP92:%.*]] = and i32 [[ROW73]], 7
; CHECK-NEXT:    [[TMP93:%.*]] = shl i32 [[TMP92]], 2
; CHECK-NEXT:    [[NV_LANE74:%.*]] = add i32 [[TMP93]], 1
; CHECK-NEXT:    [[TMP94:%.*]] = lshr i32 [[ROW73]], 3
; CHECK-NEXT:    [[PACKED_NUMBER76:%.*]] = add i32 [[TMP94]], 2
; CHECK-NEXT:    [[TMP105:%.*]] = and i32 [[PACKED_NUMBER76]], -2
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP105]]
; CHECK-NEXT:    [[NV_IDX83:%.*]] = add i32 [[TMP105]], 1
; CHECK-NEXT:    [[TMP62:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX83]]
; CHECK-NEXT:    [[TMP63:%.*]] = shl i32 [[NV_LANE74]], 2
; CHECK-NEXT:    [[A_TMP054:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP63]], i32 [[TMP66]])
; CHECK-NEXT:    [[TMP67:%.*]] = shl i32 [[NV_LANE74]], 2
; CHECK-NEXT:    [[A_TMP155:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP67]], i32 [[TMP62]])
; CHECK-NEXT:    [[LANE_MOD1656:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_857:%.*]] = icmp ult i32 [[LANE_MOD1656]], 8
; CHECK-NEXT:    [[A_FRAG_REG58:%.*]] = select i1 [[LANE_LT_857]], i32 [[A_TMP054]], i32 [[A_TMP155]]
; CHECK-NEXT:    [[BOTTOM1659:%.*]] = trunc i32 [[A_FRAG_REG58]] to i16
; CHECK-NEXT:    [[TMP100:%.*]] = insertelement <16 x i16> [[TMP91]], i16 [[BOTTOM1659]], i64 10
; CHECK-NEXT:    [[TMP78:%.*]] = lshr i32 [[A_FRAG_REG58]], 16
; CHECK-NEXT:    [[ELEMENT88:%.*]] = trunc i32 [[TMP78]] to i16
; CHECK-NEXT:    [[TMP109:%.*]] = insertelement <16 x i16> [[TMP100]], i16 [[ELEMENT88]], i64 11
; CHECK-NEXT:    [[ROW89:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP110:%.*]] = and i32 [[ROW89]], 7
; CHECK-NEXT:    [[TMP111:%.*]] = shl i32 [[TMP110]], 2
; CHECK-NEXT:    [[NV_LANE90:%.*]] = add i32 [[TMP111]], 2
; CHECK-NEXT:    [[TMP140:%.*]] = lshr i32 [[ROW89]], 3
; CHECK-NEXT:    [[PACKED_NUMBER92:%.*]] = add i32 [[TMP140]], 2
; CHECK-NEXT:    [[TMP123:%.*]] = and i32 [[PACKED_NUMBER92]], -2
; CHECK-NEXT:    [[TMP71:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP123]]
; CHECK-NEXT:    [[NV_IDX99:%.*]] = add i32 [[TMP123]], 1
; CHECK-NEXT:    [[TMP76:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX99]]
; CHECK-NEXT:    [[TMP77:%.*]] = shl i32 [[NV_LANE90]], 2
; CHECK-NEXT:    [[A_TMP066:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP77]], i32 [[TMP71]])
; CHECK-NEXT:    [[TMP75:%.*]] = shl i32 [[NV_LANE90]], 2
; CHECK-NEXT:    [[A_TMP167:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP75]], i32 [[TMP76]])
; CHECK-NEXT:    [[LANE_MOD1668:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_869:%.*]] = icmp ult i32 [[LANE_MOD1668]], 8
; CHECK-NEXT:    [[A_FRAG_REG70:%.*]] = select i1 [[LANE_LT_869]], i32 [[A_TMP066]], i32 [[A_TMP167]]
; CHECK-NEXT:    [[BOTTOM1671:%.*]] = trunc i32 [[A_FRAG_REG70]] to i16
; CHECK-NEXT:    [[TMP118:%.*]] = insertelement <16 x i16> [[TMP109]], i16 [[BOTTOM1671]], i64 12
; CHECK-NEXT:    [[TMP95:%.*]] = lshr i32 [[A_FRAG_REG70]], 16
; CHECK-NEXT:    [[ELEMENT104:%.*]] = trunc i32 [[TMP95]] to i16
; CHECK-NEXT:    [[TMP127:%.*]] = insertelement <16 x i16> [[TMP118]], i16 [[ELEMENT104]], i64 13
; CHECK-NEXT:    [[ROW105:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP128:%.*]] = and i32 [[ROW105]], 7
; CHECK-NEXT:    [[TMP129:%.*]] = shl i32 [[TMP128]], 2
; CHECK-NEXT:    [[NV_LANE106:%.*]] = add i32 [[TMP129]], 3
; CHECK-NEXT:    [[TMP130:%.*]] = lshr i32 [[ROW105]], 3
; CHECK-NEXT:    [[PACKED_NUMBER108:%.*]] = add i32 [[TMP130]], 2
; CHECK-NEXT:    [[TMP141:%.*]] = and i32 [[PACKED_NUMBER108]], -2
; CHECK-NEXT:    [[TMP83:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[TMP141]]
; CHECK-NEXT:    [[NV_IDX115:%.*]] = add i32 [[TMP141]], 1
; CHECK-NEXT:    [[TMP84:%.*]] = extractelement <4 x i32> [[NV_A]], i32 [[NV_IDX115]]
; CHECK-NEXT:    [[TMP85:%.*]] = shl i32 [[NV_LANE106]], 2
; CHECK-NEXT:    [[A_TMP078:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP85]], i32 [[TMP83]])
; CHECK-NEXT:    [[TMP87:%.*]] = shl i32 [[NV_LANE106]], 2
; CHECK-NEXT:    [[A_TMP179:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP87]], i32 [[TMP84]])
; CHECK-NEXT:    [[LANE_MOD1680:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[LANE_LT_881:%.*]] = icmp ult i32 [[LANE_MOD1680]], 8
; CHECK-NEXT:    [[A_FRAG_REG82:%.*]] = select i1 [[LANE_LT_881]], i32 [[A_TMP078]], i32 [[A_TMP179]]
; CHECK-NEXT:    [[BOTTOM1683:%.*]] = trunc i32 [[A_FRAG_REG82]] to i16
; CHECK-NEXT:    [[TMP136:%.*]] = insertelement <16 x i16> [[TMP127]], i16 [[BOTTOM1683]], i64 14
; CHECK-NEXT:    [[TMP107:%.*]] = lshr i32 [[A_FRAG_REG82]], 16
; CHECK-NEXT:    [[ELEMENT120:%.*]] = trunc i32 [[TMP107]] to i16
; CHECK-NEXT:    [[TMP145:%.*]] = insertelement <16 x i16> [[TMP136]], i16 [[ELEMENT120]], i64 15
; CHECK-NEXT:    store <16 x i16> [[TMP145]], ptr [[AMD_A]], align 32
; CHECK-NEXT:    ret void
;
  %converted_a = call <16 x i16> @llvm.zluda.amatrix.convert.amd.nv16x16.v16i16.v4i32(<4 x i32> %nv_a)
  store <16 x i16> %converted_a, ptr %amd_a

  ret void
}

define void @bmatrix_zext(ptr %amd_b, <2 x i32> %nv_b) {
; CHECK-LABEL: define void @bmatrix_zext(
; CHECK-SAME: ptr [[AMD_B:%.*]], <2 x i32> [[NV_B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ult i32 [[TMP2]], 8
; CHECK-NEXT:    [[TMP7:%.*]] = and i32 [[TMP2]], 7
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[TMP7]], 2
; CHECK-NEXT:    [[NV_LANE:%.*]] = add i32 [[TMP3]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x i32> [[NV_B]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[PACKED:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP6]], i32 [[TMP5]])
; CHECK-NEXT:    [[BOTTOM16_FIRST:%.*]] = trunc i32 [[PACKED]] to i16
; CHECK-NEXT:    [[TMP11:%.*]] = select i1 [[TMP9]], i16 [[BOTTOM16_FIRST]], i16 0
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <16 x i16> poison, i16 [[TMP11]], i64 0
; CHECK-NEXT:    [[TMP8:%.*]] = lshr i32 [[PACKED]], 16
; CHECK-NEXT:    [[TOP16_FIRST:%.*]] = trunc i32 [[TMP8]] to i16
; CHECK-NEXT:    [[TMP14:%.*]] = select i1 [[TMP9]], i16 [[TOP16_FIRST]], i16 0
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <16 x i16> [[TMP12]], i16 [[TMP14]], i64 1
; CHECK-NEXT:    [[ROW6:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST7:%.*]] = icmp ult i32 [[ROW6]], 8
; CHECK-NEXT:    [[TMP16:%.*]] = and i32 [[ROW6]], 7
; CHECK-NEXT:    [[TMP17:%.*]] = shl i32 [[TMP16]], 2
; CHECK-NEXT:    [[NV_LANE8:%.*]] = add i32 [[TMP17]], 1
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <2 x i32> [[NV_B]], i64 0
; CHECK-NEXT:    [[TMP20:%.*]] = shl i32 [[NV_LANE8]], 2
; CHECK-NEXT:    [[PACKED9:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP20]], i32 [[TMP19]])
; CHECK-NEXT:    [[BOTTOM16_FIRST5:%.*]] = trunc i32 [[PACKED9]] to i16
; CHECK-NEXT:    [[TMP24:%.*]] = select i1 [[IS_IN_FIRST7]], i16 [[BOTTOM16_FIRST5]], i16 0
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <16 x i16> [[TMP15]], i16 [[TMP24]], i64 2
; CHECK-NEXT:    [[TMP18:%.*]] = lshr i32 [[PACKED9]], 16
; CHECK-NEXT:    [[TOP16_FIRST7:%.*]] = trunc i32 [[TMP18]] to i16
; CHECK-NEXT:    [[TMP27:%.*]] = select i1 [[IS_IN_FIRST7]], i16 [[TOP16_FIRST7]], i16 0
; CHECK-NEXT:    [[TMP28:%.*]] = insertelement <16 x i16> [[TMP25]], i16 [[TMP27]], i64 3
; CHECK-NEXT:    [[ROW16:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST17:%.*]] = icmp ult i32 [[ROW16]], 8
; CHECK-NEXT:    [[TMP30:%.*]] = and i32 [[ROW16]], 7
; CHECK-NEXT:    [[TMP31:%.*]] = shl i32 [[TMP30]], 2
; CHECK-NEXT:    [[NV_LANE18:%.*]] = add i32 [[TMP31]], 2
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <2 x i32> [[NV_B]], i64 0
; CHECK-NEXT:    [[TMP34:%.*]] = shl i32 [[NV_LANE18]], 2
; CHECK-NEXT:    [[PACKED19:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP34]], i32 [[TMP33]])
; CHECK-NEXT:    [[BOTTOM16_FIRST13:%.*]] = trunc i32 [[PACKED19]] to i16
; CHECK-NEXT:    [[TMP37:%.*]] = select i1 [[IS_IN_FIRST17]], i16 [[BOTTOM16_FIRST13]], i16 0
; CHECK-NEXT:    [[TMP38:%.*]] = insertelement <16 x i16> [[TMP28]], i16 [[TMP37]], i64 4
; CHECK-NEXT:    [[TMP21:%.*]] = lshr i32 [[PACKED19]], 16
; CHECK-NEXT:    [[TOP16_FIRST15:%.*]] = trunc i32 [[TMP21]] to i16
; CHECK-NEXT:    [[TMP40:%.*]] = select i1 [[IS_IN_FIRST17]], i16 [[TOP16_FIRST15]], i16 0
; CHECK-NEXT:    [[TMP41:%.*]] = insertelement <16 x i16> [[TMP38]], i16 [[TMP40]], i64 5
; CHECK-NEXT:    [[ROW26:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST27:%.*]] = icmp ult i32 [[ROW26]], 8
; CHECK-NEXT:    [[TMP44:%.*]] = and i32 [[ROW26]], 7
; CHECK-NEXT:    [[TMP45:%.*]] = shl i32 [[TMP44]], 2
; CHECK-NEXT:    [[NV_LANE28:%.*]] = add i32 [[TMP45]], 3
; CHECK-NEXT:    [[TMP47:%.*]] = extractelement <2 x i32> [[NV_B]], i64 0
; CHECK-NEXT:    [[TMP48:%.*]] = shl i32 [[NV_LANE28]], 2
; CHECK-NEXT:    [[PACKED29:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP48]], i32 [[TMP47]])
; CHECK-NEXT:    [[BOTTOM16_FIRST21:%.*]] = trunc i32 [[PACKED29]] to i16
; CHECK-NEXT:    [[TMP50:%.*]] = select i1 [[IS_IN_FIRST27]], i16 [[BOTTOM16_FIRST21]], i16 0
; CHECK-NEXT:    [[TMP51:%.*]] = insertelement <16 x i16> [[TMP41]], i16 [[TMP50]], i64 6
; CHECK-NEXT:    [[TMP29:%.*]] = lshr i32 [[PACKED29]], 16
; CHECK-NEXT:    [[TOP16_FIRST23:%.*]] = trunc i32 [[TMP29]] to i16
; CHECK-NEXT:    [[TMP53:%.*]] = select i1 [[IS_IN_FIRST27]], i16 [[TOP16_FIRST23]], i16 0
; CHECK-NEXT:    [[TMP54:%.*]] = insertelement <16 x i16> [[TMP51]], i16 [[TMP53]], i64 7
; CHECK-NEXT:    [[ROW36:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST37:%.*]] = icmp ult i32 [[ROW36]], 8
; CHECK-NEXT:    [[TMP58:%.*]] = and i32 [[ROW36]], 7
; CHECK-NEXT:    [[TMP59:%.*]] = shl i32 [[TMP58]], 2
; CHECK-NEXT:    [[NV_LANE38:%.*]] = add i32 [[TMP59]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractelement <2 x i32> [[NV_B]], i64 1
; CHECK-NEXT:    [[TMP62:%.*]] = shl i32 [[NV_LANE38]], 2
; CHECK-NEXT:    [[PACKED39:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP62]], i32 [[TMP61]])
; CHECK-NEXT:    [[BOTTOM16_FIRST29:%.*]] = trunc i32 [[PACKED39]] to i16
; CHECK-NEXT:    [[TMP63:%.*]] = select i1 [[IS_IN_FIRST37]], i16 [[BOTTOM16_FIRST29]], i16 0
; CHECK-NEXT:    [[TMP64:%.*]] = insertelement <16 x i16> [[TMP54]], i16 [[TMP63]], i64 8
; CHECK-NEXT:    [[TMP35:%.*]] = lshr i32 [[PACKED39]], 16
; CHECK-NEXT:    [[TOP16_FIRST31:%.*]] = trunc i32 [[TMP35]] to i16
; CHECK-NEXT:    [[TMP66:%.*]] = select i1 [[IS_IN_FIRST37]], i16 [[TOP16_FIRST31]], i16 0
; CHECK-NEXT:    [[TMP67:%.*]] = insertelement <16 x i16> [[TMP64]], i16 [[TMP66]], i64 9
; CHECK-NEXT:    [[ROW46:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST47:%.*]] = icmp ult i32 [[ROW46]], 8
; CHECK-NEXT:    [[TMP72:%.*]] = and i32 [[ROW46]], 7
; CHECK-NEXT:    [[TMP73:%.*]] = shl i32 [[TMP72]], 2
; CHECK-NEXT:    [[NV_LANE48:%.*]] = add i32 [[TMP73]], 1
; CHECK-NEXT:    [[TMP121:%.*]] = extractelement <2 x i32> [[NV_B]], i64 1
; CHECK-NEXT:    [[TMP122:%.*]] = shl i32 [[NV_LANE48]], 2
; CHECK-NEXT:    [[PACKED49:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP122]], i32 [[TMP121]])
; CHECK-NEXT:    [[BOTTOM16_FIRST37:%.*]] = trunc i32 [[PACKED49]] to i16
; CHECK-NEXT:    [[TMP76:%.*]] = select i1 [[IS_IN_FIRST47]], i16 [[BOTTOM16_FIRST37]], i16 0
; CHECK-NEXT:    [[TMP77:%.*]] = insertelement <16 x i16> [[TMP67]], i16 [[TMP76]], i64 10
; CHECK-NEXT:    [[TMP42:%.*]] = lshr i32 [[PACKED49]], 16
; CHECK-NEXT:    [[TOP16_FIRST39:%.*]] = trunc i32 [[TMP42]] to i16
; CHECK-NEXT:    [[TMP79:%.*]] = select i1 [[IS_IN_FIRST47]], i16 [[TOP16_FIRST39]], i16 0
; CHECK-NEXT:    [[TMP80:%.*]] = insertelement <16 x i16> [[TMP77]], i16 [[TMP79]], i64 11
; CHECK-NEXT:    [[ROW56:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST57:%.*]] = icmp ult i32 [[ROW56]], 8
; CHECK-NEXT:    [[TMP86:%.*]] = and i32 [[ROW56]], 7
; CHECK-NEXT:    [[TMP87:%.*]] = shl i32 [[TMP86]], 2
; CHECK-NEXT:    [[NV_LANE58:%.*]] = add i32 [[TMP87]], 2
; CHECK-NEXT:    [[TMP126:%.*]] = extractelement <2 x i32> [[NV_B]], i64 1
; CHECK-NEXT:    [[TMP127:%.*]] = shl i32 [[NV_LANE58]], 2
; CHECK-NEXT:    [[PACKED59:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP127]], i32 [[TMP126]])
; CHECK-NEXT:    [[BOTTOM16_FIRST45:%.*]] = trunc i32 [[PACKED59]] to i16
; CHECK-NEXT:    [[TMP89:%.*]] = select i1 [[IS_IN_FIRST57]], i16 [[BOTTOM16_FIRST45]], i16 0
; CHECK-NEXT:    [[TMP90:%.*]] = insertelement <16 x i16> [[TMP80]], i16 [[TMP89]], i64 12
; CHECK-NEXT:    [[TMP49:%.*]] = lshr i32 [[PACKED59]], 16
; CHECK-NEXT:    [[TOP16_FIRST47:%.*]] = trunc i32 [[TMP49]] to i16
; CHECK-NEXT:    [[TMP92:%.*]] = select i1 [[IS_IN_FIRST57]], i16 [[TOP16_FIRST47]], i16 0
; CHECK-NEXT:    [[TMP93:%.*]] = insertelement <16 x i16> [[TMP90]], i16 [[TMP92]], i64 13
; CHECK-NEXT:    [[ROW66:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST67:%.*]] = icmp ult i32 [[ROW66]], 8
; CHECK-NEXT:    [[TMP100:%.*]] = and i32 [[ROW66]], 7
; CHECK-NEXT:    [[TMP129:%.*]] = shl i32 [[TMP100]], 2
; CHECK-NEXT:    [[NV_LANE68:%.*]] = add i32 [[TMP129]], 3
; CHECK-NEXT:    [[TMP132:%.*]] = extractelement <2 x i32> [[NV_B]], i64 1
; CHECK-NEXT:    [[TMP104:%.*]] = shl i32 [[NV_LANE68]], 2
; CHECK-NEXT:    [[PACKED69:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP104]], i32 [[TMP132]])
; CHECK-NEXT:    [[BOTTOM16_FIRST53:%.*]] = trunc i32 [[PACKED69]] to i16
; CHECK-NEXT:    [[TMP102:%.*]] = select i1 [[IS_IN_FIRST67]], i16 [[BOTTOM16_FIRST53]], i16 0
; CHECK-NEXT:    [[TMP103:%.*]] = insertelement <16 x i16> [[TMP93]], i16 [[TMP102]], i64 14
; CHECK-NEXT:    [[TMP56:%.*]] = lshr i32 [[PACKED69]], 16
; CHECK-NEXT:    [[TOP16_FIRST55:%.*]] = trunc i32 [[TMP56]] to i16
; CHECK-NEXT:    [[TMP105:%.*]] = select i1 [[IS_IN_FIRST67]], i16 [[TOP16_FIRST55]], i16 0
; CHECK-NEXT:    [[TMP106:%.*]] = insertelement <16 x i16> [[TMP103]], i16 [[TMP105]], i64 15
; CHECK-NEXT:    store <16 x i16> [[TMP106]], ptr [[AMD_B]], align 32
; CHECK-NEXT:    ret void
;
  %converted_b = call <16 x i16> @llvm.zluda.bmatrix.zext.amd16x16.nv16x8.v16i16.v2i32(<2 x i32> %nv_b)
  store <16 x i16> %converted_b, ptr %amd_b

  ret void
}

define void @bmatrix_concatenate(ptr %amd_b, <2 x i32> %nv_b0, <2 x i32> %nv_b1) {
; CHECK-LABEL: define void @bmatrix_concatenate(
; CHECK-SAME: ptr [[AMD_B:%.*]], <2 x i32> [[NV_B0:%.*]], <2 x i32> [[NV_B1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ult i32 [[TMP2]], 8
; CHECK-NEXT:    [[TMP5:%.*]] = and i32 [[TMP2]], 7
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[TMP5]], 2
; CHECK-NEXT:    [[NV_LANE:%.*]] = add i32 [[TMP3]], 0
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 0
; CHECK-NEXT:    [[TMP6:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[PACKED4:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP6]], i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP7]], i32 [[TMP9]])
; CHECK-NEXT:    [[BOTTOM16_FIRST:%.*]] = trunc i32 [[PACKED4]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND:%.*]] = trunc i32 [[B_FRAG_REG_SECOND]] to i16
; CHECK-NEXT:    [[ELEMENT:%.*]] = select i1 [[TMP12]], i16 [[BOTTOM16_FIRST]], i16 [[BOTTOM16_SECOND]]
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <16 x i16> poison, i16 [[ELEMENT]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = lshr i32 [[PACKED4]], 16
; CHECK-NEXT:    [[TOP16_FIRST:%.*]] = trunc i32 [[TMP11]] to i16
; CHECK-NEXT:    [[TMP10:%.*]] = lshr i32 [[B_FRAG_REG_SECOND]], 16
; CHECK-NEXT:    [[TOP16_SECOND:%.*]] = trunc i32 [[TMP10]] to i16
; CHECK-NEXT:    [[ELEMENT5:%.*]] = select i1 [[TMP12]], i16 [[TOP16_FIRST]], i16 [[TOP16_SECOND]]
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <16 x i16> [[TMP8]], i16 [[ELEMENT5]], i64 1
; CHECK-NEXT:    [[ROW6:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST7:%.*]] = icmp ult i32 [[ROW6]], 8
; CHECK-NEXT:    [[TMP16:%.*]] = and i32 [[ROW6]], 7
; CHECK-NEXT:    [[TMP17:%.*]] = shl i32 [[TMP16]], 2
; CHECK-NEXT:    [[NV_LANE8:%.*]] = add i32 [[TMP17]], 1
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 0
; CHECK-NEXT:    [[TMP21:%.*]] = shl i32 [[NV_LANE8]], 2
; CHECK-NEXT:    [[TMP29:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP21]], i32 [[TMP19]])
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[NV_LANE8]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND5:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP22]], i32 [[TMP15]])
; CHECK-NEXT:    [[BOTTOM16_FIRST6:%.*]] = trunc i32 [[TMP29]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND7:%.*]] = trunc i32 [[B_FRAG_REG_SECOND5]] to i16
; CHECK-NEXT:    [[TMP30:%.*]] = select i1 [[IS_IN_FIRST7]], i16 [[BOTTOM16_FIRST6]], i16 [[BOTTOM16_SECOND7]]
; CHECK-NEXT:    [[TMP31:%.*]] = insertelement <16 x i16> [[TMP18]], i16 [[TMP30]], i64 2
; CHECK-NEXT:    [[TMP23:%.*]] = lshr i32 [[TMP29]], 16
; CHECK-NEXT:    [[TOP16_FIRST9:%.*]] = trunc i32 [[TMP23]] to i16
; CHECK-NEXT:    [[TMP20:%.*]] = lshr i32 [[B_FRAG_REG_SECOND5]], 16
; CHECK-NEXT:    [[TOP16_SECOND10:%.*]] = trunc i32 [[TMP20]] to i16
; CHECK-NEXT:    [[TMP33:%.*]] = select i1 [[IS_IN_FIRST7]], i16 [[TOP16_FIRST9]], i16 [[TOP16_SECOND10]]
; CHECK-NEXT:    [[TMP34:%.*]] = insertelement <16 x i16> [[TMP31]], i16 [[TMP33]], i64 3
; CHECK-NEXT:    [[ROW16:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST17:%.*]] = icmp ult i32 [[ROW16]], 8
; CHECK-NEXT:    [[TMP56:%.*]] = and i32 [[ROW16]], 7
; CHECK-NEXT:    [[TMP76:%.*]] = shl i32 [[TMP56]], 2
; CHECK-NEXT:    [[NV_LANE18:%.*]] = add i32 [[TMP76]], 2
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 0
; CHECK-NEXT:    [[TMP26:%.*]] = shl i32 [[NV_LANE18]], 2
; CHECK-NEXT:    [[PACKED24:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP26]], i32 [[TMP24]])
; CHECK-NEXT:    [[TMP27:%.*]] = shl i32 [[NV_LANE18]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND16:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP27]], i32 [[TMP25]])
; CHECK-NEXT:    [[BOTTOM16_FIRST17:%.*]] = trunc i32 [[PACKED24]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND18:%.*]] = trunc i32 [[B_FRAG_REG_SECOND16]] to i16
; CHECK-NEXT:    [[ELEMENT20:%.*]] = select i1 [[IS_IN_FIRST17]], i16 [[BOTTOM16_FIRST17]], i16 [[BOTTOM16_SECOND18]]
; CHECK-NEXT:    [[TMP36:%.*]] = insertelement <16 x i16> [[TMP34]], i16 [[ELEMENT20]], i64 4
; CHECK-NEXT:    [[TMP32:%.*]] = lshr i32 [[PACKED24]], 16
; CHECK-NEXT:    [[TOP16_FIRST20:%.*]] = trunc i32 [[TMP32]] to i16
; CHECK-NEXT:    [[TMP38:%.*]] = lshr i32 [[B_FRAG_REG_SECOND16]], 16
; CHECK-NEXT:    [[TOP16_SECOND21:%.*]] = trunc i32 [[TMP38]] to i16
; CHECK-NEXT:    [[ELEMENT25:%.*]] = select i1 [[IS_IN_FIRST17]], i16 [[TOP16_FIRST20]], i16 [[TOP16_SECOND21]]
; CHECK-NEXT:    [[TMP50:%.*]] = insertelement <16 x i16> [[TMP36]], i16 [[ELEMENT25]], i64 5
; CHECK-NEXT:    [[ROW26:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST27:%.*]] = icmp ult i32 [[ROW26]], 8
; CHECK-NEXT:    [[TMP44:%.*]] = and i32 [[ROW26]], 7
; CHECK-NEXT:    [[TMP45:%.*]] = shl i32 [[TMP44]], 2
; CHECK-NEXT:    [[NV_LANE28:%.*]] = add i32 [[TMP45]], 3
; CHECK-NEXT:    [[TMP39:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 0
; CHECK-NEXT:    [[TMP41:%.*]] = shl i32 [[NV_LANE28]], 2
; CHECK-NEXT:    [[TMP61:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP41]], i32 [[TMP39]])
; CHECK-NEXT:    [[TMP37:%.*]] = shl i32 [[NV_LANE28]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND27:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP37]], i32 [[TMP35]])
; CHECK-NEXT:    [[BOTTOM16_FIRST28:%.*]] = trunc i32 [[TMP61]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND29:%.*]] = trunc i32 [[B_FRAG_REG_SECOND27]] to i16
; CHECK-NEXT:    [[TMP62:%.*]] = select i1 [[IS_IN_FIRST27]], i16 [[BOTTOM16_FIRST28]], i16 [[BOTTOM16_SECOND29]]
; CHECK-NEXT:    [[TMP63:%.*]] = insertelement <16 x i16> [[TMP50]], i16 [[TMP62]], i64 6
; CHECK-NEXT:    [[TMP42:%.*]] = lshr i32 [[TMP61]], 16
; CHECK-NEXT:    [[TOP16_FIRST31:%.*]] = trunc i32 [[TMP42]] to i16
; CHECK-NEXT:    [[TMP40:%.*]] = lshr i32 [[B_FRAG_REG_SECOND27]], 16
; CHECK-NEXT:    [[TOP16_SECOND32:%.*]] = trunc i32 [[TMP40]] to i16
; CHECK-NEXT:    [[TMP65:%.*]] = select i1 [[IS_IN_FIRST27]], i16 [[TOP16_FIRST31]], i16 [[TOP16_SECOND32]]
; CHECK-NEXT:    [[TMP66:%.*]] = insertelement <16 x i16> [[TMP63]], i16 [[TMP65]], i64 7
; CHECK-NEXT:    [[ROW36:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST37:%.*]] = icmp ult i32 [[ROW36]], 8
; CHECK-NEXT:    [[TMP58:%.*]] = and i32 [[ROW36]], 7
; CHECK-NEXT:    [[TMP115:%.*]] = shl i32 [[TMP58]], 2
; CHECK-NEXT:    [[NV_LANE38:%.*]] = add i32 [[TMP115]], 0
; CHECK-NEXT:    [[TMP48:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 1
; CHECK-NEXT:    [[TMP49:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 1
; CHECK-NEXT:    [[TMP46:%.*]] = shl i32 [[NV_LANE38]], 2
; CHECK-NEXT:    [[TMP77:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP46]], i32 [[TMP48]])
; CHECK-NEXT:    [[TMP47:%.*]] = shl i32 [[NV_LANE38]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND38:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP47]], i32 [[TMP49]])
; CHECK-NEXT:    [[BOTTOM16_FIRST39:%.*]] = trunc i32 [[TMP77]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND40:%.*]] = trunc i32 [[B_FRAG_REG_SECOND38]] to i16
; CHECK-NEXT:    [[TMP78:%.*]] = select i1 [[IS_IN_FIRST37]], i16 [[BOTTOM16_FIRST39]], i16 [[BOTTOM16_SECOND40]]
; CHECK-NEXT:    [[TMP79:%.*]] = insertelement <16 x i16> [[TMP66]], i16 [[TMP78]], i64 8
; CHECK-NEXT:    [[TMP51:%.*]] = lshr i32 [[TMP77]], 16
; CHECK-NEXT:    [[TOP16_FIRST42:%.*]] = trunc i32 [[TMP51]] to i16
; CHECK-NEXT:    [[TMP52:%.*]] = lshr i32 [[B_FRAG_REG_SECOND38]], 16
; CHECK-NEXT:    [[TOP16_SECOND43:%.*]] = trunc i32 [[TMP52]] to i16
; CHECK-NEXT:    [[TMP81:%.*]] = select i1 [[IS_IN_FIRST37]], i16 [[TOP16_FIRST42]], i16 [[TOP16_SECOND43]]
; CHECK-NEXT:    [[TMP82:%.*]] = insertelement <16 x i16> [[TMP79]], i16 [[TMP81]], i64 9
; CHECK-NEXT:    [[ROW46:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST47:%.*]] = icmp ult i32 [[ROW46]], 8
; CHECK-NEXT:    [[TMP72:%.*]] = and i32 [[ROW46]], 7
; CHECK-NEXT:    [[TMP73:%.*]] = shl i32 [[TMP72]], 2
; CHECK-NEXT:    [[NV_LANE48:%.*]] = add i32 [[TMP73]], 1
; CHECK-NEXT:    [[TMP54:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 1
; CHECK-NEXT:    [[TMP55:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 1
; CHECK-NEXT:    [[TMP59:%.*]] = shl i32 [[NV_LANE48]], 2
; CHECK-NEXT:    [[PACKED54:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP59]], i32 [[TMP54]])
; CHECK-NEXT:    [[TMP57:%.*]] = shl i32 [[NV_LANE48]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND49:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP57]], i32 [[TMP55]])
; CHECK-NEXT:    [[BOTTOM16_FIRST50:%.*]] = trunc i32 [[PACKED54]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND51:%.*]] = trunc i32 [[B_FRAG_REG_SECOND49]] to i16
; CHECK-NEXT:    [[ELEMENT50:%.*]] = select i1 [[IS_IN_FIRST47]], i16 [[BOTTOM16_FIRST50]], i16 [[BOTTOM16_SECOND51]]
; CHECK-NEXT:    [[TMP122:%.*]] = insertelement <16 x i16> [[TMP82]], i16 [[ELEMENT50]], i64 10
; CHECK-NEXT:    [[TMP64:%.*]] = lshr i32 [[PACKED54]], 16
; CHECK-NEXT:    [[TOP16_FIRST53:%.*]] = trunc i32 [[TMP64]] to i16
; CHECK-NEXT:    [[TMP60:%.*]] = lshr i32 [[B_FRAG_REG_SECOND49]], 16
; CHECK-NEXT:    [[TOP16_SECOND54:%.*]] = trunc i32 [[TMP60]] to i16
; CHECK-NEXT:    [[ELEMENT55:%.*]] = select i1 [[IS_IN_FIRST47]], i16 [[TOP16_FIRST53]], i16 [[TOP16_SECOND54]]
; CHECK-NEXT:    [[TMP98:%.*]] = insertelement <16 x i16> [[TMP122]], i16 [[ELEMENT55]], i64 11
; CHECK-NEXT:    [[ROW56:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST57:%.*]] = icmp ult i32 [[ROW56]], 8
; CHECK-NEXT:    [[TMP86:%.*]] = and i32 [[ROW56]], 7
; CHECK-NEXT:    [[TMP87:%.*]] = shl i32 [[TMP86]], 2
; CHECK-NEXT:    [[NV_LANE58:%.*]] = add i32 [[TMP87]], 2
; CHECK-NEXT:    [[TMP68:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 1
; CHECK-NEXT:    [[TMP69:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 1
; CHECK-NEXT:    [[TMP71:%.*]] = shl i32 [[NV_LANE58]], 2
; CHECK-NEXT:    [[TMP109:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP71]], i32 [[TMP68]])
; CHECK-NEXT:    [[TMP67:%.*]] = shl i32 [[NV_LANE58]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND60:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP67]], i32 [[TMP69]])
; CHECK-NEXT:    [[BOTTOM16_FIRST61:%.*]] = trunc i32 [[TMP109]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND62:%.*]] = trunc i32 [[B_FRAG_REG_SECOND60]] to i16
; CHECK-NEXT:    [[TMP110:%.*]] = select i1 [[IS_IN_FIRST57]], i16 [[BOTTOM16_FIRST61]], i16 [[BOTTOM16_SECOND62]]
; CHECK-NEXT:    [[TMP111:%.*]] = insertelement <16 x i16> [[TMP98]], i16 [[TMP110]], i64 12
; CHECK-NEXT:    [[TMP84:%.*]] = lshr i32 [[TMP109]], 16
; CHECK-NEXT:    [[TOP16_FIRST64:%.*]] = trunc i32 [[TMP84]] to i16
; CHECK-NEXT:    [[TMP70:%.*]] = lshr i32 [[B_FRAG_REG_SECOND60]], 16
; CHECK-NEXT:    [[TOP16_SECOND65:%.*]] = trunc i32 [[TMP70]] to i16
; CHECK-NEXT:    [[TMP113:%.*]] = select i1 [[IS_IN_FIRST57]], i16 [[TOP16_FIRST64]], i16 [[TOP16_SECOND65]]
; CHECK-NEXT:    [[TMP114:%.*]] = insertelement <16 x i16> [[TMP111]], i16 [[TMP113]], i64 13
; CHECK-NEXT:    [[ROW66:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST67:%.*]] = icmp ult i32 [[ROW66]], 8
; CHECK-NEXT:    [[TMP100:%.*]] = and i32 [[ROW66]], 7
; CHECK-NEXT:    [[TMP101:%.*]] = shl i32 [[TMP100]], 2
; CHECK-NEXT:    [[NV_LANE68:%.*]] = add i32 [[TMP101]], 3
; CHECK-NEXT:    [[TMP74:%.*]] = extractelement <2 x i32> [[NV_B0]], i64 1
; CHECK-NEXT:    [[TMP75:%.*]] = extractelement <2 x i32> [[NV_B1]], i64 1
; CHECK-NEXT:    [[TMP83:%.*]] = shl i32 [[NV_LANE68]], 2
; CHECK-NEXT:    [[PACKED74:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP83]], i32 [[TMP74]])
; CHECK-NEXT:    [[TMP85:%.*]] = shl i32 [[NV_LANE68]], 2
; CHECK-NEXT:    [[B_FRAG_REG_SECOND71:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP85]], i32 [[TMP75]])
; CHECK-NEXT:    [[BOTTOM16_FIRST72:%.*]] = trunc i32 [[PACKED74]] to i16
; CHECK-NEXT:    [[BOTTOM16_SECOND73:%.*]] = trunc i32 [[B_FRAG_REG_SECOND71]] to i16
; CHECK-NEXT:    [[TMP126:%.*]] = select i1 [[IS_IN_FIRST67]], i16 [[BOTTOM16_FIRST72]], i16 [[BOTTOM16_SECOND73]]
; CHECK-NEXT:    [[TMP127:%.*]] = insertelement <16 x i16> [[TMP114]], i16 [[TMP126]], i64 14
; CHECK-NEXT:    [[TMP88:%.*]] = lshr i32 [[PACKED74]], 16
; CHECK-NEXT:    [[TOP16_FIRST75:%.*]] = trunc i32 [[TMP88]] to i16
; CHECK-NEXT:    [[TMP80:%.*]] = lshr i32 [[B_FRAG_REG_SECOND71]], 16
; CHECK-NEXT:    [[TOP16_SECOND76:%.*]] = trunc i32 [[TMP80]] to i16
; CHECK-NEXT:    [[TMP129:%.*]] = select i1 [[IS_IN_FIRST67]], i16 [[TOP16_FIRST75]], i16 [[TOP16_SECOND76]]
; CHECK-NEXT:    [[CONVERTED_B:%.*]] = insertelement <16 x i16> [[TMP127]], i16 [[TMP129]], i64 15
; CHECK-NEXT:    store <16 x i16> [[CONVERTED_B]], ptr [[AMD_B]], align 32
; CHECK-NEXT:    ret void
;
  %converted_b = call <16 x i16> @llvm.zluda.bmatrix.concatenate.amd16x16.nv16x8.v16i16.v2i32(<2 x i32> %nv_b0, <2 x i32> %nv_b1)
  store <16 x i16> %converted_b, ptr %amd_b

  ret void
}

define void @cmatrix_zext(ptr %amd_c, <4 x float> %nv_c) {
; CHECK-LABEL: define void @cmatrix_zext(
; CHECK-SAME: ptr [[AMD_C:%.*]], <4 x float> [[NV_C:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[TMP11:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW:%.*]] = add i32 0, [[TMP11]]
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult i32 [[TMP2]], 8
; CHECK-NEXT:    [[TMP14:%.*]] = and i32 [[ROW]], 7
; CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[TMP2]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP:%.*]] = lshr i32 [[TMP4]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = shl i32 [[TMP14]], 2
; CHECK-NEXT:    [[NV_LANE:%.*]] = add i32 [[TMP5]], [[THREAD_ID_IN_GROUP]]
; CHECK-NEXT:    [[TMP6:%.*]] = and i32 [[TMP2]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i32 [[ROW]], 3
; CHECK-NEXT:    [[TMP8:%.*]] = shl i32 [[TMP7]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], [[TMP6]]
; CHECK-NEXT:    [[BASE_IDX:%.*]] = and i32 [[TMP9]], -2
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX]]
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX]]
; CHECK-NEXT:    [[TMP12:%.*]] = add i32 [[BASE_IDX]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP12]]
; CHECK-NEXT:    [[TMP58:%.*]] = add i32 [[BASE_IDX]], 1
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP58]]
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast float [[TMP10]] to i32
; CHECK-NEXT:    [[TMP60:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP0_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP60]], i32 [[TMP16]])
; CHECK-NEXT:    [[TMP88:%.*]] = bitcast i32 [[CTMP0_FIRST]] to float
; CHECK-NEXT:    [[TMP19:%.*]] = bitcast float [[TMP31]] to i32
; CHECK-NEXT:    [[TMP92:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP0_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP92]], i32 [[TMP19]])
; CHECK-NEXT:    [[TMP113:%.*]] = bitcast i32 [[CTMP0_SECOND]] to float
; CHECK-NEXT:    [[TMP114:%.*]] = bitcast float [[TMP13]] to i32
; CHECK-NEXT:    [[TMP23:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP1_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP23]], i32 [[TMP114]])
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast i32 [[CTMP1_FIRST]] to float
; CHECK-NEXT:    [[TMP116:%.*]] = bitcast float [[TMP15]] to i32
; CHECK-NEXT:    [[TMP118:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP1_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP118]], i32 [[TMP116]])
; CHECK-NEXT:    [[TMP27:%.*]] = bitcast i32 [[CTMP1_SECOND]] to float
; CHECK-NEXT:    [[TMP28:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD:%.*]] = trunc i32 [[TMP28]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST:%.*]] = select i1 [[LANE_IS_ODD]], float [[TMP24]], float [[TMP88]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND:%.*]] = select i1 [[LANE_IS_ODD]], float [[TMP27]], float [[TMP113]]
; CHECK-NEXT:    [[TMP30:%.*]] = select i1 [[TMP3]], float [[CFRAG_VALUE_FIRST]], float [[CFRAG_VALUE_SECOND]]
; CHECK-NEXT:    [[TMP25:%.*]] = insertelement <8 x float> poison, float [[TMP30]], i64 0
; CHECK-NEXT:    [[TMP26:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW1:%.*]] = add i32 2, [[TMP26]]
; CHECK-NEXT:    [[COLUMN2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST3:%.*]] = icmp ult i32 [[COLUMN2]], 8
; CHECK-NEXT:    [[TMP17:%.*]] = and i32 [[ROW1]], 7
; CHECK-NEXT:    [[TMP18:%.*]] = and i32 [[COLUMN2]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP4:%.*]] = lshr i32 [[TMP18]], 1
; CHECK-NEXT:    [[TMP33:%.*]] = shl i32 [[TMP17]], 2
; CHECK-NEXT:    [[NV_LANE5:%.*]] = add i32 [[TMP33]], [[THREAD_ID_IN_GROUP4]]
; CHECK-NEXT:    [[TMP20:%.*]] = and i32 [[COLUMN2]], 1
; CHECK-NEXT:    [[TMP21:%.*]] = lshr i32 [[ROW1]], 3
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[TMP21]], 1
; CHECK-NEXT:    [[TMP37:%.*]] = add i32 [[TMP22]], [[TMP20]]
; CHECK-NEXT:    [[BASE_IDX6:%.*]] = and i32 [[TMP37]], -2
; CHECK-NEXT:    [[TMP38:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX6]]
; CHECK-NEXT:    [[TMP119:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX6]]
; CHECK-NEXT:    [[TMP40:%.*]] = add i32 [[BASE_IDX6]], 1
; CHECK-NEXT:    [[TMP41:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP40]]
; CHECK-NEXT:    [[TMP120:%.*]] = add i32 [[BASE_IDX6]], 1
; CHECK-NEXT:    [[TMP43:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP120]]
; CHECK-NEXT:    [[TMP141:%.*]] = bitcast float [[TMP38]] to i32
; CHECK-NEXT:    [[TMP142:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP0_FIRST7:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP142]], i32 [[TMP141]])
; CHECK-NEXT:    [[TMP46:%.*]] = bitcast i32 [[CTMP0_FIRST7]] to float
; CHECK-NEXT:    [[TMP47:%.*]] = bitcast float [[TMP119]] to i32
; CHECK-NEXT:    [[TMP143:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP0_SECOND8:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP143]], i32 [[TMP47]])
; CHECK-NEXT:    [[TMP144:%.*]] = bitcast i32 [[CTMP0_SECOND8]] to float
; CHECK-NEXT:    [[TMP50:%.*]] = bitcast float [[TMP41]] to i32
; CHECK-NEXT:    [[TMP51:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP1_FIRST9:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP51]], i32 [[TMP50]])
; CHECK-NEXT:    [[TMP52:%.*]] = bitcast i32 [[CTMP1_FIRST9]] to float
; CHECK-NEXT:    [[TMP146:%.*]] = bitcast float [[TMP43]] to i32
; CHECK-NEXT:    [[TMP147:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP1_SECOND10:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP147]], i32 [[TMP146]])
; CHECK-NEXT:    [[TMP148:%.*]] = bitcast i32 [[CTMP1_SECOND10]] to float
; CHECK-NEXT:    [[TMP169:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD11:%.*]] = trunc i32 [[TMP169]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST12:%.*]] = select i1 [[LANE_IS_ODD11]], float [[TMP52]], float [[TMP46]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND13:%.*]] = select i1 [[LANE_IS_ODD11]], float [[TMP148]], float [[TMP144]]
; CHECK-NEXT:    [[TMP39:%.*]] = select i1 [[IS_IN_FIRST3]], float [[CFRAG_VALUE_FIRST12]], float [[CFRAG_VALUE_SECOND13]]
; CHECK-NEXT:    [[TMP29:%.*]] = insertelement <8 x float> [[TMP25]], float [[TMP39]], i64 1
; CHECK-NEXT:    [[TMP32:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW7:%.*]] = add i32 4, [[TMP32]]
; CHECK-NEXT:    [[COLUMN8:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST9:%.*]] = icmp ult i32 [[COLUMN8]], 8
; CHECK-NEXT:    [[TMP49:%.*]] = and i32 [[ROW7]], 7
; CHECK-NEXT:    [[TMP42:%.*]] = and i32 [[COLUMN8]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP10:%.*]] = lshr i32 [[TMP42]], 1
; CHECK-NEXT:    [[TMP61:%.*]] = shl i32 [[TMP49]], 2
; CHECK-NEXT:    [[NV_LANE19:%.*]] = add i32 [[TMP61]], [[THREAD_ID_IN_GROUP10]]
; CHECK-NEXT:    [[TMP34:%.*]] = and i32 [[COLUMN8]], 1
; CHECK-NEXT:    [[TMP35:%.*]] = lshr i32 [[ROW7]], 3
; CHECK-NEXT:    [[TMP36:%.*]] = shl i32 [[TMP35]], 1
; CHECK-NEXT:    [[TMP65:%.*]] = add i32 [[TMP36]], [[TMP34]]
; CHECK-NEXT:    [[BASE_IDX20:%.*]] = and i32 [[TMP65]], -2
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX20]]
; CHECK-NEXT:    [[TMP170:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX20]]
; CHECK-NEXT:    [[TMP172:%.*]] = add i32 [[BASE_IDX20]], 1
; CHECK-NEXT:    [[TMP69:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP172]]
; CHECK-NEXT:    [[TMP70:%.*]] = add i32 [[BASE_IDX20]], 1
; CHECK-NEXT:    [[TMP174:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP70]]
; CHECK-NEXT:    [[TMP175:%.*]] = bitcast float [[TMP66]] to i32
; CHECK-NEXT:    [[TMP176:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP0_FIRST21:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP176]], i32 [[TMP175]])
; CHECK-NEXT:    [[TMP74:%.*]] = bitcast i32 [[CTMP0_FIRST21]] to float
; CHECK-NEXT:    [[TMP75:%.*]] = bitcast float [[TMP170]] to i32
; CHECK-NEXT:    [[TMP197:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP0_SECOND22:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP197]], i32 [[TMP75]])
; CHECK-NEXT:    [[TMP198:%.*]] = bitcast i32 [[CTMP0_SECOND22]] to float
; CHECK-NEXT:    [[TMP199:%.*]] = bitcast float [[TMP69]] to i32
; CHECK-NEXT:    [[TMP79:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP1_FIRST23:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP79]], i32 [[TMP199]])
; CHECK-NEXT:    [[TMP200:%.*]] = bitcast i32 [[CTMP1_FIRST23]] to float
; CHECK-NEXT:    [[TMP202:%.*]] = bitcast float [[TMP174]] to i32
; CHECK-NEXT:    [[TMP82:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP1_SECOND24:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP82]], i32 [[TMP202]])
; CHECK-NEXT:    [[TMP83:%.*]] = bitcast i32 [[CTMP1_SECOND24]] to float
; CHECK-NEXT:    [[TMP84:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD25:%.*]] = trunc i32 [[TMP84]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST26:%.*]] = select i1 [[LANE_IS_ODD25]], float [[TMP200]], float [[TMP74]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND27:%.*]] = select i1 [[LANE_IS_ODD25]], float [[TMP83]], float [[TMP198]]
; CHECK-NEXT:    [[TMP73:%.*]] = select i1 [[IS_IN_FIRST9]], float [[CFRAG_VALUE_FIRST26]], float [[CFRAG_VALUE_SECOND27]]
; CHECK-NEXT:    [[TMP53:%.*]] = insertelement <8 x float> [[TMP29]], float [[TMP73]], i64 2
; CHECK-NEXT:    [[TMP44:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW13:%.*]] = add i32 6, [[TMP44]]
; CHECK-NEXT:    [[COLUMN14:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST15:%.*]] = icmp ult i32 [[COLUMN14]], 8
; CHECK-NEXT:    [[TMP45:%.*]] = and i32 [[ROW13]], 7
; CHECK-NEXT:    [[TMP55:%.*]] = and i32 [[COLUMN14]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP16:%.*]] = lshr i32 [[TMP55]], 1
; CHECK-NEXT:    [[TMP89:%.*]] = shl i32 [[TMP45]], 2
; CHECK-NEXT:    [[NV_LANE33:%.*]] = add i32 [[TMP89]], [[THREAD_ID_IN_GROUP16]]
; CHECK-NEXT:    [[TMP48:%.*]] = and i32 [[COLUMN14]], 1
; CHECK-NEXT:    [[TMP54:%.*]] = lshr i32 [[ROW13]], 3
; CHECK-NEXT:    [[TMP56:%.*]] = shl i32 [[TMP54]], 1
; CHECK-NEXT:    [[TMP93:%.*]] = add i32 [[TMP56]], [[TMP48]]
; CHECK-NEXT:    [[BASE_IDX34:%.*]] = and i32 [[TMP93]], -2
; CHECK-NEXT:    [[TMP94:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX34]]
; CHECK-NEXT:    [[TMP95:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX34]]
; CHECK-NEXT:    [[TMP96:%.*]] = add i32 [[BASE_IDX34]], 1
; CHECK-NEXT:    [[TMP203:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP96]]
; CHECK-NEXT:    [[TMP204:%.*]] = add i32 [[BASE_IDX34]], 1
; CHECK-NEXT:    [[TMP99:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP204]]
; CHECK-NEXT:    [[TMP100:%.*]] = bitcast float [[TMP94]] to i32
; CHECK-NEXT:    [[TMP225:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP0_FIRST35:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP225]], i32 [[TMP100]])
; CHECK-NEXT:    [[TMP226:%.*]] = bitcast i32 [[CTMP0_FIRST35]] to float
; CHECK-NEXT:    [[TMP103:%.*]] = bitcast float [[TMP95]] to i32
; CHECK-NEXT:    [[TMP227:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP0_SECOND36:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP227]], i32 [[TMP103]])
; CHECK-NEXT:    [[TMP228:%.*]] = bitcast i32 [[CTMP0_SECOND36]] to float
; CHECK-NEXT:    [[TMP229:%.*]] = bitcast float [[TMP203]] to i32
; CHECK-NEXT:    [[TMP107:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP1_FIRST37:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP107]], i32 [[TMP229]])
; CHECK-NEXT:    [[TMP108:%.*]] = bitcast i32 [[CTMP1_FIRST37]] to float
; CHECK-NEXT:    [[TMP230:%.*]] = bitcast float [[TMP99]] to i32
; CHECK-NEXT:    [[TMP231:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP1_SECOND38:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP231]], i32 [[TMP230]])
; CHECK-NEXT:    [[TMP111:%.*]] = bitcast i32 [[CTMP1_SECOND38]] to float
; CHECK-NEXT:    [[TMP232:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD39:%.*]] = trunc i32 [[TMP232]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST40:%.*]] = select i1 [[LANE_IS_ODD39]], float [[TMP108]], float [[TMP226]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND41:%.*]] = select i1 [[LANE_IS_ODD39]], float [[TMP111]], float [[TMP228]]
; CHECK-NEXT:    [[TMP106:%.*]] = select i1 [[IS_IN_FIRST15]], float [[CFRAG_VALUE_FIRST40]], float [[CFRAG_VALUE_SECOND41]]
; CHECK-NEXT:    [[TMP57:%.*]] = insertelement <8 x float> [[TMP53]], float [[TMP106]], i64 3
; CHECK-NEXT:    [[TMP67:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW19:%.*]] = add i32 8, [[TMP67]]
; CHECK-NEXT:    [[COLUMN20:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST21:%.*]] = icmp ult i32 [[COLUMN20]], 8
; CHECK-NEXT:    [[TMP59:%.*]] = and i32 [[ROW19]], 7
; CHECK-NEXT:    [[TMP68:%.*]] = and i32 [[COLUMN20]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP22:%.*]] = lshr i32 [[TMP68]], 1
; CHECK-NEXT:    [[TMP117:%.*]] = shl i32 [[TMP59]], 2
; CHECK-NEXT:    [[NV_LANE47:%.*]] = add i32 [[TMP117]], [[THREAD_ID_IN_GROUP22]]
; CHECK-NEXT:    [[TMP62:%.*]] = and i32 [[COLUMN20]], 1
; CHECK-NEXT:    [[TMP63:%.*]] = lshr i32 [[ROW19]], 3
; CHECK-NEXT:    [[TMP64:%.*]] = shl i32 [[TMP63]], 1
; CHECK-NEXT:    [[TMP121:%.*]] = add i32 [[TMP64]], [[TMP62]]
; CHECK-NEXT:    [[BASE_IDX48:%.*]] = and i32 [[TMP121]], -2
; CHECK-NEXT:    [[TMP122:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX48]]
; CHECK-NEXT:    [[TMP123:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX48]]
; CHECK-NEXT:    [[TMP124:%.*]] = add i32 [[BASE_IDX48]], 1
; CHECK-NEXT:    [[TMP125:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP124]]
; CHECK-NEXT:    [[TMP126:%.*]] = add i32 [[BASE_IDX48]], 1
; CHECK-NEXT:    [[TMP233:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP126]]
; CHECK-NEXT:    [[TMP128:%.*]] = bitcast float [[TMP122]] to i32
; CHECK-NEXT:    [[TMP129:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP0_FIRST49:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP129]], i32 [[TMP128]])
; CHECK-NEXT:    [[TMP130:%.*]] = bitcast i32 [[CTMP0_FIRST49]] to float
; CHECK-NEXT:    [[TMP131:%.*]] = bitcast float [[TMP123]] to i32
; CHECK-NEXT:    [[TMP132:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP0_SECOND50:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP132]], i32 [[TMP131]])
; CHECK-NEXT:    [[TMP133:%.*]] = bitcast i32 [[CTMP0_SECOND50]] to float
; CHECK-NEXT:    [[TMP134:%.*]] = bitcast float [[TMP125]] to i32
; CHECK-NEXT:    [[TMP135:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP1_FIRST51:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP135]], i32 [[TMP134]])
; CHECK-NEXT:    [[TMP136:%.*]] = bitcast i32 [[CTMP1_FIRST51]] to float
; CHECK-NEXT:    [[TMP137:%.*]] = bitcast float [[TMP233]] to i32
; CHECK-NEXT:    [[TMP138:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP1_SECOND52:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP138]], i32 [[TMP137]])
; CHECK-NEXT:    [[TMP139:%.*]] = bitcast i32 [[CTMP1_SECOND52]] to float
; CHECK-NEXT:    [[TMP140:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD53:%.*]] = trunc i32 [[TMP140]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST54:%.*]] = select i1 [[LANE_IS_ODD53]], float [[TMP136]], float [[TMP130]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND55:%.*]] = select i1 [[LANE_IS_ODD53]], float [[TMP139]], float [[TMP133]]
; CHECK-NEXT:    [[TMP105:%.*]] = select i1 [[IS_IN_FIRST21]], float [[CFRAG_VALUE_FIRST54]], float [[CFRAG_VALUE_SECOND55]]
; CHECK-NEXT:    [[TMP71:%.*]] = insertelement <8 x float> [[TMP57]], float [[TMP105]], i64 4
; CHECK-NEXT:    [[TMP72:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW25:%.*]] = add i32 10, [[TMP72]]
; CHECK-NEXT:    [[COLUMN26:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST27:%.*]] = icmp ult i32 [[COLUMN26]], 8
; CHECK-NEXT:    [[TMP80:%.*]] = and i32 [[ROW25]], 7
; CHECK-NEXT:    [[TMP81:%.*]] = and i32 [[COLUMN26]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP28:%.*]] = lshr i32 [[TMP81]], 1
; CHECK-NEXT:    [[TMP145:%.*]] = shl i32 [[TMP80]], 2
; CHECK-NEXT:    [[NV_LANE61:%.*]] = add i32 [[TMP145]], [[THREAD_ID_IN_GROUP28]]
; CHECK-NEXT:    [[TMP76:%.*]] = and i32 [[COLUMN26]], 1
; CHECK-NEXT:    [[TMP77:%.*]] = lshr i32 [[ROW25]], 3
; CHECK-NEXT:    [[TMP78:%.*]] = shl i32 [[TMP77]], 1
; CHECK-NEXT:    [[TMP234:%.*]] = add i32 [[TMP78]], [[TMP76]]
; CHECK-NEXT:    [[BASE_IDX62:%.*]] = and i32 [[TMP234]], -2
; CHECK-NEXT:    [[TMP150:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX62]]
; CHECK-NEXT:    [[TMP151:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX62]]
; CHECK-NEXT:    [[TMP152:%.*]] = add i32 [[BASE_IDX62]], 1
; CHECK-NEXT:    [[TMP235:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP152]]
; CHECK-NEXT:    [[TMP154:%.*]] = add i32 [[BASE_IDX62]], 1
; CHECK-NEXT:    [[TMP155:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP154]]
; CHECK-NEXT:    [[TMP156:%.*]] = bitcast float [[TMP150]] to i32
; CHECK-NEXT:    [[TMP157:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP0_FIRST63:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP157]], i32 [[TMP156]])
; CHECK-NEXT:    [[TMP158:%.*]] = bitcast i32 [[CTMP0_FIRST63]] to float
; CHECK-NEXT:    [[TMP159:%.*]] = bitcast float [[TMP151]] to i32
; CHECK-NEXT:    [[TMP160:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP0_SECOND64:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP160]], i32 [[TMP159]])
; CHECK-NEXT:    [[TMP161:%.*]] = bitcast i32 [[CTMP0_SECOND64]] to float
; CHECK-NEXT:    [[TMP162:%.*]] = bitcast float [[TMP235]] to i32
; CHECK-NEXT:    [[TMP163:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP1_FIRST65:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP163]], i32 [[TMP162]])
; CHECK-NEXT:    [[TMP164:%.*]] = bitcast i32 [[CTMP1_FIRST65]] to float
; CHECK-NEXT:    [[TMP165:%.*]] = bitcast float [[TMP155]] to i32
; CHECK-NEXT:    [[TMP166:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP1_SECOND66:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP166]], i32 [[TMP165]])
; CHECK-NEXT:    [[TMP167:%.*]] = bitcast i32 [[CTMP1_SECOND66]] to float
; CHECK-NEXT:    [[TMP168:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD67:%.*]] = trunc i32 [[TMP168]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST68:%.*]] = select i1 [[LANE_IS_ODD67]], float [[TMP164]], float [[TMP158]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND69:%.*]] = select i1 [[LANE_IS_ODD67]], float [[TMP167]], float [[TMP161]]
; CHECK-NEXT:    [[TMP127:%.*]] = select i1 [[IS_IN_FIRST27]], float [[CFRAG_VALUE_FIRST68]], float [[CFRAG_VALUE_SECOND69]]
; CHECK-NEXT:    [[TMP85:%.*]] = insertelement <8 x float> [[TMP71]], float [[TMP127]], i64 5
; CHECK-NEXT:    [[TMP86:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW31:%.*]] = add i32 12, [[TMP86]]
; CHECK-NEXT:    [[COLUMN32:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST33:%.*]] = icmp ult i32 [[COLUMN32]], 8
; CHECK-NEXT:    [[TMP87:%.*]] = and i32 [[ROW31]], 7
; CHECK-NEXT:    [[TMP97:%.*]] = and i32 [[COLUMN32]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP34:%.*]] = lshr i32 [[TMP97]], 1
; CHECK-NEXT:    [[TMP173:%.*]] = shl i32 [[TMP87]], 2
; CHECK-NEXT:    [[NV_LANE75:%.*]] = add i32 [[TMP173]], [[THREAD_ID_IN_GROUP34]]
; CHECK-NEXT:    [[TMP90:%.*]] = and i32 [[COLUMN32]], 1
; CHECK-NEXT:    [[TMP91:%.*]] = lshr i32 [[ROW31]], 3
; CHECK-NEXT:    [[TMP98:%.*]] = shl i32 [[TMP91]], 1
; CHECK-NEXT:    [[TMP177:%.*]] = add i32 [[TMP98]], [[TMP90]]
; CHECK-NEXT:    [[BASE_IDX76:%.*]] = and i32 [[TMP177]], -2
; CHECK-NEXT:    [[TMP178:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX76]]
; CHECK-NEXT:    [[TMP179:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX76]]
; CHECK-NEXT:    [[TMP180:%.*]] = add i32 [[BASE_IDX76]], 1
; CHECK-NEXT:    [[TMP181:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP180]]
; CHECK-NEXT:    [[TMP182:%.*]] = add i32 [[BASE_IDX76]], 1
; CHECK-NEXT:    [[TMP183:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP182]]
; CHECK-NEXT:    [[TMP184:%.*]] = bitcast float [[TMP178]] to i32
; CHECK-NEXT:    [[TMP185:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP0_FIRST77:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP185]], i32 [[TMP184]])
; CHECK-NEXT:    [[TMP186:%.*]] = bitcast i32 [[CTMP0_FIRST77]] to float
; CHECK-NEXT:    [[TMP187:%.*]] = bitcast float [[TMP179]] to i32
; CHECK-NEXT:    [[TMP188:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP0_SECOND78:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP188]], i32 [[TMP187]])
; CHECK-NEXT:    [[TMP189:%.*]] = bitcast i32 [[CTMP0_SECOND78]] to float
; CHECK-NEXT:    [[TMP190:%.*]] = bitcast float [[TMP181]] to i32
; CHECK-NEXT:    [[TMP191:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP1_FIRST79:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP191]], i32 [[TMP190]])
; CHECK-NEXT:    [[TMP192:%.*]] = bitcast i32 [[CTMP1_FIRST79]] to float
; CHECK-NEXT:    [[TMP193:%.*]] = bitcast float [[TMP183]] to i32
; CHECK-NEXT:    [[TMP194:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP1_SECOND80:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP194]], i32 [[TMP193]])
; CHECK-NEXT:    [[TMP195:%.*]] = bitcast i32 [[CTMP1_SECOND80]] to float
; CHECK-NEXT:    [[TMP196:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD81:%.*]] = trunc i32 [[TMP196]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST82:%.*]] = select i1 [[LANE_IS_ODD81]], float [[TMP192]], float [[TMP186]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND83:%.*]] = select i1 [[LANE_IS_ODD81]], float [[TMP195]], float [[TMP189]]
; CHECK-NEXT:    [[TMP149:%.*]] = select i1 [[IS_IN_FIRST33]], float [[CFRAG_VALUE_FIRST82]], float [[CFRAG_VALUE_SECOND83]]
; CHECK-NEXT:    [[TMP102:%.*]] = insertelement <8 x float> [[TMP85]], float [[TMP149]], i64 6
; CHECK-NEXT:    [[TMP109:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW37:%.*]] = add i32 14, [[TMP109]]
; CHECK-NEXT:    [[COLUMN38:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST39:%.*]] = icmp ult i32 [[COLUMN38]], 8
; CHECK-NEXT:    [[TMP101:%.*]] = and i32 [[ROW37]], 7
; CHECK-NEXT:    [[TMP110:%.*]] = and i32 [[COLUMN38]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP40:%.*]] = lshr i32 [[TMP110]], 1
; CHECK-NEXT:    [[TMP201:%.*]] = shl i32 [[TMP101]], 2
; CHECK-NEXT:    [[NV_LANE89:%.*]] = add i32 [[TMP201]], [[THREAD_ID_IN_GROUP40]]
; CHECK-NEXT:    [[TMP104:%.*]] = and i32 [[COLUMN38]], 1
; CHECK-NEXT:    [[TMP112:%.*]] = lshr i32 [[ROW37]], 3
; CHECK-NEXT:    [[TMP115:%.*]] = shl i32 [[TMP112]], 1
; CHECK-NEXT:    [[TMP205:%.*]] = add i32 [[TMP115]], [[TMP104]]
; CHECK-NEXT:    [[BASE_IDX90:%.*]] = and i32 [[TMP205]], -2
; CHECK-NEXT:    [[TMP206:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[BASE_IDX90]]
; CHECK-NEXT:    [[TMP207:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[BASE_IDX90]]
; CHECK-NEXT:    [[TMP208:%.*]] = add i32 [[BASE_IDX90]], 1
; CHECK-NEXT:    [[TMP209:%.*]] = extractelement <4 x float> [[NV_C]], i32 [[TMP208]]
; CHECK-NEXT:    [[TMP210:%.*]] = add i32 [[BASE_IDX90]], 1
; CHECK-NEXT:    [[TMP211:%.*]] = extractelement <4 x float> zeroinitializer, i32 [[TMP210]]
; CHECK-NEXT:    [[TMP212:%.*]] = bitcast float [[TMP206]] to i32
; CHECK-NEXT:    [[TMP213:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP0_FIRST91:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP213]], i32 [[TMP212]])
; CHECK-NEXT:    [[TMP214:%.*]] = bitcast i32 [[CTMP0_FIRST91]] to float
; CHECK-NEXT:    [[TMP215:%.*]] = bitcast float [[TMP207]] to i32
; CHECK-NEXT:    [[TMP216:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP0_SECOND92:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP216]], i32 [[TMP215]])
; CHECK-NEXT:    [[TMP217:%.*]] = bitcast i32 [[CTMP0_SECOND92]] to float
; CHECK-NEXT:    [[TMP218:%.*]] = bitcast float [[TMP209]] to i32
; CHECK-NEXT:    [[TMP219:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP1_FIRST93:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP219]], i32 [[TMP218]])
; CHECK-NEXT:    [[TMP220:%.*]] = bitcast i32 [[CTMP1_FIRST93]] to float
; CHECK-NEXT:    [[TMP221:%.*]] = bitcast float [[TMP211]] to i32
; CHECK-NEXT:    [[TMP222:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP1_SECOND94:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP222]], i32 [[TMP221]])
; CHECK-NEXT:    [[TMP223:%.*]] = bitcast i32 [[CTMP1_SECOND94]] to float
; CHECK-NEXT:    [[TMP224:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD95:%.*]] = trunc i32 [[TMP224]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST96:%.*]] = select i1 [[LANE_IS_ODD95]], float [[TMP220]], float [[TMP214]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND97:%.*]] = select i1 [[LANE_IS_ODD95]], float [[TMP223]], float [[TMP217]]
; CHECK-NEXT:    [[TMP171:%.*]] = select i1 [[IS_IN_FIRST39]], float [[CFRAG_VALUE_FIRST96]], float [[CFRAG_VALUE_SECOND97]]
; CHECK-NEXT:    [[TMP153:%.*]] = insertelement <8 x float> [[TMP102]], float [[TMP171]], i64 7
; CHECK-NEXT:    store <8 x float> [[TMP153]], ptr [[AMD_C]], align 32
; CHECK-NEXT:    ret void
;
  %converted_c = call <8 x float> @llvm.zluda.cmatrix.zext.amd16x16.nv16x8.v8f32.v4f32(<4 x float> %nv_c)
  store <8 x float> %converted_c, ptr %amd_c

  ret void
}

define void @cmatrix_concatenate(ptr %amd_c, <4 x float> %nv_c0, <4 x float> %nv_c1) {
; CHECK-LABEL: define void @cmatrix_concatenate(
; CHECK-SAME: ptr [[AMD_C:%.*]], <4 x float> [[NV_C0:%.*]], <4 x float> [[NV_C1:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[TMP11:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW:%.*]] = add i32 0, [[TMP11]]
; CHECK-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult i32 [[TMP2]], 8
; CHECK-NEXT:    [[TMP14:%.*]] = and i32 [[ROW]], 7
; CHECK-NEXT:    [[TMP4:%.*]] = and i32 [[TMP2]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP:%.*]] = lshr i32 [[TMP4]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = shl i32 [[TMP14]], 2
; CHECK-NEXT:    [[NV_LANE:%.*]] = add i32 [[TMP5]], [[THREAD_ID_IN_GROUP]]
; CHECK-NEXT:    [[TMP6:%.*]] = and i32 [[TMP2]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = lshr i32 [[ROW]], 3
; CHECK-NEXT:    [[TMP8:%.*]] = shl i32 [[TMP7]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP8]], [[TMP6]]
; CHECK-NEXT:    [[BASE_IDX:%.*]] = and i32 [[TMP9]], -2
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX]]
; CHECK-NEXT:    [[TMP29:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX]]
; CHECK-NEXT:    [[TMP12:%.*]] = add i32 [[BASE_IDX]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP12]]
; CHECK-NEXT:    [[TMP57:%.*]] = add i32 [[BASE_IDX]], 1
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP57]]
; CHECK-NEXT:    [[TMP58:%.*]] = bitcast float [[TMP10]] to i32
; CHECK-NEXT:    [[TMP60:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP0_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP60]], i32 [[TMP58]])
; CHECK-NEXT:    [[TMP85:%.*]] = bitcast i32 [[CTMP0_FIRST]] to float
; CHECK-NEXT:    [[TMP19:%.*]] = bitcast float [[TMP29]] to i32
; CHECK-NEXT:    [[TMP113:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP0_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP113]], i32 [[TMP19]])
; CHECK-NEXT:    [[TMP114:%.*]] = bitcast i32 [[CTMP0_SECOND]] to float
; CHECK-NEXT:    [[TMP115:%.*]] = bitcast float [[TMP13]] to i32
; CHECK-NEXT:    [[TMP23:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP1_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP23]], i32 [[TMP115]])
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast i32 [[CTMP1_FIRST]] to float
; CHECK-NEXT:    [[TMP25:%.*]] = bitcast float [[TMP15]] to i32
; CHECK-NEXT:    [[TMP26:%.*]] = shl i32 [[NV_LANE]], 2
; CHECK-NEXT:    [[CTMP1_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP26]], i32 [[TMP25]])
; CHECK-NEXT:    [[TMP27:%.*]] = bitcast i32 [[CTMP1_SECOND]] to float
; CHECK-NEXT:    [[TMP28:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD:%.*]] = trunc i32 [[TMP28]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST:%.*]] = select i1 [[LANE_IS_ODD]], float [[TMP24]], float [[TMP85]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND:%.*]] = select i1 [[LANE_IS_ODD]], float [[TMP27]], float [[TMP114]]
; CHECK-NEXT:    [[TMP33:%.*]] = select i1 [[TMP3]], float [[CFRAG_VALUE_FIRST]], float [[CFRAG_VALUE_SECOND]]
; CHECK-NEXT:    [[TMP34:%.*]] = insertelement <8 x float> poison, float [[TMP33]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW1:%.*]] = add i32 2, [[TMP16]]
; CHECK-NEXT:    [[COLUMN2:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST3:%.*]] = icmp ult i32 [[COLUMN2]], 8
; CHECK-NEXT:    [[TMP17:%.*]] = and i32 [[ROW1]], 7
; CHECK-NEXT:    [[TMP18:%.*]] = and i32 [[COLUMN2]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP4:%.*]] = lshr i32 [[TMP18]], 1
; CHECK-NEXT:    [[TMP116:%.*]] = shl i32 [[TMP17]], 2
; CHECK-NEXT:    [[NV_LANE5:%.*]] = add i32 [[TMP116]], [[THREAD_ID_IN_GROUP4]]
; CHECK-NEXT:    [[TMP20:%.*]] = and i32 [[COLUMN2]], 1
; CHECK-NEXT:    [[TMP21:%.*]] = lshr i32 [[ROW1]], 3
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[TMP21]], 1
; CHECK-NEXT:    [[TMP37:%.*]] = add i32 [[TMP22]], [[TMP20]]
; CHECK-NEXT:    [[BASE_IDX6:%.*]] = and i32 [[TMP37]], -2
; CHECK-NEXT:    [[TMP38:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX6]]
; CHECK-NEXT:    [[TMP118:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX6]]
; CHECK-NEXT:    [[TMP40:%.*]] = add i32 [[BASE_IDX6]], 1
; CHECK-NEXT:    [[TMP41:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = add i32 [[BASE_IDX6]], 1
; CHECK-NEXT:    [[TMP43:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP42]]
; CHECK-NEXT:    [[TMP119:%.*]] = bitcast float [[TMP38]] to i32
; CHECK-NEXT:    [[TMP120:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP0_FIRST7:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP120]], i32 [[TMP119]])
; CHECK-NEXT:    [[TMP46:%.*]] = bitcast i32 [[CTMP0_FIRST7]] to float
; CHECK-NEXT:    [[TMP47:%.*]] = bitcast float [[TMP118]] to i32
; CHECK-NEXT:    [[TMP141:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP0_SECOND8:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP141]], i32 [[TMP47]])
; CHECK-NEXT:    [[TMP142:%.*]] = bitcast i32 [[CTMP0_SECOND8]] to float
; CHECK-NEXT:    [[TMP143:%.*]] = bitcast float [[TMP41]] to i32
; CHECK-NEXT:    [[TMP51:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP1_FIRST9:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP51]], i32 [[TMP143]])
; CHECK-NEXT:    [[TMP52:%.*]] = bitcast i32 [[CTMP1_FIRST9]] to float
; CHECK-NEXT:    [[TMP53:%.*]] = bitcast float [[TMP43]] to i32
; CHECK-NEXT:    [[TMP144:%.*]] = shl i32 [[NV_LANE5]], 2
; CHECK-NEXT:    [[CTMP1_SECOND10:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP144]], i32 [[TMP53]])
; CHECK-NEXT:    [[TMP55:%.*]] = bitcast i32 [[CTMP1_SECOND10]] to float
; CHECK-NEXT:    [[TMP56:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD11:%.*]] = trunc i32 [[TMP56]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST12:%.*]] = select i1 [[LANE_IS_ODD11]], float [[TMP52]], float [[TMP46]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND13:%.*]] = select i1 [[LANE_IS_ODD11]], float [[TMP55]], float [[TMP142]]
; CHECK-NEXT:    [[TMP65:%.*]] = select i1 [[IS_IN_FIRST3]], float [[CFRAG_VALUE_FIRST12]], float [[CFRAG_VALUE_SECOND13]]
; CHECK-NEXT:    [[TMP66:%.*]] = insertelement <8 x float> [[TMP34]], float [[TMP65]], i64 1
; CHECK-NEXT:    [[TMP30:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW7:%.*]] = add i32 4, [[TMP30]]
; CHECK-NEXT:    [[COLUMN8:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST9:%.*]] = icmp ult i32 [[COLUMN8]], 8
; CHECK-NEXT:    [[TMP31:%.*]] = and i32 [[ROW7]], 7
; CHECK-NEXT:    [[TMP32:%.*]] = and i32 [[COLUMN8]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP10:%.*]] = lshr i32 [[TMP32]], 1
; CHECK-NEXT:    [[TMP61:%.*]] = shl i32 [[TMP31]], 2
; CHECK-NEXT:    [[NV_LANE19:%.*]] = add i32 [[TMP61]], [[THREAD_ID_IN_GROUP10]]
; CHECK-NEXT:    [[TMP39:%.*]] = and i32 [[COLUMN8]], 1
; CHECK-NEXT:    [[TMP35:%.*]] = lshr i32 [[ROW7]], 3
; CHECK-NEXT:    [[TMP36:%.*]] = shl i32 [[TMP35]], 1
; CHECK-NEXT:    [[TMP146:%.*]] = add i32 [[TMP36]], [[TMP39]]
; CHECK-NEXT:    [[BASE_IDX20:%.*]] = and i32 [[TMP146]], -2
; CHECK-NEXT:    [[TMP147:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX20]]
; CHECK-NEXT:    [[TMP148:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX20]]
; CHECK-NEXT:    [[TMP68:%.*]] = add i32 [[BASE_IDX20]], 1
; CHECK-NEXT:    [[TMP69:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP68]]
; CHECK-NEXT:    [[TMP70:%.*]] = add i32 [[BASE_IDX20]], 1
; CHECK-NEXT:    [[TMP71:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP70]]
; CHECK-NEXT:    [[TMP169:%.*]] = bitcast float [[TMP147]] to i32
; CHECK-NEXT:    [[TMP170:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP0_FIRST21:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP170]], i32 [[TMP169]])
; CHECK-NEXT:    [[TMP171:%.*]] = bitcast i32 [[CTMP0_FIRST21]] to float
; CHECK-NEXT:    [[TMP75:%.*]] = bitcast float [[TMP148]] to i32
; CHECK-NEXT:    [[TMP172:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP0_SECOND22:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP172]], i32 [[TMP75]])
; CHECK-NEXT:    [[TMP174:%.*]] = bitcast i32 [[CTMP0_SECOND22]] to float
; CHECK-NEXT:    [[TMP175:%.*]] = bitcast float [[TMP69]] to i32
; CHECK-NEXT:    [[TMP79:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP1_FIRST23:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP79]], i32 [[TMP175]])
; CHECK-NEXT:    [[TMP176:%.*]] = bitcast i32 [[CTMP1_FIRST23]] to float
; CHECK-NEXT:    [[TMP81:%.*]] = bitcast float [[TMP71]] to i32
; CHECK-NEXT:    [[TMP82:%.*]] = shl i32 [[NV_LANE19]], 2
; CHECK-NEXT:    [[CTMP1_SECOND24:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP82]], i32 [[TMP81]])
; CHECK-NEXT:    [[TMP83:%.*]] = bitcast i32 [[CTMP1_SECOND24]] to float
; CHECK-NEXT:    [[TMP84:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD25:%.*]] = trunc i32 [[TMP84]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST26:%.*]] = select i1 [[LANE_IS_ODD25]], float [[TMP176]], float [[TMP171]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND27:%.*]] = select i1 [[LANE_IS_ODD25]], float [[TMP83]], float [[TMP174]]
; CHECK-NEXT:    [[TMP97:%.*]] = select i1 [[IS_IN_FIRST9]], float [[CFRAG_VALUE_FIRST26]], float [[CFRAG_VALUE_SECOND27]]
; CHECK-NEXT:    [[TMP98:%.*]] = insertelement <8 x float> [[TMP66]], float [[TMP97]], i64 2
; CHECK-NEXT:    [[TMP44:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW13:%.*]] = add i32 6, [[TMP44]]
; CHECK-NEXT:    [[COLUMN14:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST15:%.*]] = icmp ult i32 [[COLUMN14]], 8
; CHECK-NEXT:    [[TMP45:%.*]] = and i32 [[ROW13]], 7
; CHECK-NEXT:    [[TMP54:%.*]] = and i32 [[COLUMN14]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP16:%.*]] = lshr i32 [[TMP54]], 1
; CHECK-NEXT:    [[TMP89:%.*]] = shl i32 [[TMP45]], 2
; CHECK-NEXT:    [[NV_LANE33:%.*]] = add i32 [[TMP89]], [[THREAD_ID_IN_GROUP16]]
; CHECK-NEXT:    [[TMP48:%.*]] = and i32 [[COLUMN14]], 1
; CHECK-NEXT:    [[TMP49:%.*]] = lshr i32 [[ROW13]], 3
; CHECK-NEXT:    [[TMP50:%.*]] = shl i32 [[TMP49]], 1
; CHECK-NEXT:    [[TMP93:%.*]] = add i32 [[TMP50]], [[TMP48]]
; CHECK-NEXT:    [[BASE_IDX34:%.*]] = and i32 [[TMP93]], -2
; CHECK-NEXT:    [[TMP94:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX34]]
; CHECK-NEXT:    [[TMP95:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX34]]
; CHECK-NEXT:    [[TMP96:%.*]] = add i32 [[BASE_IDX34]], 1
; CHECK-NEXT:    [[TMP197:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP96]]
; CHECK-NEXT:    [[TMP198:%.*]] = add i32 [[BASE_IDX34]], 1
; CHECK-NEXT:    [[TMP99:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP198]]
; CHECK-NEXT:    [[TMP100:%.*]] = bitcast float [[TMP94]] to i32
; CHECK-NEXT:    [[TMP199:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP0_FIRST35:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP199]], i32 [[TMP100]])
; CHECK-NEXT:    [[TMP200:%.*]] = bitcast i32 [[CTMP0_FIRST35]] to float
; CHECK-NEXT:    [[TMP103:%.*]] = bitcast float [[TMP95]] to i32
; CHECK-NEXT:    [[TMP202:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP0_SECOND36:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP202]], i32 [[TMP103]])
; CHECK-NEXT:    [[TMP203:%.*]] = bitcast i32 [[CTMP0_SECOND36]] to float
; CHECK-NEXT:    [[TMP204:%.*]] = bitcast float [[TMP197]] to i32
; CHECK-NEXT:    [[TMP107:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP1_FIRST37:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP107]], i32 [[TMP204]])
; CHECK-NEXT:    [[TMP108:%.*]] = bitcast i32 [[CTMP1_FIRST37]] to float
; CHECK-NEXT:    [[TMP227:%.*]] = bitcast float [[TMP99]] to i32
; CHECK-NEXT:    [[TMP110:%.*]] = shl i32 [[NV_LANE33]], 2
; CHECK-NEXT:    [[CTMP1_SECOND38:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP110]], i32 [[TMP227]])
; CHECK-NEXT:    [[TMP111:%.*]] = bitcast i32 [[CTMP1_SECOND38]] to float
; CHECK-NEXT:    [[TMP112:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD39:%.*]] = trunc i32 [[TMP112]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST40:%.*]] = select i1 [[LANE_IS_ODD39]], float [[TMP108]], float [[TMP200]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND41:%.*]] = select i1 [[LANE_IS_ODD39]], float [[TMP111]], float [[TMP203]]
; CHECK-NEXT:    [[TMP129:%.*]] = select i1 [[IS_IN_FIRST15]], float [[CFRAG_VALUE_FIRST40]], float [[CFRAG_VALUE_SECOND41]]
; CHECK-NEXT:    [[TMP222:%.*]] = insertelement <8 x float> [[TMP98]], float [[TMP129]], i64 3
; CHECK-NEXT:    [[TMP67:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW19:%.*]] = add i32 8, [[TMP67]]
; CHECK-NEXT:    [[COLUMN20:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST21:%.*]] = icmp ult i32 [[COLUMN20]], 8
; CHECK-NEXT:    [[TMP59:%.*]] = and i32 [[ROW19]], 7
; CHECK-NEXT:    [[TMP62:%.*]] = and i32 [[COLUMN20]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP22:%.*]] = lshr i32 [[TMP62]], 1
; CHECK-NEXT:    [[TMP117:%.*]] = shl i32 [[TMP59]], 2
; CHECK-NEXT:    [[NV_LANE47:%.*]] = add i32 [[TMP117]], [[THREAD_ID_IN_GROUP22]]
; CHECK-NEXT:    [[TMP80:%.*]] = and i32 [[COLUMN20]], 1
; CHECK-NEXT:    [[TMP63:%.*]] = lshr i32 [[ROW19]], 3
; CHECK-NEXT:    [[TMP64:%.*]] = shl i32 [[TMP63]], 1
; CHECK-NEXT:    [[TMP121:%.*]] = add i32 [[TMP64]], [[TMP80]]
; CHECK-NEXT:    [[BASE_IDX48:%.*]] = and i32 [[TMP121]], -2
; CHECK-NEXT:    [[TMP122:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX48]]
; CHECK-NEXT:    [[TMP123:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX48]]
; CHECK-NEXT:    [[TMP124:%.*]] = add i32 [[BASE_IDX48]], 1
; CHECK-NEXT:    [[TMP125:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP124]]
; CHECK-NEXT:    [[TMP126:%.*]] = add i32 [[BASE_IDX48]], 1
; CHECK-NEXT:    [[TMP127:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP126]]
; CHECK-NEXT:    [[TMP128:%.*]] = bitcast float [[TMP122]] to i32
; CHECK-NEXT:    [[TMP228:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP0_FIRST49:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP228]], i32 [[TMP128]])
; CHECK-NEXT:    [[TMP130:%.*]] = bitcast i32 [[CTMP0_FIRST49]] to float
; CHECK-NEXT:    [[TMP131:%.*]] = bitcast float [[TMP123]] to i32
; CHECK-NEXT:    [[TMP132:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP0_SECOND50:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP132]], i32 [[TMP131]])
; CHECK-NEXT:    [[TMP133:%.*]] = bitcast i32 [[CTMP0_SECOND50]] to float
; CHECK-NEXT:    [[TMP134:%.*]] = bitcast float [[TMP125]] to i32
; CHECK-NEXT:    [[TMP135:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP1_FIRST51:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP135]], i32 [[TMP134]])
; CHECK-NEXT:    [[TMP136:%.*]] = bitcast i32 [[CTMP1_FIRST51]] to float
; CHECK-NEXT:    [[TMP137:%.*]] = bitcast float [[TMP127]] to i32
; CHECK-NEXT:    [[TMP138:%.*]] = shl i32 [[NV_LANE47]], 2
; CHECK-NEXT:    [[CTMP1_SECOND52:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP138]], i32 [[TMP137]])
; CHECK-NEXT:    [[TMP139:%.*]] = bitcast i32 [[CTMP1_SECOND52]] to float
; CHECK-NEXT:    [[TMP140:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD53:%.*]] = trunc i32 [[TMP140]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST54:%.*]] = select i1 [[LANE_IS_ODD53]], float [[TMP136]], float [[TMP130]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND55:%.*]] = select i1 [[LANE_IS_ODD53]], float [[TMP139]], float [[TMP133]]
; CHECK-NEXT:    [[TMP161:%.*]] = select i1 [[IS_IN_FIRST21]], float [[CFRAG_VALUE_FIRST54]], float [[CFRAG_VALUE_SECOND55]]
; CHECK-NEXT:    [[TMP162:%.*]] = insertelement <8 x float> [[TMP222]], float [[TMP161]], i64 4
; CHECK-NEXT:    [[TMP72:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW25:%.*]] = add i32 10, [[TMP72]]
; CHECK-NEXT:    [[COLUMN26:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST27:%.*]] = icmp ult i32 [[COLUMN26]], 8
; CHECK-NEXT:    [[TMP73:%.*]] = and i32 [[ROW25]], 7
; CHECK-NEXT:    [[TMP74:%.*]] = and i32 [[COLUMN26]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP28:%.*]] = lshr i32 [[TMP74]], 1
; CHECK-NEXT:    [[TMP145:%.*]] = shl i32 [[TMP73]], 2
; CHECK-NEXT:    [[NV_LANE61:%.*]] = add i32 [[TMP145]], [[THREAD_ID_IN_GROUP28]]
; CHECK-NEXT:    [[TMP76:%.*]] = and i32 [[COLUMN26]], 1
; CHECK-NEXT:    [[TMP77:%.*]] = lshr i32 [[ROW25]], 3
; CHECK-NEXT:    [[TMP78:%.*]] = shl i32 [[TMP77]], 1
; CHECK-NEXT:    [[TMP149:%.*]] = add i32 [[TMP78]], [[TMP76]]
; CHECK-NEXT:    [[BASE_IDX62:%.*]] = and i32 [[TMP149]], -2
; CHECK-NEXT:    [[TMP150:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX62]]
; CHECK-NEXT:    [[TMP151:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX62]]
; CHECK-NEXT:    [[TMP152:%.*]] = add i32 [[BASE_IDX62]], 1
; CHECK-NEXT:    [[TMP229:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP152]]
; CHECK-NEXT:    [[TMP154:%.*]] = add i32 [[BASE_IDX62]], 1
; CHECK-NEXT:    [[TMP155:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP154]]
; CHECK-NEXT:    [[TMP156:%.*]] = bitcast float [[TMP150]] to i32
; CHECK-NEXT:    [[TMP157:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP0_FIRST63:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP157]], i32 [[TMP156]])
; CHECK-NEXT:    [[TMP158:%.*]] = bitcast i32 [[CTMP0_FIRST63]] to float
; CHECK-NEXT:    [[TMP159:%.*]] = bitcast float [[TMP151]] to i32
; CHECK-NEXT:    [[TMP160:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP0_SECOND64:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP160]], i32 [[TMP159]])
; CHECK-NEXT:    [[TMP230:%.*]] = bitcast i32 [[CTMP0_SECOND64]] to float
; CHECK-NEXT:    [[TMP231:%.*]] = bitcast float [[TMP229]] to i32
; CHECK-NEXT:    [[TMP163:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP1_FIRST65:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP163]], i32 [[TMP231]])
; CHECK-NEXT:    [[TMP164:%.*]] = bitcast i32 [[CTMP1_FIRST65]] to float
; CHECK-NEXT:    [[TMP165:%.*]] = bitcast float [[TMP155]] to i32
; CHECK-NEXT:    [[TMP166:%.*]] = shl i32 [[NV_LANE61]], 2
; CHECK-NEXT:    [[CTMP1_SECOND66:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP166]], i32 [[TMP165]])
; CHECK-NEXT:    [[TMP167:%.*]] = bitcast i32 [[CTMP1_SECOND66]] to float
; CHECK-NEXT:    [[TMP168:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD67:%.*]] = trunc i32 [[TMP168]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST68:%.*]] = select i1 [[LANE_IS_ODD67]], float [[TMP164]], float [[TMP158]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND69:%.*]] = select i1 [[LANE_IS_ODD67]], float [[TMP167]], float [[TMP230]]
; CHECK-NEXT:    [[TMP193:%.*]] = select i1 [[IS_IN_FIRST27]], float [[CFRAG_VALUE_FIRST68]], float [[CFRAG_VALUE_SECOND69]]
; CHECK-NEXT:    [[TMP194:%.*]] = insertelement <8 x float> [[TMP162]], float [[TMP193]], i64 5
; CHECK-NEXT:    [[TMP86:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW31:%.*]] = add i32 12, [[TMP86]]
; CHECK-NEXT:    [[COLUMN32:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST33:%.*]] = icmp ult i32 [[COLUMN32]], 8
; CHECK-NEXT:    [[TMP87:%.*]] = and i32 [[ROW31]], 7
; CHECK-NEXT:    [[TMP88:%.*]] = and i32 [[COLUMN32]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP34:%.*]] = lshr i32 [[TMP88]], 1
; CHECK-NEXT:    [[TMP173:%.*]] = shl i32 [[TMP87]], 2
; CHECK-NEXT:    [[NV_LANE75:%.*]] = add i32 [[TMP173]], [[THREAD_ID_IN_GROUP34]]
; CHECK-NEXT:    [[TMP90:%.*]] = and i32 [[COLUMN32]], 1
; CHECK-NEXT:    [[TMP91:%.*]] = lshr i32 [[ROW31]], 3
; CHECK-NEXT:    [[TMP92:%.*]] = shl i32 [[TMP91]], 1
; CHECK-NEXT:    [[TMP177:%.*]] = add i32 [[TMP92]], [[TMP90]]
; CHECK-NEXT:    [[BASE_IDX76:%.*]] = and i32 [[TMP177]], -2
; CHECK-NEXT:    [[TMP178:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX76]]
; CHECK-NEXT:    [[TMP179:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX76]]
; CHECK-NEXT:    [[TMP180:%.*]] = add i32 [[BASE_IDX76]], 1
; CHECK-NEXT:    [[TMP181:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP180]]
; CHECK-NEXT:    [[TMP182:%.*]] = add i32 [[BASE_IDX76]], 1
; CHECK-NEXT:    [[TMP183:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP182]]
; CHECK-NEXT:    [[TMP184:%.*]] = bitcast float [[TMP178]] to i32
; CHECK-NEXT:    [[TMP185:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP0_FIRST77:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP185]], i32 [[TMP184]])
; CHECK-NEXT:    [[TMP186:%.*]] = bitcast i32 [[CTMP0_FIRST77]] to float
; CHECK-NEXT:    [[TMP187:%.*]] = bitcast float [[TMP179]] to i32
; CHECK-NEXT:    [[TMP188:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP0_SECOND78:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP188]], i32 [[TMP187]])
; CHECK-NEXT:    [[TMP189:%.*]] = bitcast i32 [[CTMP0_SECOND78]] to float
; CHECK-NEXT:    [[TMP190:%.*]] = bitcast float [[TMP181]] to i32
; CHECK-NEXT:    [[TMP191:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP1_FIRST79:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP191]], i32 [[TMP190]])
; CHECK-NEXT:    [[TMP192:%.*]] = bitcast i32 [[CTMP1_FIRST79]] to float
; CHECK-NEXT:    [[TMP232:%.*]] = bitcast float [[TMP183]] to i32
; CHECK-NEXT:    [[TMP233:%.*]] = shl i32 [[NV_LANE75]], 2
; CHECK-NEXT:    [[CTMP1_SECOND80:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP233]], i32 [[TMP232]])
; CHECK-NEXT:    [[TMP195:%.*]] = bitcast i32 [[CTMP1_SECOND80]] to float
; CHECK-NEXT:    [[TMP196:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD81:%.*]] = trunc i32 [[TMP196]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST82:%.*]] = select i1 [[LANE_IS_ODD81]], float [[TMP192]], float [[TMP186]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND83:%.*]] = select i1 [[LANE_IS_ODD81]], float [[TMP195]], float [[TMP189]]
; CHECK-NEXT:    [[TMP225:%.*]] = select i1 [[IS_IN_FIRST33]], float [[CFRAG_VALUE_FIRST82]], float [[CFRAG_VALUE_SECOND83]]
; CHECK-NEXT:    [[TMP226:%.*]] = insertelement <8 x float> [[TMP194]], float [[TMP225]], i64 6
; CHECK-NEXT:    [[TMP102:%.*]] = lshr i32 [[TMP1]], 4
; CHECK-NEXT:    [[ROW37:%.*]] = add i32 14, [[TMP102]]
; CHECK-NEXT:    [[COLUMN38:%.*]] = and i32 [[TMP1]], 15
; CHECK-NEXT:    [[IS_IN_FIRST39:%.*]] = icmp ult i32 [[COLUMN38]], 8
; CHECK-NEXT:    [[TMP101:%.*]] = and i32 [[ROW37]], 7
; CHECK-NEXT:    [[TMP109:%.*]] = and i32 [[COLUMN38]], 7
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP40:%.*]] = lshr i32 [[TMP109]], 1
; CHECK-NEXT:    [[TMP201:%.*]] = shl i32 [[TMP101]], 2
; CHECK-NEXT:    [[NV_LANE89:%.*]] = add i32 [[TMP201]], [[THREAD_ID_IN_GROUP40]]
; CHECK-NEXT:    [[TMP104:%.*]] = and i32 [[COLUMN38]], 1
; CHECK-NEXT:    [[TMP105:%.*]] = lshr i32 [[ROW37]], 3
; CHECK-NEXT:    [[TMP106:%.*]] = shl i32 [[TMP105]], 1
; CHECK-NEXT:    [[TMP205:%.*]] = add i32 [[TMP106]], [[TMP104]]
; CHECK-NEXT:    [[BASE_IDX90:%.*]] = and i32 [[TMP205]], -2
; CHECK-NEXT:    [[TMP206:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[BASE_IDX90]]
; CHECK-NEXT:    [[TMP207:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[BASE_IDX90]]
; CHECK-NEXT:    [[TMP208:%.*]] = add i32 [[BASE_IDX90]], 1
; CHECK-NEXT:    [[TMP209:%.*]] = extractelement <4 x float> [[NV_C0]], i32 [[TMP208]]
; CHECK-NEXT:    [[TMP210:%.*]] = add i32 [[BASE_IDX90]], 1
; CHECK-NEXT:    [[TMP211:%.*]] = extractelement <4 x float> [[NV_C1]], i32 [[TMP210]]
; CHECK-NEXT:    [[TMP212:%.*]] = bitcast float [[TMP206]] to i32
; CHECK-NEXT:    [[TMP213:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP0_FIRST91:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP213]], i32 [[TMP212]])
; CHECK-NEXT:    [[TMP214:%.*]] = bitcast i32 [[CTMP0_FIRST91]] to float
; CHECK-NEXT:    [[TMP215:%.*]] = bitcast float [[TMP207]] to i32
; CHECK-NEXT:    [[TMP216:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP0_SECOND92:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP216]], i32 [[TMP215]])
; CHECK-NEXT:    [[TMP217:%.*]] = bitcast i32 [[CTMP0_SECOND92]] to float
; CHECK-NEXT:    [[TMP218:%.*]] = bitcast float [[TMP209]] to i32
; CHECK-NEXT:    [[TMP219:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP1_FIRST93:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP219]], i32 [[TMP218]])
; CHECK-NEXT:    [[TMP220:%.*]] = bitcast i32 [[CTMP1_FIRST93]] to float
; CHECK-NEXT:    [[TMP221:%.*]] = bitcast float [[TMP211]] to i32
; CHECK-NEXT:    [[TMP234:%.*]] = shl i32 [[NV_LANE89]], 2
; CHECK-NEXT:    [[CTMP1_SECOND94:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP234]], i32 [[TMP221]])
; CHECK-NEXT:    [[TMP223:%.*]] = bitcast i32 [[CTMP1_SECOND94]] to float
; CHECK-NEXT:    [[TMP224:%.*]] = and i32 [[TMP1]], 1
; CHECK-NEXT:    [[LANE_IS_ODD95:%.*]] = trunc i32 [[TMP224]] to i1
; CHECK-NEXT:    [[CFRAG_VALUE_FIRST96:%.*]] = select i1 [[LANE_IS_ODD95]], float [[TMP220]], float [[TMP214]]
; CHECK-NEXT:    [[CFRAG_VALUE_SECOND97:%.*]] = select i1 [[LANE_IS_ODD95]], float [[TMP223]], float [[TMP217]]
; CHECK-NEXT:    [[TMP257:%.*]] = select i1 [[IS_IN_FIRST39]], float [[CFRAG_VALUE_FIRST96]], float [[CFRAG_VALUE_SECOND97]]
; CHECK-NEXT:    [[TMP153:%.*]] = insertelement <8 x float> [[TMP226]], float [[TMP257]], i64 7
; CHECK-NEXT:    store <8 x float> [[TMP153]], ptr [[AMD_C]], align 32
; CHECK-NEXT:    ret void
;
  %converted_c = call <8 x float> @llvm.zluda.cmatrix.concatenate.amd16x16.nv16x8.v8f32.v4f32(<4 x float> %nv_c0, <4 x float> %nv_c1)
  store <8 x float> %converted_c, ptr %amd_c

  ret void
}

define void @dmatrix_trunc(ptr %amd_d, <8 x float> %nv_d) {
; CHECK-LABEL: define void @dmatrix_trunc(
; CHECK-SAME: ptr [[AMD_D:%.*]], <8 x float> [[NV_D:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[GROUP_ID:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP5:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW:%.*]] = add i32 [[GROUP_ID]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = shl i32 [[TMP5]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP6]], 0
; CHECK-NEXT:    [[ELEMENT_IDX:%.*]] = lshr i32 [[ROW]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[ROW]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = and i32 [[TMP3]], 31
; CHECK-NEXT:    [[TMP8:%.*]] = add i32 [[TMP7]], [[TMP4]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST:%.*]] = and i32 [[ELEMENT_IDX]], -4
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST]]
; CHECK-NEXT:    [[TMP25:%.*]] = bitcast float [[TMP24]] to i32
; CHECK-NEXT:    [[TMP26:%.*]] = shl i32 [[TMP8]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP26]], i32 [[TMP25]])
; CHECK-NEXT:    [[TMP47:%.*]] = bitcast i32 [[D_TMP0_FIRST]] to float
; CHECK-NEXT:    [[TMP48:%.*]] = add i32 [[BASE_VGPR_FIRST]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP48]]
; CHECK-NEXT:    [[TMP27:%.*]] = bitcast float [[TMP10]] to i32
; CHECK-NEXT:    [[TMP12:%.*]] = shl i32 [[TMP8]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP12]], i32 [[TMP27]])
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast i32 [[D_TMP1_FIRST]] to float
; CHECK-NEXT:    [[TMP14:%.*]] = add i32 [[BASE_VGPR_FIRST]], 2
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast float [[TMP15]] to i32
; CHECK-NEXT:    [[TMP49:%.*]] = shl i32 [[TMP8]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP49]], i32 [[TMP16]])
; CHECK-NEXT:    [[TMP18:%.*]] = bitcast i32 [[D_TMP2_FIRST]] to float
; CHECK-NEXT:    [[TMP51:%.*]] = add i32 [[BASE_VGPR_FIRST]], 3
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP51]]
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast float [[TMP20]] to i32
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[TMP8]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP22]], i32 [[TMP21]])
; CHECK-NEXT:    [[TMP23:%.*]] = bitcast i32 [[D_TMP3_FIRST]] to float
; CHECK-NEXT:    [[LANE_LT_8:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_16:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_24:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST:%.*]] = select i1 [[LANE_LT_24]], float [[TMP18]], float [[TMP23]]
; CHECK-NEXT:    [[SELECT_123_FIRST:%.*]] = select i1 [[LANE_LT_16]], float [[TMP13]], float [[SELECT_23_FIRST]]
; CHECK-NEXT:    [[TMP28:%.*]] = select i1 [[LANE_LT_8]], float [[TMP47]], float [[SELECT_123_FIRST]]
; CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x float> poison, float [[TMP28]], i64 0
; CHECK-NEXT:    [[GROUP_ID1:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP39:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW3:%.*]] = add i32 [[GROUP_ID1]], 0
; CHECK-NEXT:    [[TMP40:%.*]] = shl i32 [[TMP39]], 1
; CHECK-NEXT:    [[TMP38:%.*]] = add i32 [[TMP40]], 1
; CHECK-NEXT:    [[ELEMENT_IDX5:%.*]] = lshr i32 [[ROW3]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = shl i32 [[ROW3]], 4
; CHECK-NEXT:    [[TMP41:%.*]] = and i32 [[TMP11]], 31
; CHECK-NEXT:    [[TMP42:%.*]] = add i32 [[TMP41]], [[TMP38]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST7:%.*]] = and i32 [[ELEMENT_IDX5]], -4
; CHECK-NEXT:    [[TMP50:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST7]]
; CHECK-NEXT:    [[TMP59:%.*]] = bitcast float [[TMP50]] to i32
; CHECK-NEXT:    [[TMP60:%.*]] = shl i32 [[TMP42]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST8:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP60]], i32 [[TMP59]])
; CHECK-NEXT:    [[TMP31:%.*]] = bitcast i32 [[D_TMP0_FIRST8]] to float
; CHECK-NEXT:    [[TMP32:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 1
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP32]]
; CHECK-NEXT:    [[TMP34:%.*]] = bitcast float [[TMP33]] to i32
; CHECK-NEXT:    [[TMP35:%.*]] = shl i32 [[TMP42]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST9:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP35]], i32 [[TMP34]])
; CHECK-NEXT:    [[TMP36:%.*]] = bitcast i32 [[D_TMP1_FIRST9]] to float
; CHECK-NEXT:    [[TMP37:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 2
; CHECK-NEXT:    [[TMP70:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP37]]
; CHECK-NEXT:    [[TMP92:%.*]] = bitcast float [[TMP70]] to i32
; CHECK-NEXT:    [[TMP93:%.*]] = shl i32 [[TMP42]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST10:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP93]], i32 [[TMP92]])
; CHECK-NEXT:    [[TMP71:%.*]] = bitcast i32 [[D_TMP2_FIRST10]] to float
; CHECK-NEXT:    [[TMP97:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 3
; CHECK-NEXT:    [[TMP43:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP97]]
; CHECK-NEXT:    [[TMP44:%.*]] = bitcast float [[TMP43]] to i32
; CHECK-NEXT:    [[TMP45:%.*]] = shl i32 [[TMP42]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST11:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP45]], i32 [[TMP44]])
; CHECK-NEXT:    [[TMP46:%.*]] = bitcast i32 [[D_TMP3_FIRST11]] to float
; CHECK-NEXT:    [[LANE_LT_812:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1613:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2414:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST15:%.*]] = select i1 [[LANE_LT_2414]], float [[TMP71]], float [[TMP46]]
; CHECK-NEXT:    [[SELECT_123_FIRST16:%.*]] = select i1 [[LANE_LT_1613]], float [[TMP36]], float [[SELECT_23_FIRST15]]
; CHECK-NEXT:    [[TMP62:%.*]] = select i1 [[LANE_LT_812]], float [[TMP31]], float [[SELECT_123_FIRST16]]
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x float> [[TMP9]], float [[TMP62]], i64 1
; CHECK-NEXT:    [[GROUP_ID8:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP73:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW10:%.*]] = add i32 [[GROUP_ID8]], 8
; CHECK-NEXT:    [[TMP74:%.*]] = shl i32 [[TMP73]], 1
; CHECK-NEXT:    [[TMP72:%.*]] = add i32 [[TMP74]], 0
; CHECK-NEXT:    [[ELEMENT_IDX12:%.*]] = lshr i32 [[ROW10]], 1
; CHECK-NEXT:    [[TMP19:%.*]] = shl i32 [[ROW10]], 4
; CHECK-NEXT:    [[TMP75:%.*]] = and i32 [[TMP19]], 31
; CHECK-NEXT:    [[TMP76:%.*]] = add i32 [[TMP75]], [[TMP72]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST24:%.*]] = and i32 [[ELEMENT_IDX12]], -4
; CHECK-NEXT:    [[TMP94:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST24]]
; CHECK-NEXT:    [[TMP52:%.*]] = bitcast float [[TMP94]] to i32
; CHECK-NEXT:    [[TMP53:%.*]] = shl i32 [[TMP76]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST25:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP53]], i32 [[TMP52]])
; CHECK-NEXT:    [[TMP54:%.*]] = bitcast i32 [[D_TMP0_FIRST25]] to float
; CHECK-NEXT:    [[TMP55:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 1
; CHECK-NEXT:    [[TMP56:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP55]]
; CHECK-NEXT:    [[TMP57:%.*]] = bitcast float [[TMP56]] to i32
; CHECK-NEXT:    [[TMP58:%.*]] = shl i32 [[TMP76]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST26:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP58]], i32 [[TMP57]])
; CHECK-NEXT:    [[TMP99:%.*]] = bitcast i32 [[D_TMP1_FIRST26]] to float
; CHECK-NEXT:    [[TMP100:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 2
; CHECK-NEXT:    [[TMP61:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP100]]
; CHECK-NEXT:    [[TMP95:%.*]] = bitcast float [[TMP61]] to i32
; CHECK-NEXT:    [[TMP63:%.*]] = shl i32 [[TMP76]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST27:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP63]], i32 [[TMP95]])
; CHECK-NEXT:    [[TMP64:%.*]] = bitcast i32 [[D_TMP2_FIRST27]] to float
; CHECK-NEXT:    [[TMP65:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 3
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP65]]
; CHECK-NEXT:    [[TMP67:%.*]] = bitcast float [[TMP66]] to i32
; CHECK-NEXT:    [[TMP68:%.*]] = shl i32 [[TMP76]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST28:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP68]], i32 [[TMP67]])
; CHECK-NEXT:    [[TMP69:%.*]] = bitcast i32 [[D_TMP3_FIRST28]] to float
; CHECK-NEXT:    [[LANE_LT_829:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1630:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2431:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST32:%.*]] = select i1 [[LANE_LT_2431]], float [[TMP64]], float [[TMP69]]
; CHECK-NEXT:    [[SELECT_123_FIRST33:%.*]] = select i1 [[LANE_LT_1630]], float [[TMP99]], float [[SELECT_23_FIRST32]]
; CHECK-NEXT:    [[TMP96:%.*]] = select i1 [[LANE_LT_829]], float [[TMP54]], float [[SELECT_123_FIRST33]]
; CHECK-NEXT:    [[TMP29:%.*]] = insertelement <4 x float> [[TMP17]], float [[TMP96]], i64 2
; CHECK-NEXT:    [[GROUP_ID15:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP107:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW17:%.*]] = add i32 [[GROUP_ID15]], 8
; CHECK-NEXT:    [[TMP108:%.*]] = shl i32 [[TMP107]], 1
; CHECK-NEXT:    [[TMP106:%.*]] = add i32 [[TMP108]], 1
; CHECK-NEXT:    [[ELEMENT_IDX19:%.*]] = lshr i32 [[ROW17]], 1
; CHECK-NEXT:    [[TMP30:%.*]] = shl i32 [[ROW17]], 4
; CHECK-NEXT:    [[TMP109:%.*]] = and i32 [[TMP30]], 31
; CHECK-NEXT:    [[TMP110:%.*]] = add i32 [[TMP109]], [[TMP106]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST41:%.*]] = and i32 [[ELEMENT_IDX19]], -4
; CHECK-NEXT:    [[TMP98:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST41]]
; CHECK-NEXT:    [[TMP101:%.*]] = bitcast float [[TMP98]] to i32
; CHECK-NEXT:    [[TMP102:%.*]] = shl i32 [[TMP110]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST42:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP102]], i32 [[TMP101]])
; CHECK-NEXT:    [[TMP77:%.*]] = bitcast i32 [[D_TMP0_FIRST42]] to float
; CHECK-NEXT:    [[TMP78:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 1
; CHECK-NEXT:    [[TMP79:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP78]]
; CHECK-NEXT:    [[TMP80:%.*]] = bitcast float [[TMP79]] to i32
; CHECK-NEXT:    [[TMP81:%.*]] = shl i32 [[TMP110]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST43:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP81]], i32 [[TMP80]])
; CHECK-NEXT:    [[TMP82:%.*]] = bitcast i32 [[D_TMP1_FIRST43]] to float
; CHECK-NEXT:    [[TMP83:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 2
; CHECK-NEXT:    [[TMP84:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP83]]
; CHECK-NEXT:    [[TMP85:%.*]] = bitcast float [[TMP84]] to i32
; CHECK-NEXT:    [[TMP86:%.*]] = shl i32 [[TMP110]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST44:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP86]], i32 [[TMP85]])
; CHECK-NEXT:    [[TMP87:%.*]] = bitcast i32 [[D_TMP2_FIRST44]] to float
; CHECK-NEXT:    [[TMP88:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 3
; CHECK-NEXT:    [[TMP89:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP88]]
; CHECK-NEXT:    [[TMP90:%.*]] = bitcast float [[TMP89]] to i32
; CHECK-NEXT:    [[TMP91:%.*]] = shl i32 [[TMP110]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST45:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP91]], i32 [[TMP90]])
; CHECK-NEXT:    [[TMP103:%.*]] = bitcast i32 [[D_TMP3_FIRST45]] to float
; CHECK-NEXT:    [[LANE_LT_846:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1647:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2448:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST49:%.*]] = select i1 [[LANE_LT_2448]], float [[TMP87]], float [[TMP103]]
; CHECK-NEXT:    [[SELECT_123_FIRST50:%.*]] = select i1 [[LANE_LT_1647]], float [[TMP82]], float [[SELECT_23_FIRST49]]
; CHECK-NEXT:    [[TMP130:%.*]] = select i1 [[LANE_LT_846]], float [[TMP77]], float [[SELECT_123_FIRST50]]
; CHECK-NEXT:    [[TMP137:%.*]] = insertelement <4 x float> [[TMP29]], float [[TMP130]], i64 3
; CHECK-NEXT:    store <4 x float> [[TMP137]], ptr [[AMD_D]], align 16
; CHECK-NEXT:    ret void
;
  %converted_d = call <4 x float> @llvm.zluda.dmatrix.trunc.nv16x8.amd16x16(<8 x float> %nv_d)
  store <4 x float> %converted_d, ptr %amd_d

  ret void
}

define void @dmatrix_split(ptr %amd_d0, ptr %amd_d1, <8 x float> %nv_d) {
; CHECK-LABEL: define void @dmatrix_split(
; CHECK-SAME: ptr [[AMD_D0:%.*]], ptr [[AMD_D1:%.*]], <8 x float> [[NV_D:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[TMP2:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP5:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW:%.*]] = add i32 [[TMP2]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = shl i32 [[TMP5]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[TMP6]], 0
; CHECK-NEXT:    [[ELEMENT_IDX:%.*]] = lshr i32 [[ROW]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[ROW]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = and i32 [[TMP3]], 31
; CHECK-NEXT:    [[AMD_LANE:%.*]] = add i32 [[TMP7]], [[TMP4]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST:%.*]] = and i32 [[ELEMENT_IDX]], -4
; CHECK-NEXT:    [[TMP24:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST]]
; CHECK-NEXT:    [[TMP25:%.*]] = bitcast float [[TMP24]] to i32
; CHECK-NEXT:    [[TMP26:%.*]] = shl i32 [[AMD_LANE]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP26]], i32 [[TMP25]])
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast i32 [[D_TMP0_FIRST]] to float
; CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[BASE_VGPR_FIRST]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP9]]
; CHECK-NEXT:    [[TMP47:%.*]] = bitcast float [[TMP10]] to i32
; CHECK-NEXT:    [[TMP12:%.*]] = shl i32 [[AMD_LANE]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP12]], i32 [[TMP47]])
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast i32 [[D_TMP1_FIRST]] to float
; CHECK-NEXT:    [[TMP14:%.*]] = add i32 [[BASE_VGPR_FIRST]], 2
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast float [[TMP15]] to i32
; CHECK-NEXT:    [[TMP17:%.*]] = shl i32 [[AMD_LANE]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP17]], i32 [[TMP16]])
; CHECK-NEXT:    [[TMP18:%.*]] = bitcast i32 [[D_TMP2_FIRST]] to float
; CHECK-NEXT:    [[TMP70:%.*]] = add i32 [[BASE_VGPR_FIRST]], 3
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP70]]
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast float [[TMP20]] to i32
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[AMD_LANE]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP22]], i32 [[TMP21]])
; CHECK-NEXT:    [[TMP23:%.*]] = bitcast i32 [[D_TMP3_FIRST]] to float
; CHECK-NEXT:    [[LANE_LT_8:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_16:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_24:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST:%.*]] = select i1 [[LANE_LT_24]], float [[TMP18]], float [[TMP23]]
; CHECK-NEXT:    [[SELECT_123_FIRST:%.*]] = select i1 [[LANE_LT_16]], float [[TMP13]], float [[SELECT_23_FIRST]]
; CHECK-NEXT:    [[TMP37:%.*]] = select i1 [[LANE_LT_8]], float [[TMP8]], float [[SELECT_123_FIRST]]
; CHECK-NEXT:    [[TMP39:%.*]] = insertelement <4 x float> poison, float [[TMP37]], i64 0
; CHECK-NEXT:    [[GROUP_ID1:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP43:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW3:%.*]] = add i32 [[GROUP_ID1]], 0
; CHECK-NEXT:    [[TMP44:%.*]] = shl i32 [[TMP43]], 1
; CHECK-NEXT:    [[TMP42:%.*]] = add i32 [[TMP44]], 1
; CHECK-NEXT:    [[ELEMENT_IDX5:%.*]] = lshr i32 [[ROW3]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = shl i32 [[ROW3]], 4
; CHECK-NEXT:    [[TMP45:%.*]] = and i32 [[TMP11]], 31
; CHECK-NEXT:    [[AMD_LANE6:%.*]] = add i32 [[TMP45]], [[TMP42]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST7:%.*]] = and i32 [[ELEMENT_IDX5]], -4
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST7]]
; CHECK-NEXT:    [[TMP29:%.*]] = bitcast float [[TMP28]] to i32
; CHECK-NEXT:    [[TMP30:%.*]] = shl i32 [[AMD_LANE6]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST8:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP30]], i32 [[TMP29]])
; CHECK-NEXT:    [[TMP31:%.*]] = bitcast i32 [[D_TMP0_FIRST8]] to float
; CHECK-NEXT:    [[TMP71:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 1
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP71]]
; CHECK-NEXT:    [[TMP72:%.*]] = bitcast float [[TMP33]] to i32
; CHECK-NEXT:    [[TMP73:%.*]] = shl i32 [[AMD_LANE6]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST9:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP73]], i32 [[TMP72]])
; CHECK-NEXT:    [[TMP93:%.*]] = bitcast i32 [[D_TMP1_FIRST9]] to float
; CHECK-NEXT:    [[TMP94:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 2
; CHECK-NEXT:    [[TMP38:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP94]]
; CHECK-NEXT:    [[TMP95:%.*]] = bitcast float [[TMP38]] to i32
; CHECK-NEXT:    [[TMP96:%.*]] = shl i32 [[AMD_LANE6]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST10:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP96]], i32 [[TMP95]])
; CHECK-NEXT:    [[TMP116:%.*]] = bitcast i32 [[D_TMP2_FIRST10]] to float
; CHECK-NEXT:    [[TMP117:%.*]] = add i32 [[BASE_VGPR_FIRST7]], 3
; CHECK-NEXT:    [[TMP139:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP117]]
; CHECK-NEXT:    [[TMP140:%.*]] = bitcast float [[TMP139]] to i32
; CHECK-NEXT:    [[TMP141:%.*]] = shl i32 [[AMD_LANE6]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST11:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP141]], i32 [[TMP140]])
; CHECK-NEXT:    [[TMP46:%.*]] = bitcast i32 [[D_TMP3_FIRST11]] to float
; CHECK-NEXT:    [[LANE_LT_812:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1613:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2414:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST15:%.*]] = select i1 [[LANE_LT_2414]], float [[TMP116]], float [[TMP46]]
; CHECK-NEXT:    [[SELECT_123_FIRST16:%.*]] = select i1 [[LANE_LT_1613]], float [[TMP93]], float [[SELECT_23_FIRST15]]
; CHECK-NEXT:    [[TMP75:%.*]] = select i1 [[LANE_LT_812]], float [[TMP31]], float [[SELECT_123_FIRST16]]
; CHECK-NEXT:    [[TMP77:%.*]] = insertelement <4 x float> [[TMP39]], float [[TMP75]], i64 1
; CHECK-NEXT:    [[GROUP_ID8:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP81:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW10:%.*]] = add i32 [[GROUP_ID8]], 8
; CHECK-NEXT:    [[TMP82:%.*]] = shl i32 [[TMP81]], 1
; CHECK-NEXT:    [[TMP80:%.*]] = add i32 [[TMP82]], 0
; CHECK-NEXT:    [[ELEMENT_IDX12:%.*]] = lshr i32 [[ROW10]], 1
; CHECK-NEXT:    [[TMP19:%.*]] = shl i32 [[ROW10]], 4
; CHECK-NEXT:    [[TMP83:%.*]] = and i32 [[TMP19]], 31
; CHECK-NEXT:    [[AMD_LANE13:%.*]] = add i32 [[TMP83]], [[TMP80]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST24:%.*]] = and i32 [[ELEMENT_IDX12]], -4
; CHECK-NEXT:    [[TMP142:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST24]]
; CHECK-NEXT:    [[TMP162:%.*]] = bitcast float [[TMP142]] to i32
; CHECK-NEXT:    [[TMP163:%.*]] = shl i32 [[AMD_LANE13]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST25:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP163]], i32 [[TMP162]])
; CHECK-NEXT:    [[TMP164:%.*]] = bitcast i32 [[D_TMP0_FIRST25]] to float
; CHECK-NEXT:    [[TMP55:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 1
; CHECK-NEXT:    [[TMP165:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP55]]
; CHECK-NEXT:    [[TMP185:%.*]] = bitcast float [[TMP165]] to i32
; CHECK-NEXT:    [[TMP186:%.*]] = shl i32 [[AMD_LANE13]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST26:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP186]], i32 [[TMP185]])
; CHECK-NEXT:    [[TMP187:%.*]] = bitcast i32 [[D_TMP1_FIRST26]] to float
; CHECK-NEXT:    [[TMP188:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 2
; CHECK-NEXT:    [[TMP189:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP188]]
; CHECK-NEXT:    [[TMP62:%.*]] = bitcast float [[TMP189]] to i32
; CHECK-NEXT:    [[TMP63:%.*]] = shl i32 [[AMD_LANE13]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST27:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP63]], i32 [[TMP62]])
; CHECK-NEXT:    [[TMP190:%.*]] = bitcast i32 [[D_TMP2_FIRST27]] to float
; CHECK-NEXT:    [[TMP65:%.*]] = add i32 [[BASE_VGPR_FIRST24]], 3
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP65]]
; CHECK-NEXT:    [[TMP67:%.*]] = bitcast float [[TMP66]] to i32
; CHECK-NEXT:    [[TMP68:%.*]] = shl i32 [[AMD_LANE13]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST28:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP68]], i32 [[TMP67]])
; CHECK-NEXT:    [[TMP69:%.*]] = bitcast i32 [[D_TMP3_FIRST28]] to float
; CHECK-NEXT:    [[LANE_LT_829:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1630:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2431:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST32:%.*]] = select i1 [[LANE_LT_2431]], float [[TMP190]], float [[TMP69]]
; CHECK-NEXT:    [[SELECT_123_FIRST33:%.*]] = select i1 [[LANE_LT_1630]], float [[TMP187]], float [[SELECT_23_FIRST32]]
; CHECK-NEXT:    [[TMP113:%.*]] = select i1 [[LANE_LT_829]], float [[TMP164]], float [[SELECT_123_FIRST33]]
; CHECK-NEXT:    [[TMP115:%.*]] = insertelement <4 x float> [[TMP77]], float [[TMP113]], i64 2
; CHECK-NEXT:    [[GROUP_ID15:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[TMP119:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW17:%.*]] = add i32 [[GROUP_ID15]], 8
; CHECK-NEXT:    [[TMP120:%.*]] = shl i32 [[TMP119]], 1
; CHECK-NEXT:    [[TMP118:%.*]] = add i32 [[TMP120]], 1
; CHECK-NEXT:    [[ELEMENT_IDX19:%.*]] = lshr i32 [[ROW17]], 1
; CHECK-NEXT:    [[TMP27:%.*]] = shl i32 [[ROW17]], 4
; CHECK-NEXT:    [[TMP121:%.*]] = and i32 [[TMP27]], 31
; CHECK-NEXT:    [[AMD_LANE20:%.*]] = add i32 [[TMP121]], [[TMP118]]
; CHECK-NEXT:    [[BASE_VGPR_FIRST41:%.*]] = and i32 [[ELEMENT_IDX19]], -4
; CHECK-NEXT:    [[TMP74:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_FIRST41]]
; CHECK-NEXT:    [[TMP191:%.*]] = bitcast float [[TMP74]] to i32
; CHECK-NEXT:    [[TMP76:%.*]] = shl i32 [[AMD_LANE20]], 2
; CHECK-NEXT:    [[D_TMP0_FIRST42:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP76]], i32 [[TMP191]])
; CHECK-NEXT:    [[TMP192:%.*]] = bitcast i32 [[D_TMP0_FIRST42]] to float
; CHECK-NEXT:    [[TMP78:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 1
; CHECK-NEXT:    [[TMP79:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP78]]
; CHECK-NEXT:    [[TMP193:%.*]] = bitcast float [[TMP79]] to i32
; CHECK-NEXT:    [[TMP194:%.*]] = shl i32 [[AMD_LANE20]], 2
; CHECK-NEXT:    [[D_TMP1_FIRST43:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP194]], i32 [[TMP193]])
; CHECK-NEXT:    [[TMP195:%.*]] = bitcast i32 [[D_TMP1_FIRST43]] to float
; CHECK-NEXT:    [[TMP196:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 2
; CHECK-NEXT:    [[TMP84:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP196]]
; CHECK-NEXT:    [[TMP85:%.*]] = bitcast float [[TMP84]] to i32
; CHECK-NEXT:    [[TMP86:%.*]] = shl i32 [[AMD_LANE20]], 2
; CHECK-NEXT:    [[D_TMP2_FIRST44:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP86]], i32 [[TMP85]])
; CHECK-NEXT:    [[TMP87:%.*]] = bitcast i32 [[D_TMP2_FIRST44]] to float
; CHECK-NEXT:    [[TMP88:%.*]] = add i32 [[BASE_VGPR_FIRST41]], 3
; CHECK-NEXT:    [[TMP89:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP88]]
; CHECK-NEXT:    [[TMP90:%.*]] = bitcast float [[TMP89]] to i32
; CHECK-NEXT:    [[TMP91:%.*]] = shl i32 [[AMD_LANE20]], 2
; CHECK-NEXT:    [[D_TMP3_FIRST45:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP91]], i32 [[TMP90]])
; CHECK-NEXT:    [[TMP92:%.*]] = bitcast i32 [[D_TMP3_FIRST45]] to float
; CHECK-NEXT:    [[LANE_LT_846:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1647:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2448:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_FIRST49:%.*]] = select i1 [[LANE_LT_2448]], float [[TMP87]], float [[TMP92]]
; CHECK-NEXT:    [[SELECT_123_FIRST50:%.*]] = select i1 [[LANE_LT_1647]], float [[TMP195]], float [[SELECT_23_FIRST49]]
; CHECK-NEXT:    [[TMP32:%.*]] = select i1 [[LANE_LT_846]], float [[TMP192]], float [[SELECT_123_FIRST50]]
; CHECK-NEXT:    [[TMP152:%.*]] = insertelement <4 x float> [[TMP115]], float [[TMP32]], i64 3
; CHECK-NEXT:    [[GROUP_ID22:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP23:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW24:%.*]] = add i32 [[GROUP_ID22]], 0
; CHECK-NEXT:    [[TMP34:%.*]] = shl i32 [[THREAD_ID_IN_GROUP23]], 1
; CHECK-NEXT:    [[COLUMN25:%.*]] = add i32 [[TMP34]], 0
; CHECK-NEXT:    [[COLUMN_SECOND:%.*]] = add i32 [[COLUMN25]], 8
; CHECK-NEXT:    [[ELEMENT_IDX26:%.*]] = lshr i32 [[ROW24]], 1
; CHECK-NEXT:    [[TMP35:%.*]] = shl i32 [[ROW24]], 4
; CHECK-NEXT:    [[TMP36:%.*]] = and i32 [[TMP35]], 31
; CHECK-NEXT:    [[AMD_LANE27:%.*]] = add i32 [[TMP36]], [[COLUMN_SECOND]]
; CHECK-NEXT:    [[BASE_VGPR_SECOND:%.*]] = and i32 [[ELEMENT_IDX26]], -4
; CHECK-NEXT:    [[TMP97:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_SECOND]]
; CHECK-NEXT:    [[TMP98:%.*]] = bitcast float [[TMP97]] to i32
; CHECK-NEXT:    [[TMP99:%.*]] = shl i32 [[AMD_LANE27]], 2
; CHECK-NEXT:    [[D_TMP0_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP99]], i32 [[TMP98]])
; CHECK-NEXT:    [[TMP100:%.*]] = bitcast i32 [[D_TMP0_SECOND]] to float
; CHECK-NEXT:    [[TMP101:%.*]] = add i32 [[BASE_VGPR_SECOND]], 1
; CHECK-NEXT:    [[TMP102:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP101]]
; CHECK-NEXT:    [[TMP103:%.*]] = bitcast float [[TMP102]] to i32
; CHECK-NEXT:    [[TMP104:%.*]] = shl i32 [[AMD_LANE27]], 2
; CHECK-NEXT:    [[D_TMP1_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP104]], i32 [[TMP103]])
; CHECK-NEXT:    [[TMP105:%.*]] = bitcast i32 [[D_TMP1_SECOND]] to float
; CHECK-NEXT:    [[TMP106:%.*]] = add i32 [[BASE_VGPR_SECOND]], 2
; CHECK-NEXT:    [[TMP107:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP106]]
; CHECK-NEXT:    [[TMP108:%.*]] = bitcast float [[TMP107]] to i32
; CHECK-NEXT:    [[TMP109:%.*]] = shl i32 [[AMD_LANE27]], 2
; CHECK-NEXT:    [[D_TMP2_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP109]], i32 [[TMP108]])
; CHECK-NEXT:    [[TMP110:%.*]] = bitcast i32 [[D_TMP2_SECOND]] to float
; CHECK-NEXT:    [[TMP111:%.*]] = add i32 [[BASE_VGPR_SECOND]], 3
; CHECK-NEXT:    [[TMP112:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP111]]
; CHECK-NEXT:    [[TMP197:%.*]] = bitcast float [[TMP112]] to i32
; CHECK-NEXT:    [[TMP114:%.*]] = shl i32 [[AMD_LANE27]], 2
; CHECK-NEXT:    [[D_TMP3_SECOND:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP114]], i32 [[TMP197]])
; CHECK-NEXT:    [[TMP198:%.*]] = bitcast i32 [[D_TMP3_SECOND]] to float
; CHECK-NEXT:    [[LANE_LT_858:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1659:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2460:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_SECOND:%.*]] = select i1 [[LANE_LT_2460]], float [[TMP110]], float [[TMP198]]
; CHECK-NEXT:    [[SELECT_123_SECOND:%.*]] = select i1 [[LANE_LT_1659]], float [[TMP105]], float [[SELECT_23_SECOND]]
; CHECK-NEXT:    [[TMP40:%.*]] = select i1 [[LANE_LT_858]], float [[TMP100]], float [[SELECT_123_SECOND]]
; CHECK-NEXT:    [[TMP41:%.*]] = insertelement <4 x float> poison, float [[TMP40]], i64 0
; CHECK-NEXT:    [[GROUP_ID28:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP29:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW30:%.*]] = add i32 [[GROUP_ID28]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = shl i32 [[THREAD_ID_IN_GROUP29]], 1
; CHECK-NEXT:    [[COLUMN31:%.*]] = add i32 [[TMP53]], 1
; CHECK-NEXT:    [[COLUMN_SECOND32:%.*]] = add i32 [[COLUMN31]], 8
; CHECK-NEXT:    [[ELEMENT_IDX33:%.*]] = lshr i32 [[ROW30]], 1
; CHECK-NEXT:    [[TMP54:%.*]] = shl i32 [[ROW30]], 4
; CHECK-NEXT:    [[TMP61:%.*]] = and i32 [[TMP54]], 31
; CHECK-NEXT:    [[AMD_LANE34:%.*]] = add i32 [[TMP61]], [[COLUMN_SECOND32]]
; CHECK-NEXT:    [[BASE_VGPR_SECOND68:%.*]] = and i32 [[ELEMENT_IDX33]], -4
; CHECK-NEXT:    [[TMP199:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_SECOND68]]
; CHECK-NEXT:    [[TMP200:%.*]] = bitcast float [[TMP199]] to i32
; CHECK-NEXT:    [[TMP122:%.*]] = shl i32 [[AMD_LANE34]], 2
; CHECK-NEXT:    [[D_TMP0_SECOND69:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP122]], i32 [[TMP200]])
; CHECK-NEXT:    [[TMP123:%.*]] = bitcast i32 [[D_TMP0_SECOND69]] to float
; CHECK-NEXT:    [[TMP124:%.*]] = add i32 [[BASE_VGPR_SECOND68]], 1
; CHECK-NEXT:    [[TMP125:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP124]]
; CHECK-NEXT:    [[TMP126:%.*]] = bitcast float [[TMP125]] to i32
; CHECK-NEXT:    [[TMP127:%.*]] = shl i32 [[AMD_LANE34]], 2
; CHECK-NEXT:    [[D_TMP1_SECOND70:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP127]], i32 [[TMP126]])
; CHECK-NEXT:    [[TMP128:%.*]] = bitcast i32 [[D_TMP1_SECOND70]] to float
; CHECK-NEXT:    [[TMP129:%.*]] = add i32 [[BASE_VGPR_SECOND68]], 2
; CHECK-NEXT:    [[TMP130:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP129]]
; CHECK-NEXT:    [[TMP131:%.*]] = bitcast float [[TMP130]] to i32
; CHECK-NEXT:    [[TMP132:%.*]] = shl i32 [[AMD_LANE34]], 2
; CHECK-NEXT:    [[D_TMP2_SECOND71:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP132]], i32 [[TMP131]])
; CHECK-NEXT:    [[TMP133:%.*]] = bitcast i32 [[D_TMP2_SECOND71]] to float
; CHECK-NEXT:    [[TMP134:%.*]] = add i32 [[BASE_VGPR_SECOND68]], 3
; CHECK-NEXT:    [[TMP135:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP134]]
; CHECK-NEXT:    [[TMP136:%.*]] = bitcast float [[TMP135]] to i32
; CHECK-NEXT:    [[TMP137:%.*]] = shl i32 [[AMD_LANE34]], 2
; CHECK-NEXT:    [[D_TMP3_SECOND72:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP137]], i32 [[TMP136]])
; CHECK-NEXT:    [[TMP138:%.*]] = bitcast i32 [[D_TMP3_SECOND72]] to float
; CHECK-NEXT:    [[LANE_LT_873:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1674:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2475:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_SECOND76:%.*]] = select i1 [[LANE_LT_2475]], float [[TMP133]], float [[TMP138]]
; CHECK-NEXT:    [[SELECT_123_SECOND77:%.*]] = select i1 [[LANE_LT_1674]], float [[TMP128]], float [[SELECT_23_SECOND76]]
; CHECK-NEXT:    [[TMP48:%.*]] = select i1 [[LANE_LT_873]], float [[TMP123]], float [[SELECT_123_SECOND77]]
; CHECK-NEXT:    [[TMP49:%.*]] = insertelement <4 x float> [[TMP41]], float [[TMP48]], i64 1
; CHECK-NEXT:    [[GROUP_ID36:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP37:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW38:%.*]] = add i32 [[GROUP_ID36]], 8
; CHECK-NEXT:    [[TMP50:%.*]] = shl i32 [[THREAD_ID_IN_GROUP37]], 1
; CHECK-NEXT:    [[COLUMN39:%.*]] = add i32 [[TMP50]], 0
; CHECK-NEXT:    [[COLUMN_SECOND40:%.*]] = add i32 [[COLUMN39]], 8
; CHECK-NEXT:    [[ELEMENT_IDX41:%.*]] = lshr i32 [[ROW38]], 1
; CHECK-NEXT:    [[TMP51:%.*]] = shl i32 [[ROW38]], 4
; CHECK-NEXT:    [[TMP52:%.*]] = and i32 [[TMP51]], 31
; CHECK-NEXT:    [[AMD_LANE42:%.*]] = add i32 [[TMP52]], [[COLUMN_SECOND40]]
; CHECK-NEXT:    [[BASE_VGPR_SECOND86:%.*]] = and i32 [[ELEMENT_IDX41]], -4
; CHECK-NEXT:    [[TMP143:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_SECOND86]]
; CHECK-NEXT:    [[TMP144:%.*]] = bitcast float [[TMP143]] to i32
; CHECK-NEXT:    [[TMP145:%.*]] = shl i32 [[AMD_LANE42]], 2
; CHECK-NEXT:    [[D_TMP0_SECOND87:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP145]], i32 [[TMP144]])
; CHECK-NEXT:    [[TMP146:%.*]] = bitcast i32 [[D_TMP0_SECOND87]] to float
; CHECK-NEXT:    [[TMP147:%.*]] = add i32 [[BASE_VGPR_SECOND86]], 1
; CHECK-NEXT:    [[TMP148:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP147]]
; CHECK-NEXT:    [[TMP149:%.*]] = bitcast float [[TMP148]] to i32
; CHECK-NEXT:    [[TMP150:%.*]] = shl i32 [[AMD_LANE42]], 2
; CHECK-NEXT:    [[D_TMP1_SECOND88:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP150]], i32 [[TMP149]])
; CHECK-NEXT:    [[TMP151:%.*]] = bitcast i32 [[D_TMP1_SECOND88]] to float
; CHECK-NEXT:    [[TMP201:%.*]] = add i32 [[BASE_VGPR_SECOND86]], 2
; CHECK-NEXT:    [[TMP202:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP201]]
; CHECK-NEXT:    [[TMP203:%.*]] = bitcast float [[TMP202]] to i32
; CHECK-NEXT:    [[TMP204:%.*]] = shl i32 [[AMD_LANE42]], 2
; CHECK-NEXT:    [[D_TMP2_SECOND89:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP204]], i32 [[TMP203]])
; CHECK-NEXT:    [[TMP156:%.*]] = bitcast i32 [[D_TMP2_SECOND89]] to float
; CHECK-NEXT:    [[TMP157:%.*]] = add i32 [[BASE_VGPR_SECOND86]], 3
; CHECK-NEXT:    [[TMP158:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP157]]
; CHECK-NEXT:    [[TMP159:%.*]] = bitcast float [[TMP158]] to i32
; CHECK-NEXT:    [[TMP160:%.*]] = shl i32 [[AMD_LANE42]], 2
; CHECK-NEXT:    [[D_TMP3_SECOND90:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP160]], i32 [[TMP159]])
; CHECK-NEXT:    [[TMP161:%.*]] = bitcast i32 [[D_TMP3_SECOND90]] to float
; CHECK-NEXT:    [[LANE_LT_891:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_1692:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_2493:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_SECOND94:%.*]] = select i1 [[LANE_LT_2493]], float [[TMP156]], float [[TMP161]]
; CHECK-NEXT:    [[SELECT_123_SECOND95:%.*]] = select i1 [[LANE_LT_1692]], float [[TMP151]], float [[SELECT_23_SECOND94]]
; CHECK-NEXT:    [[TMP56:%.*]] = select i1 [[LANE_LT_891]], float [[TMP146]], float [[SELECT_123_SECOND95]]
; CHECK-NEXT:    [[TMP57:%.*]] = insertelement <4 x float> [[TMP49]], float [[TMP56]], i64 2
; CHECK-NEXT:    [[GROUP_ID44:%.*]] = lshr i32 [[TMP1]], 2
; CHECK-NEXT:    [[THREAD_ID_IN_GROUP45:%.*]] = and i32 [[TMP1]], 3
; CHECK-NEXT:    [[ROW46:%.*]] = add i32 [[GROUP_ID44]], 8
; CHECK-NEXT:    [[TMP58:%.*]] = shl i32 [[THREAD_ID_IN_GROUP45]], 1
; CHECK-NEXT:    [[COLUMN47:%.*]] = add i32 [[TMP58]], 1
; CHECK-NEXT:    [[COLUMN_SECOND48:%.*]] = add i32 [[COLUMN47]], 8
; CHECK-NEXT:    [[ELEMENT_IDX49:%.*]] = lshr i32 [[ROW46]], 1
; CHECK-NEXT:    [[TMP59:%.*]] = shl i32 [[ROW46]], 4
; CHECK-NEXT:    [[TMP60:%.*]] = and i32 [[TMP59]], 31
; CHECK-NEXT:    [[AMD_LANE50:%.*]] = add i32 [[TMP60]], [[COLUMN_SECOND48]]
; CHECK-NEXT:    [[BASE_VGPR_SECOND104:%.*]] = and i32 [[ELEMENT_IDX49]], -4
; CHECK-NEXT:    [[TMP166:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[BASE_VGPR_SECOND104]]
; CHECK-NEXT:    [[TMP167:%.*]] = bitcast float [[TMP166]] to i32
; CHECK-NEXT:    [[TMP168:%.*]] = shl i32 [[AMD_LANE50]], 2
; CHECK-NEXT:    [[D_TMP0_SECOND105:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP168]], i32 [[TMP167]])
; CHECK-NEXT:    [[TMP169:%.*]] = bitcast i32 [[D_TMP0_SECOND105]] to float
; CHECK-NEXT:    [[TMP170:%.*]] = add i32 [[BASE_VGPR_SECOND104]], 1
; CHECK-NEXT:    [[TMP171:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP170]]
; CHECK-NEXT:    [[TMP172:%.*]] = bitcast float [[TMP171]] to i32
; CHECK-NEXT:    [[TMP173:%.*]] = shl i32 [[AMD_LANE50]], 2
; CHECK-NEXT:    [[D_TMP1_SECOND106:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP173]], i32 [[TMP172]])
; CHECK-NEXT:    [[TMP174:%.*]] = bitcast i32 [[D_TMP1_SECOND106]] to float
; CHECK-NEXT:    [[TMP175:%.*]] = add i32 [[BASE_VGPR_SECOND104]], 2
; CHECK-NEXT:    [[TMP176:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP175]]
; CHECK-NEXT:    [[TMP177:%.*]] = bitcast float [[TMP176]] to i32
; CHECK-NEXT:    [[TMP178:%.*]] = shl i32 [[AMD_LANE50]], 2
; CHECK-NEXT:    [[D_TMP2_SECOND107:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP178]], i32 [[TMP177]])
; CHECK-NEXT:    [[TMP179:%.*]] = bitcast i32 [[D_TMP2_SECOND107]] to float
; CHECK-NEXT:    [[TMP180:%.*]] = add i32 [[BASE_VGPR_SECOND104]], 3
; CHECK-NEXT:    [[TMP181:%.*]] = extractelement <8 x float> [[NV_D]], i32 [[TMP180]]
; CHECK-NEXT:    [[TMP182:%.*]] = bitcast float [[TMP181]] to i32
; CHECK-NEXT:    [[TMP183:%.*]] = shl i32 [[AMD_LANE50]], 2
; CHECK-NEXT:    [[D_TMP3_SECOND108:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[TMP183]], i32 [[TMP182]])
; CHECK-NEXT:    [[TMP184:%.*]] = bitcast i32 [[D_TMP3_SECOND108]] to float
; CHECK-NEXT:    [[LANE_LT_8109:%.*]] = icmp ult i32 [[TMP1]], 8
; CHECK-NEXT:    [[LANE_LT_16110:%.*]] = icmp ult i32 [[TMP1]], 16
; CHECK-NEXT:    [[LANE_LT_24111:%.*]] = icmp ult i32 [[TMP1]], 24
; CHECK-NEXT:    [[SELECT_23_SECOND112:%.*]] = select i1 [[LANE_LT_24111]], float [[TMP179]], float [[TMP184]]
; CHECK-NEXT:    [[SELECT_123_SECOND113:%.*]] = select i1 [[LANE_LT_16110]], float [[TMP174]], float [[SELECT_23_SECOND112]]
; CHECK-NEXT:    [[TMP64:%.*]] = select i1 [[LANE_LT_8109]], float [[TMP169]], float [[SELECT_123_SECOND113]]
; CHECK-NEXT:    [[TMP153:%.*]] = insertelement <4 x float> [[TMP57]], float [[TMP64]], i64 3
; CHECK-NEXT:    [[TMP154:%.*]] = insertvalue { <4 x float>, <4 x float> } poison, <4 x float> [[TMP152]], 0
; CHECK-NEXT:    [[TMP155:%.*]] = insertvalue { <4 x float>, <4 x float> } [[TMP154]], <4 x float> [[TMP153]], 1
; CHECK-NEXT:    [[CONVERTED_D0:%.*]] = extractvalue { <4 x float>, <4 x float> } [[TMP155]], 0
; CHECK-NEXT:    [[CONVERTED_D1:%.*]] = extractvalue { <4 x float>, <4 x float> } [[TMP155]], 1
; CHECK-NEXT:    store <4 x float> [[CONVERTED_D0]], ptr [[AMD_D0]], align 16
; CHECK-NEXT:    store <4 x float> [[CONVERTED_D1]], ptr [[AMD_D1]], align 16
; CHECK-NEXT:    ret void
;
  %converted_d = call { <4 x float>, <4 x float> } @llvm.zluda.dmatrix.split.nv16x8.amd16x16(<8 x float> %nv_d)
  %converted_d0 = extractvalue { <4 x float>, <4 x float> } %converted_d, 0
  %converted_d1 = extractvalue { <4 x float>, <4 x float> } %converted_d, 1

  store <4 x float> %converted_d0, ptr %amd_d0
  store <4 x float> %converted_d1, ptr %amd_d1

  ret void
}
