; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 < %s | FileCheck -check-prefixes=GFX1010 %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250 %s

declare void @llvm.set.rounding(i32)

declare half @llvm.experimental.constrained.fma.f16(half, half, half, metadata, metadata)
declare <2 x half> @llvm.experimental.constrained.fma.v2f16(<2 x half>, <2 x half>, <2 x half>, metadata, metadata)
declare <3 x half> @llvm.experimental.constrained.fma.v3f16(<3 x half>, <3 x half>, <3 x half>, metadata, metadata)
declare <4 x half> @llvm.experimental.constrained.fma.v4f16(<4 x half>, <4 x half>, <4 x half>, metadata, metadata)
declare <8 x half> @llvm.experimental.constrained.fma.v8f16(<8 x half>, <8 x half>, <8 x half>, metadata, metadata)
declare bfloat @llvm.experimental.constrained.fma.bf16(bfloat, bfloat, bfloat, metadata, metadata)
declare <2 x bfloat> @llvm.experimental.constrained.fma.v2bf16(<2 x bfloat>, <2 x bfloat>, <2 x bfloat>, metadata, metadata)
declare <3 x bfloat> @llvm.experimental.constrained.fma.v3bf16(<3 x bfloat>, <3 x bfloat>, <3 x bfloat>, metadata, metadata)
declare <4 x bfloat> @llvm.experimental.constrained.fma.v4bf16(<4 x bfloat>, <4 x bfloat>, <4 x bfloat>, metadata, metadata)
declare <8 x bfloat> @llvm.experimental.constrained.fma.v8bf16(<8 x bfloat>, <8 x bfloat>, <8 x bfloat>, metadata, metadata)
declare float @llvm.experimental.constrained.fma.f32(float, float, float, metadata, metadata)
declare <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float>, <2 x float>, <2 x float>, metadata, metadata)
declare <3 x float> @llvm.experimental.constrained.fma.v3f32(<3 x float>, <3 x float>, <3 x float>, metadata, metadata)
declare <4 x float> @llvm.experimental.constrained.fma.v4f32(<4 x float>, <4 x float>, <4 x float>, metadata, metadata)
declare <8 x float> @llvm.experimental.constrained.fma.v8f32(<8 x float>, <8 x float>, <8 x float>, metadata, metadata)
declare double @llvm.experimental.constrained.fma.f64(double, double, double, metadata, metadata)
declare <2 x double> @llvm.experimental.constrained.fma.v2f64(<2 x double>, <2 x double>, <2 x double>, metadata, metadata)
declare <3 x double> @llvm.experimental.constrained.fma.v3f64(<3 x double>, <3 x double>, <3 x double>, metadata, metadata)
declare <4 x double> @llvm.experimental.constrained.fma.v4f64(<4 x double>, <4 x double>, <4 x double>, metadata, metadata)
declare <8 x double> @llvm.experimental.constrained.fma.v8f64(<8 x double>, <8 x double>, <8 x double>, metadata, metadata)

define void @v_constrained_fma_f16(half %a, half %b, half %c, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_fma_f16:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_fma_f16 v5, v0, v1, v2
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_fma_f16 v0, v0, v1, v2
; GFX1010-NEXT:    global_store_short v[3:4], v5, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_short v[3:4], v0, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_fma_f16:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_dual_mov_b32 v5, v4 :: v_dual_mov_b32 v4, v3
; GFX1250-NEXT:    v_fma_f16 v3, v0, v1, v2
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    v_fma_f16 v0, v0, v1, v2
; GFX1250-NEXT:    global_store_b16 v[4:5], v3, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b16 v[4:5], v0, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call half @llvm.experimental.constrained.fma.f16(half %a, half %b, half %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call half @llvm.experimental.constrained.fma.f16(half %a, half %b, half %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile half %r.a, ptr addrspace(1) %out
  store volatile half %r.b, ptr addrspace(1) %out
  ret void
}

define void @v_constrained_fma_v2f16(<2 x half> %a, <2 x half> %b, <2 x half> %c, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_fma_v2f16:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_pk_fma_f16 v5, v0, v1, v2
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_pk_fma_f16 v0, v0, v1, v2
; GFX1010-NEXT:    global_store_dword v[3:4], v5, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v[3:4], v0, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_fma_v2f16:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_dual_mov_b32 v5, v4 :: v_dual_mov_b32 v4, v3
; GFX1250-NEXT:    v_pk_fma_f16 v3, v0, v1, v2
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    v_pk_fma_f16 v0, v0, v1, v2
; GFX1250-NEXT:    global_store_b32 v[4:5], v3, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v[4:5], v0, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call <2 x half> @llvm.experimental.constrained.fma.v2f16(<2 x half> %a, <2 x half> %b, <2 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call <2 x half> @llvm.experimental.constrained.fma.v2f16(<2 x half> %a, <2 x half> %b, <2 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile <2 x half> %r.a, ptr addrspace(1) %out
  store volatile <2 x half> %r.b, ptr addrspace(1) %out
  ret void
}

define void @v_constrained_fma_v3f16(<3 x half> %a, <3 x half> %b, <3 x half> %c, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_fma_v3f16:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_pk_fma_f16 v8, v0, v2, v4
; GFX1010-NEXT:    v_fma_f16 v9, v1, v3, v5
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_fma_f16 v1, v1, v3, v5
; GFX1010-NEXT:    v_pk_fma_f16 v0, v0, v2, v4
; GFX1010-NEXT:    global_store_short v[6:7], v9, off offset:4
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v[6:7], v8, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_short v[6:7], v1, off offset:4
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v[6:7], v0, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_fma_v3f16:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_pk_fma_f16 v8, v0, v2, v4
; GFX1250-NEXT:    v_fma_f16 v9, v1, v3, v5
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    v_fma_f16 v1, v1, v3, v5
; GFX1250-NEXT:    v_pk_fma_f16 v0, v0, v2, v4
; GFX1250-NEXT:    global_store_b16 v[6:7], v9, off offset:4 scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v[6:7], v8, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b16 v[6:7], v1, off offset:4 scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v[6:7], v0, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call <3 x half> @llvm.experimental.constrained.fma.v3f16(<3 x half> %a, <3 x half> %b, <3 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call <3 x half> @llvm.experimental.constrained.fma.v3f16(<3 x half> %a, <3 x half> %b, <3 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile <3 x half> %r.a, ptr addrspace(1) %out
  store volatile <3 x half> %r.b, ptr addrspace(1) %out
  ret void
}

define void @v_constrained_fma_v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_fma_v4f16:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    v_lshrrev_b32_e32 v8, 16, v4
; GFX1010-NEXT:    v_lshrrev_b32_e32 v9, 16, v2
; GFX1010-NEXT:    v_lshrrev_b32_e32 v10, 16, v0
; GFX1010-NEXT:    v_lshrrev_b32_e32 v11, 16, v5
; GFX1010-NEXT:    v_lshrrev_b32_e32 v12, 16, v3
; GFX1010-NEXT:    v_lshrrev_b32_e32 v13, 16, v1
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_fmac_f16_e32 v8, v10, v9
; GFX1010-NEXT:    v_fmac_f16_e32 v5, v1, v3
; GFX1010-NEXT:    v_fmac_f16_e32 v11, v13, v12
; GFX1010-NEXT:    v_fmac_f16_e32 v4, v0, v2
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_perm_b32 v1, v11, v5, 0x5040100
; GFX1010-NEXT:    v_perm_b32 v0, v8, v4, 0x5040100
; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_fma_v4f16:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    v_dual_lshrrev_b32 v8, 16, v4 :: v_dual_lshrrev_b32 v9, 16, v2
; GFX1250-NEXT:    v_dual_lshrrev_b32 v10, 16, v0 :: v_dual_lshrrev_b32 v11, 16, v5
; GFX1250-NEXT:    v_dual_lshrrev_b32 v12, 16, v3 :: v_dual_lshrrev_b32 v13, 16, v1
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX1250-NEXT:    v_fmac_f16_e32 v8, v10, v9
; GFX1250-NEXT:    v_fmac_f16_e32 v5, v1, v3
; GFX1250-NEXT:    v_fmac_f16_e32 v11, v13, v12
; GFX1250-NEXT:    v_fmac_f16_e32 v4, v0, v2
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1250-NEXT:    v_perm_b32 v1, v11, v5, 0x5040100
; GFX1250-NEXT:    v_perm_b32 v0, v8, v4, 0x5040100
; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call <4 x half> @llvm.experimental.constrained.fma.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call <4 x half> @llvm.experimental.constrained.fma.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile <4 x half> %r.a, ptr addrspace(1) %out
  store volatile <4 x half> %r.b, ptr addrspace(1) %out
  ret void
}

; define void @v_constrained_fma_v8f16(<8 x half> %a, <8 x half> %b, <8 x half> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v8f16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v14, 16, v8
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v15, 16, v4
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v16, 16, v0
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v17, 16, v9
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v18, 16, v5
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v19, 16, v1
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v20, 16, v10
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v21, 16, v6
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v22, 16, v2
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v23, 16, v11
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v24, 16, v7
; ; GFX1010-NEXT:    v_lshrrev_b32_e32 v25, 16, v3
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f16_e32 v14, v16, v15
; ; GFX1010-NEXT:    v_fmac_f16_e32 v17, v19, v18
; ; GFX1010-NEXT:    v_fmac_f16_e32 v20, v22, v21
; ; GFX1010-NEXT:    v_fmac_f16_e32 v23, v25, v24
; ; GFX1010-NEXT:    v_fmac_f16_e32 v11, v3, v7
; ; GFX1010-NEXT:    v_fmac_f16_e32 v10, v2, v6
; ; GFX1010-NEXT:    v_fmac_f16_e32 v9, v1, v5
; ; GFX1010-NEXT:    v_fmac_f16_e32 v8, v0, v4
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_perm_b32 v3, v23, v11, 0x5040100
; ; GFX1010-NEXT:    v_perm_b32 v2, v20, v10, 0x5040100
; ; GFX1010-NEXT:    v_perm_b32 v1, v17, v9, 0x5040100
; ; GFX1010-NEXT:    v_perm_b32 v0, v14, v8, 0x5040100
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v8f16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v14, 16, v8 :: v_dual_lshrrev_b32 v17, 16, v9
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v15, 16, v4 :: v_dual_lshrrev_b32 v18, 16, v5
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v16, 16, v0 :: v_dual_lshrrev_b32 v19, 16, v1
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v20, 16, v10 :: v_dual_lshrrev_b32 v23, 16, v11
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v21, 16, v6 :: v_dual_lshrrev_b32 v24, 16, v7
; ; GFX1250-NEXT:    v_dual_lshrrev_b32 v22, 16, v2 :: v_dual_lshrrev_b32 v25, 16, v3
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fmac_f16_e32 v14, v16, v15
; ; GFX1250-NEXT:    v_fmac_f16_e32 v17, v19, v18
; ; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; ; GFX1250-NEXT:    v_fmac_f16_e32 v20, v22, v21
; ; GFX1250-NEXT:    v_fmac_f16_e32 v23, v25, v24
; ; GFX1250-NEXT:    v_fmac_f16_e32 v11, v3, v7
; ; GFX1250-NEXT:    v_fmac_f16_e32 v10, v2, v6
; ; GFX1250-NEXT:    v_fmac_f16_e32 v9, v1, v5
; ; GFX1250-NEXT:    v_fmac_f16_e32 v8, v0, v4
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    v_perm_b32 v3, v23, v11, 0x5040100
; ; GFX1250-NEXT:    v_perm_b32 v2, v20, v10, 0x5040100
; ; GFX1250-NEXT:    v_perm_b32 v1, v17, v9, 0x5040100
; ; GFX1250-NEXT:    v_perm_b32 v0, v14, v8, 0x5040100
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[0:3], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[0:3], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <8 x half> @llvm.experimental.constrained.fma.v8f16(<8 x half> %a, <8 x half> %b, <8 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <8 x half> @llvm.experimental.constrained.fma.v8f16(<8 x half> %a, <8 x half> %b, <8 x half> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <8 x half> %r.a, ptr addrspace(1) %out
;   store volatile <8 x half> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_bf16(bfloat %a, bfloat %b, bfloat %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_bf16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v2, v0, v1
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_bfe_u32 v0, v2, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v1, 0x400000, v2
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; ; GFX1010-NEXT:    v_add3_u32 v0, v0, v2, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v0, v0, v1, vcc_lo
; ; GFX1010-NEXT:    global_store_short_d16_hi v[3:4], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_short_d16_hi v[3:4], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_bf16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_mov_b32 v5, v4 :: v_dual_mov_b32 v4, v3
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v0, v0, v1, v2 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v1, v0, s0
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v0, v0, s0
; ; GFX1250-NEXT:    global_store_b16 v[4:5], v1, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b16 v[4:5], v0, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call bfloat @llvm.experimental.constrained.fma.bf16(bfloat %a, bfloat %b, bfloat %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call bfloat @llvm.experimental.constrained.fma.bf16(bfloat %a, bfloat %b, bfloat %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile bfloat %r.a, ptr addrspace(1) %out
;   store volatile bfloat %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v2bf16(<2 x bfloat> %a, <2 x bfloat> %b, <2 x bfloat> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v2bf16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_and_b32_e32 v5, 0xffff0000, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v6, 16, v1
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v7, 16, v0
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; ; GFX1010-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; ; GFX1010-NEXT:    v_fmac_f32_e32 v2, v7, v6
; ; GFX1010-NEXT:    v_fmac_f32_e32 v5, v0, v1
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_bfe_u32 v0, v2, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v6, 0x400000, v2
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; ; GFX1010-NEXT:    v_bfe_u32 v1, v5, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; ; GFX1010-NEXT:    v_add3_u32 v0, v0, v2, 0x7fff
; ; GFX1010-NEXT:    v_add3_u32 v1, v1, v5, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v0, v0, v6, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v1, v1, v7, vcc_lo
; ; GFX1010-NEXT:    v_perm_b32 v0, v1, v0, 0x7060302
; ; GFX1010-NEXT:    global_store_dword v[3:4], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dword v[3:4], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v2bf16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_mov_b32 v5, v4 :: v_dual_mov_b32 v4, v3
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v3, v0, v1, v2 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v0, v0, v1, v2 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v0, v0, v3
; ; GFX1250-NEXT:    global_store_b32 v[4:5], v0, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b32 v[4:5], v0, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <2 x bfloat> @llvm.experimental.constrained.fma.v2bf16(<2 x bfloat> %a, <2 x bfloat> %b, <2 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <2 x bfloat> @llvm.experimental.constrained.fma.v2bf16(<2 x bfloat> %a, <2 x bfloat> %b, <2 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <2 x bfloat> %r.a, ptr addrspace(1) %out
;   store volatile <2 x bfloat> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v3bf16(<3 x bfloat> %a, <3 x bfloat> %b, <3 x bfloat> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v3bf16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v9, 16, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v10, 16, v0
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; ; GFX1010-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; ; GFX1010-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; ; GFX1010-NEXT:    v_fmac_f32_e32 v8, v10, v9
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; ; GFX1010-NEXT:    v_fmac_f32_e32 v4, v0, v2
; ; GFX1010-NEXT:    v_bfe_u32 v0, v8, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v2, 0x400000, v8
; ; GFX1010-NEXT:    v_fmac_f32_e32 v5, v1, v3
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_bfe_u32 v1, v4, 16, 1
; ; GFX1010-NEXT:    v_add3_u32 v0, v0, v8, 0x7fff
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; ; GFX1010-NEXT:    v_bfe_u32 v3, v5, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v9, 0x400000, v4
; ; GFX1010-NEXT:    v_add3_u32 v1, v1, v4, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v0, v0, v2, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; ; GFX1010-NEXT:    v_add3_u32 v2, v3, v5, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v3, 0x400000, v5
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v1, v1, v9, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; ; GFX1010-NEXT:    v_perm_b32 v0, v1, v0, 0x7060302
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v2, v2, v3, vcc_lo
; ; GFX1010-NEXT:    global_store_short_d16_hi v[6:7], v2, off offset:4
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dword v[6:7], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_short_d16_hi v[6:7], v2, off offset:4
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dword v[6:7], v0, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v3bf16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v1, v1, v3, v5 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v8, v0, v2, v4 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v0, v0, v2, v4 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v2, v1, s0
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v1, v1, s0
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v0, v0, v8
; ; GFX1250-NEXT:    global_store_b16 v[6:7], v2, off offset:4 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b32 v[6:7], v0, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b16 v[6:7], v1, off offset:4 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b32 v[6:7], v0, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <3 x bfloat> @llvm.experimental.constrained.fma.v3bf16(<3 x bfloat> %a, <3 x bfloat> %b, <3 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <3 x bfloat> @llvm.experimental.constrained.fma.v3bf16(<3 x bfloat> %a, <3 x bfloat> %b, <3 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <3 x bfloat> %r.a, ptr addrspace(1) %out
;   store volatile <3 x bfloat> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v4bf16(<4 x bfloat> %a, <4 x bfloat> %b, <4 x bfloat> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v4bf16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v9, 16, v5
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v10, 16, v3
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v11, 16, v1
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; ; GFX1010-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; ; GFX1010-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; ; GFX1010-NEXT:    v_fmac_f32_e32 v9, v11, v10
; ; GFX1010-NEXT:    v_and_b32_e32 v8, 0xffff0000, v4
; ; GFX1010-NEXT:    v_and_b32_e32 v12, 0xffff0000, v2
; ; GFX1010-NEXT:    v_and_b32_e32 v13, 0xffff0000, v0
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; ; GFX1010-NEXT:    v_bfe_u32 v10, v9, 16, 1
; ; GFX1010-NEXT:    v_fmac_f32_e32 v5, v1, v3
; ; GFX1010-NEXT:    v_fmac_f32_e32 v8, v13, v12
; ; GFX1010-NEXT:    v_or_b32_e32 v1, 0x400000, v9
; ; GFX1010-NEXT:    v_fmac_f32_e32 v4, v0, v2
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_add3_u32 v0, v10, v9, 0x7fff
; ; GFX1010-NEXT:    v_bfe_u32 v2, v5, 16, 1
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; ; GFX1010-NEXT:    v_bfe_u32 v3, v4, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; ; GFX1010-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; ; GFX1010-NEXT:    v_add3_u32 v2, v2, v5, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v0, v0, v1, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; ; GFX1010-NEXT:    v_bfe_u32 v1, v8, 16, 1
; ; GFX1010-NEXT:    v_add3_u32 v3, v3, v4, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v2, v2, v9, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; ; GFX1010-NEXT:    v_add3_u32 v1, v1, v8, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v3, v3, v10, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v4, v1, v11, vcc_lo
; ; GFX1010-NEXT:    v_perm_b32 v1, v2, v0, 0x7060302
; ; GFX1010-NEXT:    v_perm_b32 v0, v4, v3, 0x7060302
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v4bf16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v8, v1, v3, v5 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v1, v1, v3, v5 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v3, v0, v2, v4 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v0, v0, v2, v4 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v1, v1, v8
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v0, v0, v3
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <4 x bfloat> @llvm.experimental.constrained.fma.v4bf16(<4 x bfloat> %a, <4 x bfloat> %b, <4 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <4 x bfloat> @llvm.experimental.constrained.fma.v4bf16(<4 x bfloat> %a, <4 x bfloat> %b, <4 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <4 x bfloat> %r.a, ptr addrspace(1) %out
;   store volatile <4 x bfloat> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v8bf16(<8 x bfloat> %a, <8 x bfloat> %b, <8 x bfloat> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v8bf16:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    v_and_b32_e32 v14, 0xffff0000, v8
; ; GFX1010-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; ; GFX1010-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; ; GFX1010-NEXT:    v_and_b32_e32 v17, 0xffff0000, v9
; ; GFX1010-NEXT:    v_and_b32_e32 v18, 0xffff0000, v5
; ; GFX1010-NEXT:    v_and_b32_e32 v19, 0xffff0000, v1
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; ; GFX1010-NEXT:    v_fmac_f32_e32 v14, v16, v15
; ; GFX1010-NEXT:    v_fmac_f32_e32 v17, v19, v18
; ; GFX1010-NEXT:    v_and_b32_e32 v15, 0xffff0000, v11
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v18, 16, v3
; ; GFX1010-NEXT:    v_fmac_f32_e32 v8, v0, v4
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v0, 16, v9
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; ; GFX1010-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; ; GFX1010-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; ; GFX1010-NEXT:    v_fmac_f32_e32 v11, v18, v16
; ; GFX1010-NEXT:    v_and_b32_e32 v5, 0xffff0000, v10
; ; GFX1010-NEXT:    v_and_b32_e32 v9, 0xffff0000, v6
; ; GFX1010-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; ; GFX1010-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; ; GFX1010-NEXT:    v_fmac_f32_e32 v15, v3, v7
; ; GFX1010-NEXT:    v_fmac_f32_e32 v0, v1, v4
; ; GFX1010-NEXT:    v_bfe_u32 v1, v11, 16, 1
; ; GFX1010-NEXT:    v_fmac_f32_e32 v5, v19, v9
; ; GFX1010-NEXT:    v_fmac_f32_e32 v10, v2, v6
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    v_bfe_u32 v3, v15, 16, 1
; ; GFX1010-NEXT:    v_add3_u32 v1, v1, v11, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v2, 0x400000, v11
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; ; GFX1010-NEXT:    v_or_b32_e32 v4, 0x400000, v15
; ; GFX1010-NEXT:    v_add3_u32 v3, v3, v15, 0x7fff
; ; GFX1010-NEXT:    v_bfe_u32 v6, v10, 16, 1
; ; GFX1010-NEXT:    v_bfe_u32 v7, v0, 16, 1
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v1, v1, v2, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; ; GFX1010-NEXT:    v_bfe_u32 v2, v5, 16, 1
; ; GFX1010-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; ; GFX1010-NEXT:    v_or_b32_e32 v11, 0x400000, v14
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v3, v3, v4, vcc_lo
; ; GFX1010-NEXT:    v_add3_u32 v4, v6, v10, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v6, 0x400000, v10
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; ; GFX1010-NEXT:    v_add3_u32 v2, v2, v5, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; ; GFX1010-NEXT:    v_perm_b32 v3, v3, v1, 0x7060302
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v4, v4, v6, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; ; GFX1010-NEXT:    v_add3_u32 v6, v7, v0, 0x7fff
; ; GFX1010-NEXT:    v_or_b32_e32 v7, 0x400000, v0
; ; GFX1010-NEXT:    v_bfe_u32 v5, v17, 16, 1
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v2, v2, v9, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; ; GFX1010-NEXT:    v_bfe_u32 v9, v8, 16, 1
; ; GFX1010-NEXT:    v_add3_u32 v5, v5, v17, 0x7fff
; ; GFX1010-NEXT:    v_perm_b32 v2, v2, v4, 0x7060302
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v0, v6, v7, vcc_lo
; ; GFX1010-NEXT:    v_or_b32_e32 v7, 0x400000, v17
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; ; GFX1010-NEXT:    v_bfe_u32 v6, v14, 16, 1
; ; GFX1010-NEXT:    v_add3_u32 v9, v9, v8, 0x7fff
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v5, v5, v7, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; ; GFX1010-NEXT:    v_add3_u32 v6, v6, v14, 0x7fff
; ; GFX1010-NEXT:    v_perm_b32 v1, v5, v0, 0x7060302
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc_lo
; ; GFX1010-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; ; GFX1010-NEXT:    v_cndmask_b32_e32 v6, v6, v11, vcc_lo
; ; GFX1010-NEXT:    v_perm_b32 v0, v6, v7, 0x7060302
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v8bf16:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v14, v3, v7, v11 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v3, v3, v7, v11 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v7, v2, v6, v10 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v2, v2, v6, v10 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v6, v1, v5, v9 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v1, v1, v5, v9 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v5, v0, v4, v8 op_sel:[1,1,1] op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_fma_mix_f32_bf16 v0, v0, v4, v8 op_sel_hi:[1,1,1]
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v3, v3, v14
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v2, v2, v7
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v1, v1, v6
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    v_cvt_pk_bf16_f32 v0, v0, v5
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[0:3], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[0:3], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <8 x bfloat> @llvm.experimental.constrained.fma.v8bf16(<8 x bfloat> %a, <8 x bfloat> %b, <8 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <8 x bfloat> @llvm.experimental.constrained.fma.v8bf16(<8 x bfloat> %a, <8 x bfloat> %b, <8 x bfloat> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <8 x bfloat> %r.a, ptr addrspace(1) %out
;   store volatile <8 x bfloat> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_f32(float %a, float %b, float %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_f32:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v2, v0, v1
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dword v[3:4], v2, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dword v[3:4], v2, off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_f32:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_mov_b32 v5, v4 :: v_dual_mov_b32 v4, v3
; ; GFX1250-NEXT:    v_fmac_f32_e32 v2, v0, v1
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b32 v[4:5], v2, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b32 v[4:5], v2, off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call float @llvm.experimental.constrained.fma.f32(float %a, float %b, float %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call float @llvm.experimental.constrained.fma.f32(float %a, float %b, float %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile float %r.a, ptr addrspace(1) %out
;   store volatile float %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v2f32:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v5, v1, v3
; ; GFX1010-NEXT:    v_fmac_f32_e32 v4, v0, v2
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[4:5], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[4:5], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v2f32:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_pk_fma_f32 v[0:1], v[0:1], v[2:3], v[4:5]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[0:1], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <2 x float> %r.a, ptr addrspace(1) %out
;   store volatile <2 x float> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v3f32(<3 x float> %a, <3 x float> %b, <3 x float> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v3f32:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v8, v2, v5
; ; GFX1010-NEXT:    v_fmac_f32_e32 v7, v1, v4
; ; GFX1010-NEXT:    v_fmac_f32_e32 v6, v0, v3
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx3 v[9:10], v[6:8], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx3 v[9:10], v[6:8], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v3f32:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_mov_b32 v11, v10 :: v_dual_mov_b32 v10, v9
; ; GFX1250-NEXT:    v_dual_fmac_f32 v8, v2, v5 :: v_dual_fmac_f32 v7, v1, v4
; ; GFX1250-NEXT:    v_fmac_f32_e32 v6, v0, v3
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b96 v[10:11], v[6:8], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b96 v[10:11], v[6:8], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <3 x float> @llvm.experimental.constrained.fma.v3f32(<3 x float> %a, <3 x float> %b, <3 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <3 x float> @llvm.experimental.constrained.fma.v3f32(<3 x float> %a, <3 x float> %b, <3 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <3 x float> %r.a, ptr addrspace(1) %out
;   store volatile <3 x float> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v4f32:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v11, v3, v7
; ; GFX1010-NEXT:    v_fmac_f32_e32 v10, v2, v6
; ; GFX1010-NEXT:    v_fmac_f32_e32 v9, v1, v5
; ; GFX1010-NEXT:    v_fmac_f32_e32 v8, v0, v4
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[8:11], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[8:11], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v4f32:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_fmac_f32 v11, v3, v7 :: v_dual_fmac_f32 v10, v2, v6
; ; GFX1250-NEXT:    v_dual_fmac_f32 v9, v1, v5 :: v_dual_fmac_f32 v8, v0, v4
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[8:11], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[8:11], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <4 x float> @llvm.experimental.constrained.fma.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <4 x float> @llvm.experimental.constrained.fma.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <4 x float> %r.a, ptr addrspace(1) %out
;   store volatile <4 x float> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v8f32(<8 x float> %a, <8 x float> %b, <8 x float> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v8f32:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fmac_f32_e32 v23, v7, v15
; ; GFX1010-NEXT:    v_fmac_f32_e32 v22, v6, v14
; ; GFX1010-NEXT:    v_fmac_f32_e32 v21, v5, v13
; ; GFX1010-NEXT:    v_fmac_f32_e32 v20, v4, v12
; ; GFX1010-NEXT:    v_fmac_f32_e32 v19, v3, v11
; ; GFX1010-NEXT:    v_fmac_f32_e32 v18, v2, v10
; ; GFX1010-NEXT:    v_fmac_f32_e32 v17, v1, v9
; ; GFX1010-NEXT:    v_fmac_f32_e32 v16, v0, v8
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[20:23], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[16:19], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[20:23], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[16:19], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v8f32:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_dual_fmac_f32 v17, v1, v9 :: v_dual_fmac_f32 v23, v7, v15
; ; GFX1250-NEXT:    v_dual_fmac_f32 v22, v6, v14 :: v_dual_fmac_f32 v21, v5, v13
; ; GFX1250-NEXT:    v_dual_fmac_f32 v20, v4, v12 :: v_dual_fmac_f32 v19, v3, v11
; ; GFX1250-NEXT:    v_dual_fmac_f32 v18, v2, v10 :: v_dual_fmac_f32 v16, v0, v8
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[16:19], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[16:19], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <8 x float> @llvm.experimental.constrained.fma.v8f32(<8 x float> %a, <8 x float> %b, <8 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <8 x float> @llvm.experimental.constrained.fma.v8f32(<8 x float> %a, <8 x float> %b, <8 x float> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <8 x float> %r.a, ptr addrspace(1) %out
;   store volatile <8 x float> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_f64(double %a, double %b, double %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_f64:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fma_f64 v[0:1], v[0:1], v[2:3], v[4:5]
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[6:7], v[0:1], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_f64:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[4:5], v[0:1], v[2:3]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[4:5], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b64 v[6:7], v[4:5], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call double @llvm.experimental.constrained.fma.f64(double %a, double %b, double %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call double @llvm.experimental.constrained.fma.f64(double %a, double %b, double %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile double %r.a, ptr addrspace(1) %out
;   store volatile double %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v2f64:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fma_f64 v[0:1], v[0:1], v[4:5], v[8:9]
; ; GFX1010-NEXT:    v_fma_f64 v[2:3], v[2:3], v[6:7], v[10:11]
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[12:13], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v2f64:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[8:9], v[0:1], v[4:5]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[10:11], v[2:3], v[6:7]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[8:11], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[12:13], v[8:11], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <2 x double> @llvm.experimental.constrained.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <2 x double> @llvm.experimental.constrained.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <2 x double> %r.a, ptr addrspace(1) %out
;   store volatile <2 x double> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v3f64(<3 x double> %a, <3 x double> %b, <3 x double> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v3f64:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fma_f64 v[4:5], v[4:5], v[10:11], v[16:17]
; ; GFX1010-NEXT:    v_fma_f64 v[0:1], v[0:1], v[6:7], v[12:13]
; ; GFX1010-NEXT:    v_fma_f64 v[2:3], v[2:3], v[8:9], v[14:15]
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[18:19], v[4:5], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[18:19], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx2 v[18:19], v[4:5], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[18:19], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v3f64:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[16:17], v[4:5], v[10:11]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[12:13], v[0:1], v[6:7]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[14:15], v[2:3], v[8:9]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b64 v[18:19], v[16:17], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[18:19], v[12:15], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b64 v[18:19], v[16:17], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[18:19], v[12:15], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <3 x double> @llvm.experimental.constrained.fma.v3f64(<3 x double> %a, <3 x double> %b, <3 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <3 x double> @llvm.experimental.constrained.fma.v3f64(<3 x double> %a, <3 x double> %b, <3 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <3 x double> %r.a, ptr addrspace(1) %out
;   store volatile <3 x double> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v4f64(<4 x double> %a, <4 x double> %b, <4 x double> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v4f64:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    v_fma_f64 v[4:5], v[4:5], v[12:13], v[20:21]
; ; GFX1010-NEXT:    v_fma_f64 v[6:7], v[6:7], v[14:15], v[22:23]
; ; GFX1010-NEXT:    v_fma_f64 v[0:1], v[0:1], v[8:9], v[16:17]
; ; GFX1010-NEXT:    v_fma_f64 v[2:3], v[2:3], v[10:11], v[18:19]
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[4:7], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[4:7], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[24:25], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v4f64:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[20:21], v[4:5], v[12:13]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[22:23], v[6:7], v[14:15]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[16:17], v[0:1], v[8:9]
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[18:19], v[2:3], v[10:11]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[16:19], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[24:25], v[16:19], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <4 x double> @llvm.experimental.constrained.fma.v4f64(<4 x double> %a, <4 x double> %b, <4 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <4 x double> @llvm.experimental.constrained.fma.v4f64(<4 x double> %a, <4 x double> %b, <4 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <4 x double> %r.a, ptr addrspace(1) %out
;   store volatile <4 x double> %r.b, ptr addrspace(1) %out
;   ret void
; }

; define void @v_constrained_fma_v8f64(<8 x double> %a, <8 x double> %b, <8 x double> %c, ptr addrspace(1) %out) #0 {
; ; GFX1010-LABEL: v_constrained_fma_v8f64:
; ; GFX1010:       ; %bb.0:
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; ; GFX1010-NEXT:    s_clause 0xa
; ; GFX1010-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:60
; ; GFX1010-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:56
; ; GFX1010-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:52
; ; GFX1010-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; ; GFX1010-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:64
; ; GFX1010-NEXT:    buffer_load_dword v37, off, s[0:3], s32 offset:24
; ; GFX1010-NEXT:    buffer_load_dword v36, off, s[0:3], s32 offset:20
; ; GFX1010-NEXT:    buffer_load_dword v39, off, s[0:3], s32 offset:48
; ; GFX1010-NEXT:    buffer_load_dword v38, off, s[0:3], s32 offset:44
; ; GFX1010-NEXT:    buffer_load_dword v49, off, s[0:3], s32 offset:40
; ; GFX1010-NEXT:    buffer_load_dword v48, off, s[0:3], s32 offset:36
; ; GFX1010-NEXT:    s_round_mode 0xf
; ; GFX1010-NEXT:    s_waitcnt vmcnt(4)
; ; GFX1010-NEXT:    v_fma_f64 v[4:5], v[4:5], v[20:21], v[36:37]
; ; GFX1010-NEXT:    v_fma_f64 v[12:13], v[12:13], v[28:29], v[34:35]
; ; GFX1010-NEXT:    s_waitcnt vmcnt(2)
; ; GFX1010-NEXT:    v_fma_f64 v[10:11], v[10:11], v[26:27], v[38:39]
; ; GFX1010-NEXT:    v_fma_f64 v[14:15], v[14:15], v[30:31], v[32:33]
; ; GFX1010-NEXT:    s_clause 0x7
; ; GFX1010-NEXT:    buffer_load_dword v29, off, s[0:3], s32 offset:8
; ; GFX1010-NEXT:    buffer_load_dword v28, off, s[0:3], s32 offset:4
; ; GFX1010-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:32
; ; GFX1010-NEXT:    buffer_load_dword v30, off, s[0:3], s32 offset:28
; ; GFX1010-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:16
; ; GFX1010-NEXT:    buffer_load_dword v32, off, s[0:3], s32 offset:12
; ; GFX1010-NEXT:    buffer_load_dword v35, off, s[0:3], s32 offset:72
; ; GFX1010-NEXT:    buffer_load_dword v34, off, s[0:3], s32 offset:68
; ; GFX1010-NEXT:    s_waitcnt vmcnt(8)
; ; GFX1010-NEXT:    v_fma_f64 v[8:9], v[8:9], v[24:25], v[48:49]
; ; GFX1010-NEXT:    s_waitcnt vmcnt(6)
; ; GFX1010-NEXT:    v_fma_f64 v[0:1], v[0:1], v[16:17], v[28:29]
; ; GFX1010-NEXT:    s_waitcnt vmcnt(4)
; ; GFX1010-NEXT:    v_fma_f64 v[6:7], v[6:7], v[22:23], v[30:31]
; ; GFX1010-NEXT:    s_waitcnt vmcnt(2)
; ; GFX1010-NEXT:    v_fma_f64 v[2:3], v[2:3], v[18:19], v[32:33]
; ; GFX1010-NEXT:    s_round_mode 0x0
; ; GFX1010-NEXT:    s_waitcnt vmcnt(0)
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[12:15], off offset:48
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[8:11], off offset:32
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[4:7], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[8:11], off offset:32
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[12:15], off offset:48
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[0:3], off
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    global_store_dwordx4 v[34:35], v[4:7], off offset:16
; ; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; ; GFX1010-NEXT:    s_setpc_b64 s[30:31]
; ;
; ; GFX1250-LABEL: v_constrained_fma_v8f64:
; ; GFX1250:       ; %bb.0:
; ; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; ; GFX1250-NEXT:    s_wait_kmcnt 0x0
; ; GFX1250-NEXT:    s_clause 0x12
; ; GFX1250-NEXT:    scratch_load_b32 v35, off, s32 offset:16
; ; GFX1250-NEXT:    scratch_load_b32 v33, off, s32 offset:8
; ; GFX1250-NEXT:    scratch_load_b32 v39, off, s32 offset:32
; ; GFX1250-NEXT:    scratch_load_b32 v37, off, s32 offset:24
; ; GFX1250-NEXT:    scratch_load_b32 v51, off, s32 offset:48
; ; GFX1250-NEXT:    scratch_load_b32 v49, off, s32 offset:40
; ; GFX1250-NEXT:    scratch_load_b32 v31, off, s32
; ; GFX1250-NEXT:    scratch_load_b32 v55, off, s32 offset:64
; ; GFX1250-NEXT:    scratch_load_b32 v53, off, s32 offset:56
; ; GFX1250-NEXT:    scratch_load_b32 v52, off, s32 offset:52
; ; GFX1250-NEXT:    scratch_load_b32 v54, off, s32 offset:60
; ; GFX1250-NEXT:    scratch_load_b32 v48, off, s32 offset:36
; ; GFX1250-NEXT:    scratch_load_b32 v50, off, s32 offset:44
; ; GFX1250-NEXT:    scratch_load_b32 v36, off, s32 offset:20
; ; GFX1250-NEXT:    scratch_load_b32 v38, off, s32 offset:28
; ; GFX1250-NEXT:    scratch_load_b32 v32, off, s32 offset:4
; ; GFX1250-NEXT:    scratch_load_b32 v34, off, s32 offset:12
; ; GFX1250-NEXT:    scratch_load_b32 v65, off, s32 offset:72
; ; GFX1250-NEXT:    scratch_load_b32 v64, off, s32 offset:68
; ; GFX1250-NEXT:    s_round_mode 0xf
; ; GFX1250-NEXT:    s_wait_loadcnt 0x9
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[52:53], v[12:13], v[28:29]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x8
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[54:55], v[14:15], v[30:31]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x7
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[48:49], v[8:9], v[24:25]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x6
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[50:51], v[10:11], v[26:27]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x5
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[36:37], v[4:5], v[20:21]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x4
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[38:39], v[6:7], v[22:23]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x3
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[32:33], v[0:1], v[16:17]
; ; GFX1250-NEXT:    s_wait_loadcnt 0x2
; ; GFX1250-NEXT:    v_fmac_f64_e32 v[34:35], v[2:3], v[18:19]
; ; GFX1250-NEXT:    s_round_mode 0x0
; ; GFX1250-NEXT:    s_wait_loadcnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[52:55], off offset:48 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[48:51], off offset:32 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[36:39], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[32:35], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[48:51], off offset:32 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[52:55], off offset:48 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[32:35], off scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    global_store_b128 v[64:65], v[36:39], off offset:16 scope:SCOPE_SYS
; ; GFX1250-NEXT:    s_wait_storecnt 0x0
; ; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
;   call void @llvm.set.rounding(i32 0) #0
;   %r.a = call <8 x double> @llvm.experimental.constrained.fma.v8f64(<8 x double> %a, <8 x double> %b, <8 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   call void @llvm.set.rounding(i32 1) #0
;   %r.b = call <8 x double> @llvm.experimental.constrained.fma.v8f64(<8 x double> %a, <8 x double> %b, <8 x double> %c, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
;   store volatile <8 x double> %r.a, ptr addrspace(1) %out
;   store volatile <8 x double> %r.b, ptr addrspace(1) %out
;   ret void
; }

; attributes #0 = { strictfp nounwind }
