; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 < %s | FileCheck -check-prefixes=GFX1010 %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 < %s | FileCheck -check-prefixes=GFX1250 %s


declare void @llvm.set.rounding(i32)

declare float @llvm.experimental.constrained.sin.f32(float, metadata, metadata)
declare float @llvm.experimental.constrained.cos.f32(float, metadata, metadata)

define void @v_constrained_sin_f32(float %a0, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_sin_f32:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_mul_f32_e32 v3, 0.15915494, v0
; GFX1010-NEXT:    v_sin_f32_e32 v3, v3
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_mul_f32_e32 v0, 0.15915494, v0
; GFX1010-NEXT:    v_sin_f32_e32 v0, v0
; GFX1010-NEXT:    global_store_dword v[1:2], v3, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v[1:2], v0, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_sin_f32:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_dual_mov_b32 v3, v2 :: v_dual_mov_b32 v2, v1
; GFX1250-NEXT:    v_mul_f32_e32 v1, 0.15915494, v0
; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX1250-NEXT:    v_sin_f32_e32 v1, v1
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    v_mul_f32_e32 v0, 0.15915494, v0
; GFX1250-NEXT:    v_sin_f32_e32 v0, v0
; GFX1250-NEXT:    global_store_b32 v[2:3], v1, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v[2:3], v0, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call float @llvm.experimental.constrained.sin.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call float @llvm.experimental.constrained.sin.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile float %r.a, ptr addrspace(1) %out
  store volatile float %r.b, ptr addrspace(1) %out
  ret void
}

define void @v_constrained_cos_f32(float %a0, ptr addrspace(1) %out) #0 {
; GFX1010-LABEL: v_constrained_cos_f32:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_mul_f32_e32 v3, 0.15915494, v0
; GFX1010-NEXT:    v_cos_f32_e32 v3, v3
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_mul_f32_e32 v0, 0.15915494, v0
; GFX1010-NEXT:    v_cos_f32_e32 v0, v0
; GFX1010-NEXT:    global_store_dword v[1:2], v3, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v[1:2], v0, off
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1250-LABEL: v_constrained_cos_f32:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_dual_mov_b32 v3, v2 :: v_dual_mov_b32 v2, v1
; GFX1250-NEXT:    v_mul_f32_e32 v1, 0.15915494, v0
; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX1250-NEXT:    v_cos_f32_e32 v1, v1
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    v_mul_f32_e32 v0, 0.15915494, v0
; GFX1250-NEXT:    v_cos_f32_e32 v0, v0
; GFX1250-NEXT:    global_store_b32 v[2:3], v1, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v[2:3], v0, off scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_set_pc_i64 s[30:31]
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call float @llvm.experimental.constrained.cos.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call float @llvm.experimental.constrained.cos.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile float %r.a, ptr addrspace(1) %out
  store volatile float %r.b, ptr addrspace(1) %out
  ret void
}

; Uniform (SGPR) operands: exercises the pseudo-scalar transcendental form.
define amdgpu_kernel void @constrained_sin_f32(ptr addrspace(1) %out, float %a0) #0 {
; GFX1010-LABEL: constrained_sin_f32:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_clause 0x1
; GFX1010-NEXT:    s_load_dword s2, s[8:9], 0x8
; GFX1010-NEXT:    s_load_dwordx2 s[0:1], s[8:9], 0x0
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_mov_b32_e32 v2, 0
; GFX1010-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1010-NEXT:    v_mul_f32_e64 v0, s2, 0.15915494
; GFX1010-NEXT:    v_sin_f32_e32 v0, v0
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_mul_f32_e64 v1, s2, 0.15915494
; GFX1010-NEXT:    v_sin_f32_e32 v1, v1
; GFX1010-NEXT:    global_store_dword v2, v0, s[0:1]
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v2, v1, s[0:1]
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_endpgm
;
; GFX1250-LABEL: constrained_sin_f32:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_load_b96 s[0:2], s[4:5], 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_mov_b32_e32 v2, 0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_mul_f32 s3, s2, 0.15915494
; GFX1250-NEXT:    s_delay_alu instid0(SALU_CYCLE_3) | instskip(SKIP_2) | instid1(SALU_CYCLE_3)
; GFX1250-NEXT:    v_sin_f32_e32 v0, s3
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    s_mul_f32 s2, s2, 0.15915494
; GFX1250-NEXT:    v_sin_f32_e32 v1, s2
; GFX1250-NEXT:    global_store_b32 v2, v0, s[0:1] scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v2, v1, s[0:1] scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_endpgm
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call float @llvm.experimental.constrained.sin.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call float @llvm.experimental.constrained.sin.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile float %r.a, ptr addrspace(1) %out
  store volatile float %r.b, ptr addrspace(1) %out
  ret void
}

; Uniform (SGPR) operands: exercises the pseudo-scalar transcendental form.
define amdgpu_kernel void @constrained_cos_f32(ptr addrspace(1) %out, float %a0) #0 {
; GFX1010-LABEL: constrained_cos_f32:
; GFX1010:       ; %bb.0:
; GFX1010-NEXT:    s_clause 0x1
; GFX1010-NEXT:    s_load_dword s2, s[8:9], 0x8
; GFX1010-NEXT:    s_load_dwordx2 s[0:1], s[8:9], 0x0
; GFX1010-NEXT:    s_round_mode 0xf
; GFX1010-NEXT:    v_mov_b32_e32 v2, 0
; GFX1010-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1010-NEXT:    v_mul_f32_e64 v0, s2, 0.15915494
; GFX1010-NEXT:    v_cos_f32_e32 v0, v0
; GFX1010-NEXT:    s_round_mode 0x0
; GFX1010-NEXT:    v_mul_f32_e64 v1, s2, 0.15915494
; GFX1010-NEXT:    v_cos_f32_e32 v1, v1
; GFX1010-NEXT:    global_store_dword v2, v0, s[0:1]
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    global_store_dword v2, v1, s[0:1]
; GFX1010-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1010-NEXT:    s_endpgm
;
; GFX1250-LABEL: constrained_cos_f32:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_load_b96 s[0:2], s[4:5], 0x0
; GFX1250-NEXT:    s_round_mode 0xf
; GFX1250-NEXT:    v_mov_b32_e32 v2, 0
; GFX1250-NEXT:    s_wait_kmcnt 0x0
; GFX1250-NEXT:    s_mul_f32 s3, s2, 0.15915494
; GFX1250-NEXT:    s_delay_alu instid0(SALU_CYCLE_3) | instskip(SKIP_2) | instid1(SALU_CYCLE_3)
; GFX1250-NEXT:    v_cos_f32_e32 v0, s3
; GFX1250-NEXT:    s_round_mode 0x0
; GFX1250-NEXT:    s_mul_f32 s2, s2, 0.15915494
; GFX1250-NEXT:    v_cos_f32_e32 v1, s2
; GFX1250-NEXT:    global_store_b32 v2, v0, s[0:1] scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    global_store_b32 v2, v1, s[0:1] scope:SCOPE_SYS
; GFX1250-NEXT:    s_wait_storecnt 0x0
; GFX1250-NEXT:    s_endpgm
  call void @llvm.set.rounding(i32 0) #0
  %r.a = call float @llvm.experimental.constrained.cos.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  call void @llvm.set.rounding(i32 1) #0
  %r.b = call float @llvm.experimental.constrained.cos.f32(float %a0, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  store volatile float %r.a, ptr addrspace(1) %out
  store volatile float %r.b, ptr addrspace(1) %out
  ret void
}

attributes #0 = { strictfp nounwind }
